/*@@
   @header  TestTypes/CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn TestTypes
   @enddesc
 @@*/


#ifndef _TESTTYPES_PARAMETERS_H_
#define _TESTTYPES_PARAMETERS_H_ 1

#include "CParameterStructNames.h"
#include "ParameterCGlobal.h"
#include "ParameterCPrivateTESTTYPES.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_PRIVATE_TESTTYPES_STRUCT_PARAMS \


#endif  /* _TESTTYPES_PARAMETERS_H_ */

