#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,GRHydro_Y_e_max,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_Y_e_min,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_atmo_tolerance,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_del_ptol,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_eos_rf_prec,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_eps_min,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_hot_atmo_Y_e,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_hot_atmo_temp,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_lorentz_overshoot_cutoff,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_max_temp,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_perc_ptol,)&&\
CCTK_DECLARE(CCTK_REAL,GRHydro_rho_central,)&&\
CCTK_DECLARE(CCTK_REAL,Tmunu_damping_radius_max,)&&\
CCTK_DECLARE(CCTK_REAL,Tmunu_damping_radius_min,)&&\
CCTK_DECLARE(CCTK_REAL,atmo_falloff_power,)&&\
CCTK_DECLARE(CCTK_REAL,atmo_falloff_radius,)&&\
CCTK_DECLARE(CCTK_REAL,atmo_tolerance_power,)&&\
CCTK_DECLARE(CCTK_REAL,atmo_tolerance_radius,)&&\
CCTK_DECLARE(CCTK_REAL,c2p_reset_pressure_to_value,)&&\
CCTK_DECLARE(CCTK_REAL,comoving_factor,)&&\
CCTK_DECLARE(CCTK_REAL,comoving_tanh_factor,)&&\
CCTK_DECLARE(CCTK_REAL,comoving_tanh_offset,)&&\
CCTK_DECLARE(CCTK_REAL,enhanced_ppm_C2,)&&\
CCTK_DECLARE(CCTK_REAL,enhanced_ppm_C3,)&&\
CCTK_DECLARE(CCTK_REAL,initial_Gamma,)&&\
CCTK_DECLARE(CCTK_REAL,initial_atmosphere_factor,)&&\
CCTK_DECLARE(CCTK_REAL,initial_k,)&&\
CCTK_DECLARE(CCTK_REAL,initial_rho_abs_min,)&&\
CCTK_DECLARE(CCTK_REAL,initial_rho_rel_min,)&&\
CCTK_DECLARE(CCTK_REAL,kap_dc,)&&\
CCTK_DECLARE(CCTK_REAL,max_magnetic_to_gas_pressure_ratio,)&&\
CCTK_DECLARE(CCTK_REAL,min_tracer,)&&\
CCTK_DECLARE(CCTK_REAL,mp5_alpha,)&&\
CCTK_DECLARE(CCTK_REAL,mp5_eps,)&&\
CCTK_DECLARE(CCTK_REAL,myfloor,)&&\
CCTK_DECLARE(CCTK_REAL,ppm_epsilon,)&&\
CCTK_DECLARE(CCTK_REAL,ppm_epsilon_shock,)&&\
CCTK_DECLARE(CCTK_REAL,ppm_eta1,)&&\
CCTK_DECLARE(CCTK_REAL,ppm_eta2,)&&\
CCTK_DECLARE(CCTK_REAL,ppm_k0,)&&\
CCTK_DECLARE(CCTK_REAL,ppm_omega1,)&&\
CCTK_DECLARE(CCTK_REAL,ppm_omega2,)&&\
CCTK_DECLARE(CCTK_REAL,ppm_omega_tracer,)&&\
CCTK_DECLARE(CCTK_REAL,ppm_small,)&&\
CCTK_DECLARE(CCTK_REAL,rho_abs_min,)&&\
CCTK_DECLARE(CCTK_REAL,rho_abs_min_after_recovery,)&&\
CCTK_DECLARE(CCTK_REAL,rho_rel_min,)&&\
CCTK_DECLARE(CCTK_REAL,setcharmax,)&&\
CCTK_DECLARE(CCTK_REAL,setcharmin,)&&\
CCTK_DECLARE(CCTK_REAL,sqrtdet_thr,)&&\
CCTK_DECLARE(CCTK_REAL,tau_rel_min,)&&\
CCTK_DECLARE(CCTK_REAL,weno_eps,)&&\
CCTK_DECLARE(CCTK_STRING,Avec_gauge,)&&\
CCTK_DECLARE(CCTK_STRING,EoS_Change_type,)&&\
CCTK_DECLARE(CCTK_STRING,GRHydro_c2p_failed_action,)&&\
CCTK_DECLARE(CCTK_STRING,GRHydro_eos_table,)&&\
CCTK_DECLARE(CCTK_STRING,GRHydro_eos_type,)&&\
CCTK_DECLARE(CCTK_STRING,HLLE_type,)&&\
CCTK_DECLARE(CCTK_STRING,bound,)&&\
CCTK_DECLARE(CCTK_STRING,comoving_attenuate,)&&\
CCTK_DECLARE(CCTK_STRING,comoving_v_method,)&&\
CCTK_DECLARE(CCTK_STRING,gradient_method,)&&\
CCTK_DECLARE(CCTK_STRING,left_eigenvectors,)&&\
CCTK_DECLARE(CCTK_STRING,method_type,)&&\
CCTK_DECLARE(CCTK_STRING,numerical_viscosity,)&&\
CCTK_DECLARE(CCTK_STRING,particle_interpolator,)&&\
CCTK_DECLARE(CCTK_STRING,ppm_flatten,)&&\
CCTK_DECLARE(CCTK_STRING,psidcspeed,)&&\
CCTK_DECLARE(CCTK_STRING,recon_method,)&&\
CCTK_DECLARE(CCTK_STRING,recon_vars,)&&\
CCTK_DECLARE(CCTK_STRING,riemann_solver,)&&\
CCTK_DECLARE(CCTK_STRING,tvd_limiter,)&&\
CCTK_DECLARE(CCTK_STRING,use_evolution_mask,)&&\
CCTK_DECLARE(CCTK_INT,Check_Rho_Minimum,)&&\
CCTK_DECLARE(CCTK_INT,EoS_Change,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_MaxNumConstrainedVars,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_MaxNumEvolvedVars,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_MaxNumEvolvedVarsSlow,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_MaxNumSandRVars,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_NaN_verbose,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_c2p_reset_eps_tau_hot_eos,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_c2p_warn_from_reflevel,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_c2p_warnlevel,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_countmax,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_countmin,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_enable_internal_excision,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_eos_hot_eps_fix,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_eos_hot_prim2con_warn,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_hydro_excision,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_oppm_reflevel,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_polish,)&&\
CCTK_DECLARE(CCTK_INT,GRHydro_stencil,)&&\
CCTK_DECLARE(CCTK_INT,WENO_order,)&&\
CCTK_DECLARE(CCTK_INT,apply_H_viscosity,)&&\
CCTK_DECLARE(CCTK_INT,c2p_reset_pressure,)&&\
CCTK_DECLARE(CCTK_INT,c2p_resort_to_bisection,)&&\
CCTK_DECLARE(CCTK_INT,calculate_bcom,)&&\
CCTK_DECLARE(CCTK_INT,check_for_trivial_rp,)&&\
CCTK_DECLARE(CCTK_INT,clean_divergence,)&&\
CCTK_DECLARE(CCTK_INT,con2prim_oct_hack,)&&\
CCTK_DECLARE(CCTK_INT,decouple_normal_Bfield,)&&\
CCTK_DECLARE(CCTK_INT,eno_order,)&&\
CCTK_DECLARE(CCTK_INT,evolve_tracer,)&&\
CCTK_DECLARE(CCTK_INT,mp5_adaptive_eps,)&&\
CCTK_DECLARE(CCTK_INT,number_of_arrays,)&&\
CCTK_DECLARE(CCTK_INT,number_of_particles,)&&\
CCTK_DECLARE(CCTK_INT,number_of_tracers,)&&\
CCTK_DECLARE(CCTK_INT,particle_interpolation_order,)&&\
CCTK_DECLARE(CCTK_INT,ppm_detect,)&&\
CCTK_DECLARE(CCTK_INT,ppm_mppm,)&&\
CCTK_DECLARE(CCTK_INT,ppm_mppm_debug_eigenvalues,)&&\
CCTK_DECLARE(CCTK_INT,reconstruct_Wv,)&&\
CCTK_DECLARE(CCTK_INT,reconstruct_temper,)&&\
CCTK_DECLARE(CCTK_INT,set_trivial_rp_grid_function,)&&\
CCTK_DECLARE(CCTK_INT,sources_spatial_order,)&&\
CCTK_DECLARE(CCTK_INT,sync_conserved_only,)&&\
CCTK_DECLARE(CCTK_INT,track_divB,)&&\
CCTK_DECLARE(CCTK_INT,transport_constraints,)&&\
CCTK_DECLARE(CCTK_INT,use_MoL_slow_multirate_sector,)&&\
CCTK_DECLARE(CCTK_INT,use_enhanced_ppm,)&&\
CCTK_DECLARE(CCTK_INT,use_min_tracer,)&&\
CCTK_DECLARE(CCTK_INT,use_optimized_ppm,)&&\
CCTK_DECLARE(CCTK_INT,use_weighted_fluxes,)&&\
CCTK_DECLARE(CCTK_INT,weno_adaptive_epsilon,)&&\
CCTK_DECLARE(CCTK_INT,wk_atmosphere,)&&\
COMMON /GRHydrorest/GRHydro_Y_e_max, GRHydro_Y_e_min, GRHydro_atmo_tolerance, GRHydro_del_ptol, GRHydro_eos_rf_prec, GRHydro_eps_min, GRHydro_hot_atmo_Y_e, GRHydro_hot_atmo_temp, GRHydro_lorentz_overshoot_cutoff, GRHydro_max_temp, GRHydro_perc_ptol, GRHydro_rho_central, Tmunu_damping_radius_max, Tmunu_damping_radius_min, atmo_falloff_power, atmo_falloff_radius, atmo_tolerance_power, atmo_tolerance_radius, c2p_reset_pressure_to_value, comoving_factor, comoving_tanh_factor, comoving_tanh_offset, enhanced_ppm_C2, enhanced_ppm_C3, initial_Gamma, initial_atmosphere_factor, initial_k, initial_rho_abs_min, initial_rho_rel_min, kap_dc, max_magnetic_to_gas_pressure_ratio, min_tracer, mp5_alpha, mp5_eps, myfloor, ppm_epsilon, ppm_epsilon_shock, ppm_eta1, ppm_eta2, ppm_k0, ppm_omega1, ppm_omega2, ppm_omega_tracer, ppm_small, rho_abs_min, rho_abs_min_after_recovery, rho_rel_min, setcharmax, setcharmin, sqrtdet_thr, tau_rel_min, weno_eps, Avec_gauge, EoS_Change_type, GRHydro_c2p_failed_action, GRHydro_eos_table, GRHydro_eos_type, HLLE_type, bound, comoving_attenuate, comoving_v_method, gradient_method, left_eigenvectors, method_type, numerical_viscosity, particle_interpolator, ppm_flatten, psidcspeed, recon_method, recon_vars, riemann_solver, tvd_limiter, use_evolution_mask, Check_Rho_Minimum, EoS_Change, GRHydro_MaxNumConstrainedVars, GRHydro_MaxNumEvolvedVars, GRHydro_MaxNumEvolvedVarsSlow, GRHydro_MaxNumSandRVars, GRHydro_NaN_verbose, GRHydro_c2p_reset_eps_tau_hot_eos, GRHydro_c2p_warn_from_reflevel, GRHydro_c2p_warnlevel, GRHydro_countmax, GRHydro_countmin, GRHydro_enable_internal_excision, GRHydro_eos_hot_eps_fix, GRHydro_eos_hot_prim2con_warn, GRHydro_hydro_excision, GRHydro_oppm_reflevel, GRHydro_polish, GRHydro_stencil, WENO_order, apply_H_viscosity, c2p_reset_pressure, c2p_resort_to_bisection, calculate_bcom, check_for_trivial_rp, clean_divergence, con2prim_oct_hack, decouple_normal_Bfield, eno_order, evolve_tracer, mp5_adaptive_eps, number_of_arrays, number_of_particles, number_of_tracers, particle_interpolation_order, ppm_detect, ppm_mppm, ppm_mppm_debug_eigenvalues, reconstruct_Wv, reconstruct_temper, set_trivial_rp_grid_function, sources_spatial_order, sync_conserved_only, track_divB, transport_constraints, use_MoL_slow_multirate_sector, use_enhanced_ppm, use_min_tracer, use_optimized_ppm, use_weighted_fluxes, weno_adaptive_epsilon, wk_atmosphere&&\
CCTK_DECLARE(CCTK_INT,constrain_to_1D,)&&\
CCTK_DECLARE(CCTK_INT,use_cxx_code,)&&\
CCTK_DECLARE(CCTK_INT,verbose,)&&\
COMMON /GRHydropriv/constrain_to_1D, use_cxx_code, verbose&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,initial_shift,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH8,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH11,)&&\
CCTK_DECLARE(CCTK_STRING,metric_type,)&&\
CCTK_DECLARE(CCTK_STRING,shift_evolution_method,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH13,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH12,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH14,)&&\
COMMON /ADMBASErest/CCTKH0, CCTKH1, CCTKH2, CCTKH3, CCTKH4, CCTKH5, CCTKH6, CCTKH7, initial_shift, CCTKH8, CCTKH9, CCTKH11, metric_type, shift_evolution_method, CCTKH13, CCTKH10, CCTKH12, CCTKH14&&\
CCTK_DECLARE(CCTK_REAL,CCTKH15,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH25,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH26,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH27,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH28,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH29,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH30,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH31,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH34,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH35,)&&\
CCTK_DECLARE(CCTK_REAL,poly_k,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH17,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH20,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH24,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH33,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH16,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH18,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH19,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH21,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH22,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH23,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH32,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH36,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH37,)&&\
COMMON /EOS_OMNIrest/CCTKH15, CCTKH25, CCTKH26, CCTKH27, CCTKH28, CCTKH29, CCTKH30, CCTKH31, CCTKH34, CCTKH35, poly_k, CCTKH17, CCTKH20, CCTKH24, CCTKH33, CCTKH16, CCTKH18, CCTKH19, CCTKH21, CCTKH22, CCTKH23, CCTKH32, CCTKH36, CCTKH37&&\
CCTK_DECLARE(CCTK_STRING,CCTKH38,)&&\
CCTK_DECLARE(CCTK_STRING,Bvec_evolution_method,)&&\
CCTK_DECLARE(CCTK_STRING,Y_e_evolution_method,)&&\
CCTK_DECLARE(CCTK_STRING,entropy_evolution_method,)&&\
CCTK_DECLARE(CCTK_STRING,evolution_method,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH39,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH40,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH41,)&&\
CCTK_DECLARE(CCTK_STRING,initial_Bvec,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH42,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH43,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH44,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH45,)&&\
CCTK_DECLARE(CCTK_STRING,prolongation_type,)&&\
CCTK_DECLARE(CCTK_STRING,temperature_evolution_method,)&&\
CCTK_DECLARE(CCTK_INT,hydro_excision,)&&\
CCTK_DECLARE(CCTK_INT,timelevels,)&&\
COMMON /HYDROBASErest/CCTKH38, Bvec_evolution_method, Y_e_evolution_method, entropy_evolution_method, evolution_method, CCTKH39, CCTKH40, CCTKH41, initial_Bvec, CCTKH42, CCTKH43, CCTKH44, CCTKH45, prolongation_type, temperature_evolution_method, hydro_excision, timelevels&&\
CCTK_DECLARE(CCTK_INT,MoL_Max_Evolved_Array_Size,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH46,)&&\
CCTK_DECLARE(CCTK_INT,MoL_Num_ArrayEvolved_Vars,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH47,)&&\
CCTK_DECLARE(CCTK_INT,MoL_Num_Constrained_Vars,)&&\
CCTK_DECLARE(CCTK_INT,MoL_Num_Evolved_Vars,)&&\
CCTK_DECLARE(CCTK_INT,MoL_Num_Evolved_Vars_Slow,)&&\
CCTK_DECLARE(CCTK_INT,MoL_Num_SaveAndRestore_Vars,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH48,)&&\
COMMON /METHODOFLINESrest/MoL_Max_Evolved_Array_Size, CCTKH46, MoL_Num_ArrayEvolved_Vars, CCTKH47, MoL_Num_Constrained_Vars, MoL_Num_Evolved_Vars, MoL_Num_Evolved_Vars_Slow, MoL_Num_SaveAndRestore_Vars, CCTKH48&&\
CCTK_DECLARE(CCTK_INT,use_mask,)&&\
COMMON /SPACEMASKrest/use_mask&&\

