/*@@
   @header  CarpetTracker_Prototypes.h
   @author  Automatically generated by CreateFunctionBindings.pl
   @desc
            Prototypes for overloaded functions used by this thorn
   @enddesc
  @@*/


#ifndef _CARPETTRACKER_PROTOTYPES_H_
#define _CARPETTRACKER_PROTOTYPES_H_  1

#ifdef CCODE
#ifdef __cplusplus
extern "C" {
#endif

CCTK_INT sf_IdFromName(const CCTK_INT id ,
 const CCTK_POINTER_TO_CONST name);

#ifdef __cplusplus
}
#endif
#endif /* CCODE */

#ifdef FCODE
#ifdef F90CODE
#define DECLARE_CARPETTRACKER_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \
  interface &&\
     CCTK_INT function sf_IdFromName (id, name) &&\
       implicit none &&\
       CCTK_INT id &&\
       CCTK_POINTER_TO_CONST name &&\
     end function sf_IdFromName &&\
  end interface &&\

#else /* ! F90CODE */

#define DECLARE_CARPETTRACKER_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \
  external sf_IdFromName &&\
  CCTK_INT sf_IdFromName &&\

#endif /* ! F90CODE */
#endif /* FCODE */

#endif

