/*@@
   @header  PAPI_Arguments.h
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Defines macros to declare/define/pass function arguments
            in calls from C to Fortran for thorn PAPI
   @enddesc
 @@*/


#ifdef FCODE
#define DECLARE_PAPI_PRIVATE_FARGUMENTS \


#define PAPI_PRIVATE_FARGUMENTS \


#endif /* FCODE */

#ifdef CCODE
#define DECLARE_PAPI_PRIVATE_CARGUMENTS \


#define DECLARE_PAPI_PRIVATE_C2F \


#define INITIALISE_PAPI_PRIVATE_C2F \


#define PAPI_PRIVATE_C2F_PROTO \


#define PASS_PAPI_PRIVATE_C2F(GH) \


#endif /* CCODE */

#ifdef FCODE
#define DECLARE_PAPI_PROTECTED_FARGUMENTS \


#define PAPI_PROTECTED_FARGUMENTS \


#endif /* FCODE */

#ifdef CCODE
#define DECLARE_PAPI_PROTECTED_CARGUMENTS \


#define DECLARE_PAPI_PROTECTED_C2F \


#define INITIALISE_PAPI_PROTECTED_C2F \


#define PAPI_PROTECTED_C2F_PROTO \


#define PASS_PAPI_PROTECTED_C2F(GH) \


#endif /* CCODE */

#ifdef FCODE
#define DECLARE_PAPI_PUBLIC_FARGUMENTS \


#define PAPI_PUBLIC_FARGUMENTS \


#endif /* FCODE */

#ifdef CCODE
#define DECLARE_PAPI_PUBLIC_CARGUMENTS \


#define DECLARE_PAPI_PUBLIC_C2F \


#define INITIALISE_PAPI_PUBLIC_C2F \


#define PAPI_PUBLIC_C2F_PROTO \


#define PASS_PAPI_PUBLIC_C2F(GH) \


#endif /* CCODE */

#ifdef FCODE
#define PAPI_FARGUMENTS _CCTK_FARGUMENTS

#define DECLARE_PAPI_FARGUMENTS _DECLARE_CCTK_FARGUMENTS

#endif /* FCODE */

#ifdef CCODE
#define DECLARE_PAPI_CARGUMENTS _DECLARE_CCTK_CARGUMENTS

#define PAPI_C2F_PROTO _CCTK_C2F_PROTO

#define PASS_PAPI_C2F(GH) _PASS_CCTK_C2F(GH)

#define DECLARE_PAPI_C2F _DECLARE_CCTK_C2F

#define INITIALISE_PAPI_C2F _INITIALISE_CCTK_C2F

#define PAPI_CARGUMENTS cGH *cctkGH

#endif /* CCODE */
