#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL EM_Rin[100];
  CCTK_REAL EM_Rout[100];
  CCTK_REAL Rin;
  CCTK_REAL Rout;
  const char * action_on_hdf5_error;
  const char * out_dir;
  CCTK_INT do_test;
  CCTK_INT extract_spacetime_metric_every;
  CCTK_INT max_spin;
  CCTK_INT num_l_modes;
  CCTK_INT num_mu_points;
  CCTK_INT num_n_modes;
  CCTK_INT num_phi_points;
  CCTK_INT num_radii;
  CCTK_INT num_x_points;
  CCTK_INT output_l_max;
  CCTK_INT output_m_max;
  CCTK_INT sync_file_each_time;
} PRIVATE_SPHERICALHARMONICDECOMP_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_SPHERICALHARMONICDECOMP_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const * const, EM_Rin, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__EM_Rin); \
  CCTK_DECLARE_INIT (CCTK_REAL const * const, EM_Rout, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__EM_Rout); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Rin, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__Rin); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Rout, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__Rout); \
  CCTK_DECLARE_INIT (const char * const, action_on_hdf5_error, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__action_on_hdf5_error); \
  CCTK_DECLARE_INIT (const char * const, out_dir, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__out_dir); \
  CCTK_DECLARE_INIT (CCTK_INT const, do_test, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__do_test); \
  CCTK_DECLARE_INIT (CCTK_INT const, extract_spacetime_metric_every, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__extract_spacetime_metric_every); \
  CCTK_DECLARE_INIT (CCTK_INT const, max_spin, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__max_spin); \
  CCTK_DECLARE_INIT (CCTK_INT const, num_l_modes, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_l_modes); \
  CCTK_DECLARE_INIT (CCTK_INT const, num_mu_points, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_mu_points); \
  CCTK_DECLARE_INIT (CCTK_INT const, num_n_modes, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_n_modes); \
  CCTK_DECLARE_INIT (CCTK_INT const, num_phi_points, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_phi_points); \
  CCTK_DECLARE_INIT (CCTK_INT const, num_radii, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_radii); \
  CCTK_DECLARE_INIT (CCTK_INT const, num_x_points, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_x_points); \
  CCTK_DECLARE_INIT (CCTK_INT const, output_l_max, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__output_l_max); \
  CCTK_DECLARE_INIT (CCTK_INT const, output_m_max, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__output_m_max); \
  CCTK_DECLARE_INIT (CCTK_INT const, sync_file_each_time, CCTK_PARAMETER__SPHERICALHARMONICDECOMP__sync_file_each_time); \


#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__EM_Rin
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__EM_Rin PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.EM_Rin
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__EM_Rout
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__EM_Rout PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.EM_Rout
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__Rin
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__Rin PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.Rin
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__Rout
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__Rout PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.Rout
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__action_on_hdf5_error
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__action_on_hdf5_error PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.action_on_hdf5_error
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__out_dir
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__out_dir PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.out_dir
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__do_test
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__do_test PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.do_test
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__extract_spacetime_metric_every
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__extract_spacetime_metric_every PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.extract_spacetime_metric_every
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__max_spin
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__max_spin PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.max_spin
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_l_modes
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_l_modes PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.num_l_modes
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_mu_points
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_mu_points PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.num_mu_points
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_n_modes
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_n_modes PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.num_n_modes
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_phi_points
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_phi_points PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.num_phi_points
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_radii
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_radii PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.num_radii
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_x_points
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__num_x_points PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.num_x_points
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__output_l_max
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__output_l_max PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.output_l_max
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__output_m_max
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__output_m_max PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.output_m_max
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICDECOMP__sync_file_each_time
#  define CCTK_PARAMETER__SPHERICALHARMONICDECOMP__sync_file_each_time PRIVATE_SPHERICALHARMONICDECOMP_STRUCT.sync_file_each_time
#endif

