#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL Hydro_Analysis_core_rho_rel_min;
  CCTK_REAL Hydro_Analysis_r_core;
  const char * Hydro_Analysis_interpolator_coordinates;
  const char * Hydro_Analysis_interpolator_name;
  const char * Hydro_Analysis_interpolator_options;
  CCTK_INT Hydro_Analysis_average_multiple_maxima_locations;
  CCTK_INT Hydro_Analysis_comp_core_rho_centroid;
  CCTK_INT Hydro_Analysis_comp_rho_max;
  CCTK_INT Hydro_Analysis_comp_rho_max_every;
  CCTK_INT Hydro_Analysis_comp_rho_max_origin_distance;
  CCTK_INT Hydro_Analysis_comp_vol_weighted_center_of_mass;
  CCTK_INT Hydro_Analysis_rho_max_loc_only_positive_x;
  CCTK_INT Hydro_Analysis_rho_max_loc_use_rotatingsymmetry180;
  CCTK_INT Hydro_Analysis_rho_max_origin_distance_npoints;
  CCTK_INT verbosity_level;
} PRIVATE_HYDRO_ANALYSIS_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_HYDRO_ANALYSIS_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, Hydro_Analysis_core_rho_rel_min, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_core_rho_rel_min); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Hydro_Analysis_r_core, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_r_core); \
  CCTK_DECLARE_INIT (const char * const, Hydro_Analysis_interpolator_coordinates, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_interpolator_coordinates); \
  CCTK_DECLARE_INIT (const char * const, Hydro_Analysis_interpolator_name, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_interpolator_name); \
  CCTK_DECLARE_INIT (const char * const, Hydro_Analysis_interpolator_options, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_interpolator_options); \
  CCTK_DECLARE_INIT (CCTK_INT const, Hydro_Analysis_average_multiple_maxima_locations, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_average_multiple_maxima_locations); \
  CCTK_DECLARE_INIT (CCTK_INT const, Hydro_Analysis_comp_core_rho_centroid, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_core_rho_centroid); \
  CCTK_DECLARE_INIT (CCTK_INT const, Hydro_Analysis_comp_rho_max, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_rho_max); \
  CCTK_DECLARE_INIT (CCTK_INT const, Hydro_Analysis_comp_rho_max_every, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_rho_max_every); \
  CCTK_DECLARE_INIT (CCTK_INT const, Hydro_Analysis_comp_rho_max_origin_distance, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_rho_max_origin_distance); \
  CCTK_DECLARE_INIT (CCTK_INT const, Hydro_Analysis_comp_vol_weighted_center_of_mass, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_vol_weighted_center_of_mass); \
  CCTK_DECLARE_INIT (CCTK_INT const, Hydro_Analysis_rho_max_loc_only_positive_x, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_rho_max_loc_only_positive_x); \
  CCTK_DECLARE_INIT (CCTK_INT const, Hydro_Analysis_rho_max_loc_use_rotatingsymmetry180, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_rho_max_loc_use_rotatingsymmetry180); \
  CCTK_DECLARE_INIT (CCTK_INT const, Hydro_Analysis_rho_max_origin_distance_npoints, CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_rho_max_origin_distance_npoints); \
  CCTK_DECLARE_INIT (CCTK_INT const, verbosity_level, CCTK_PARAMETER__HYDRO_ANALYSIS__verbosity_level); \


#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_core_rho_rel_min
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_core_rho_rel_min PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_core_rho_rel_min
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_r_core
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_r_core PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_r_core
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_interpolator_coordinates
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_interpolator_coordinates PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_interpolator_coordinates
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_interpolator_name
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_interpolator_name PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_interpolator_name
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_interpolator_options
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_interpolator_options PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_interpolator_options
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_average_multiple_maxima_locations
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_average_multiple_maxima_locations PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_average_multiple_maxima_locations
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_core_rho_centroid
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_core_rho_centroid PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_comp_core_rho_centroid
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_rho_max
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_rho_max PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_comp_rho_max
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_rho_max_every
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_rho_max_every PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_comp_rho_max_every
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_rho_max_origin_distance
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_rho_max_origin_distance PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_comp_rho_max_origin_distance
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_vol_weighted_center_of_mass
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_comp_vol_weighted_center_of_mass PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_comp_vol_weighted_center_of_mass
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_rho_max_loc_only_positive_x
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_rho_max_loc_only_positive_x PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_rho_max_loc_only_positive_x
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_rho_max_loc_use_rotatingsymmetry180
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_rho_max_loc_use_rotatingsymmetry180 PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_rho_max_loc_use_rotatingsymmetry180
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_rho_max_origin_distance_npoints
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__Hydro_Analysis_rho_max_origin_distance_npoints PRIVATE_HYDRO_ANALYSIS_STRUCT.Hydro_Analysis_rho_max_origin_distance_npoints
#endif
#ifndef CCTK_PARAMETER__HYDRO_ANALYSIS__verbosity_level
#  define CCTK_PARAMETER__HYDRO_ANALYSIS__verbosity_level PRIVATE_HYDRO_ANALYSIS_STRUCT.verbosity_level
#endif

