#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_INT tghost4d;
  CCTK_INT tsize4d;
  CCTK_INT xghost1d;
  CCTK_INT xghost2d;
  CCTK_INT xghost3d;
  CCTK_INT xghost4d;
  CCTK_INT xsize1d;
  CCTK_INT xsize2d;
  CCTK_INT xsize3d;
  CCTK_INT xsize4d;
  CCTK_INT yghost2d;
  CCTK_INT yghost3d;
  CCTK_INT yghost4d;
  CCTK_INT ysize2d;
  CCTK_INT ysize3d;
  CCTK_INT ysize4d;
  CCTK_INT zghost3d;
  CCTK_INT zghost4d;
  CCTK_INT zsize3d;
  CCTK_INT zsize4d;
} PRIVATE_TESTARRAYS_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_TESTARRAYS_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_INT const, tghost4d, CCTK_PARAMETER__TESTARRAYS__tghost4d); \
  CCTK_DECLARE_INIT (CCTK_INT const, tsize4d, CCTK_PARAMETER__TESTARRAYS__tsize4d); \
  CCTK_DECLARE_INIT (CCTK_INT const, xghost1d, CCTK_PARAMETER__TESTARRAYS__xghost1d); \
  CCTK_DECLARE_INIT (CCTK_INT const, xghost2d, CCTK_PARAMETER__TESTARRAYS__xghost2d); \
  CCTK_DECLARE_INIT (CCTK_INT const, xghost3d, CCTK_PARAMETER__TESTARRAYS__xghost3d); \
  CCTK_DECLARE_INIT (CCTK_INT const, xghost4d, CCTK_PARAMETER__TESTARRAYS__xghost4d); \
  CCTK_DECLARE_INIT (CCTK_INT const, xsize1d, CCTK_PARAMETER__TESTARRAYS__xsize1d); \
  CCTK_DECLARE_INIT (CCTK_INT const, xsize2d, CCTK_PARAMETER__TESTARRAYS__xsize2d); \
  CCTK_DECLARE_INIT (CCTK_INT const, xsize3d, CCTK_PARAMETER__TESTARRAYS__xsize3d); \
  CCTK_DECLARE_INIT (CCTK_INT const, xsize4d, CCTK_PARAMETER__TESTARRAYS__xsize4d); \
  CCTK_DECLARE_INIT (CCTK_INT const, yghost2d, CCTK_PARAMETER__TESTARRAYS__yghost2d); \
  CCTK_DECLARE_INIT (CCTK_INT const, yghost3d, CCTK_PARAMETER__TESTARRAYS__yghost3d); \
  CCTK_DECLARE_INIT (CCTK_INT const, yghost4d, CCTK_PARAMETER__TESTARRAYS__yghost4d); \
  CCTK_DECLARE_INIT (CCTK_INT const, ysize2d, CCTK_PARAMETER__TESTARRAYS__ysize2d); \
  CCTK_DECLARE_INIT (CCTK_INT const, ysize3d, CCTK_PARAMETER__TESTARRAYS__ysize3d); \
  CCTK_DECLARE_INIT (CCTK_INT const, ysize4d, CCTK_PARAMETER__TESTARRAYS__ysize4d); \
  CCTK_DECLARE_INIT (CCTK_INT const, zghost3d, CCTK_PARAMETER__TESTARRAYS__zghost3d); \
  CCTK_DECLARE_INIT (CCTK_INT const, zghost4d, CCTK_PARAMETER__TESTARRAYS__zghost4d); \
  CCTK_DECLARE_INIT (CCTK_INT const, zsize3d, CCTK_PARAMETER__TESTARRAYS__zsize3d); \
  CCTK_DECLARE_INIT (CCTK_INT const, zsize4d, CCTK_PARAMETER__TESTARRAYS__zsize4d); \


#ifndef CCTK_PARAMETER__TESTARRAYS__tghost4d
#  define CCTK_PARAMETER__TESTARRAYS__tghost4d PRIVATE_TESTARRAYS_STRUCT.tghost4d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__tsize4d
#  define CCTK_PARAMETER__TESTARRAYS__tsize4d PRIVATE_TESTARRAYS_STRUCT.tsize4d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__xghost1d
#  define CCTK_PARAMETER__TESTARRAYS__xghost1d PRIVATE_TESTARRAYS_STRUCT.xghost1d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__xghost2d
#  define CCTK_PARAMETER__TESTARRAYS__xghost2d PRIVATE_TESTARRAYS_STRUCT.xghost2d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__xghost3d
#  define CCTK_PARAMETER__TESTARRAYS__xghost3d PRIVATE_TESTARRAYS_STRUCT.xghost3d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__xghost4d
#  define CCTK_PARAMETER__TESTARRAYS__xghost4d PRIVATE_TESTARRAYS_STRUCT.xghost4d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__xsize1d
#  define CCTK_PARAMETER__TESTARRAYS__xsize1d PRIVATE_TESTARRAYS_STRUCT.xsize1d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__xsize2d
#  define CCTK_PARAMETER__TESTARRAYS__xsize2d PRIVATE_TESTARRAYS_STRUCT.xsize2d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__xsize3d
#  define CCTK_PARAMETER__TESTARRAYS__xsize3d PRIVATE_TESTARRAYS_STRUCT.xsize3d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__xsize4d
#  define CCTK_PARAMETER__TESTARRAYS__xsize4d PRIVATE_TESTARRAYS_STRUCT.xsize4d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__yghost2d
#  define CCTK_PARAMETER__TESTARRAYS__yghost2d PRIVATE_TESTARRAYS_STRUCT.yghost2d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__yghost3d
#  define CCTK_PARAMETER__TESTARRAYS__yghost3d PRIVATE_TESTARRAYS_STRUCT.yghost3d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__yghost4d
#  define CCTK_PARAMETER__TESTARRAYS__yghost4d PRIVATE_TESTARRAYS_STRUCT.yghost4d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__ysize2d
#  define CCTK_PARAMETER__TESTARRAYS__ysize2d PRIVATE_TESTARRAYS_STRUCT.ysize2d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__ysize3d
#  define CCTK_PARAMETER__TESTARRAYS__ysize3d PRIVATE_TESTARRAYS_STRUCT.ysize3d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__ysize4d
#  define CCTK_PARAMETER__TESTARRAYS__ysize4d PRIVATE_TESTARRAYS_STRUCT.ysize4d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__zghost3d
#  define CCTK_PARAMETER__TESTARRAYS__zghost3d PRIVATE_TESTARRAYS_STRUCT.zghost3d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__zghost4d
#  define CCTK_PARAMETER__TESTARRAYS__zghost4d PRIVATE_TESTARRAYS_STRUCT.zghost4d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__zsize3d
#  define CCTK_PARAMETER__TESTARRAYS__zsize3d PRIVATE_TESTARRAYS_STRUCT.zsize3d
#endif
#ifndef CCTK_PARAMETER__TESTARRAYS__zsize4d
#  define CCTK_PARAMETER__TESTARRAYS__zsize4d PRIVATE_TESTARRAYS_STRUCT.zsize4d
#endif

