#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL amplitude;
  CCTK_REAL radius;
  CCTK_REAL sigma;
  CCTK_REAL uniform_weight_value;
  CCTK_INT array_nx;
  CCTK_INT array_ny;
  CCTK_INT array_nz;
  CCTK_INT dest_proc;
  CCTK_INT map_x;
  CCTK_INT map_y;
  CCTK_INT map_z;
} PRIVATE_TESTGLOBALREDUCE_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_TESTGLOBALREDUCE_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, amplitude, CCTK_PARAMETER__TESTGLOBALREDUCE__amplitude); \
  CCTK_DECLARE_INIT (CCTK_REAL const, radius, CCTK_PARAMETER__TESTGLOBALREDUCE__radius); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma, CCTK_PARAMETER__TESTGLOBALREDUCE__sigma); \
  CCTK_DECLARE_INIT (CCTK_REAL const, uniform_weight_value, CCTK_PARAMETER__TESTGLOBALREDUCE__uniform_weight_value); \
  CCTK_DECLARE_INIT (CCTK_INT const, array_nx, CCTK_PARAMETER__TESTGLOBALREDUCE__array_nx); \
  CCTK_DECLARE_INIT (CCTK_INT const, array_ny, CCTK_PARAMETER__TESTGLOBALREDUCE__array_ny); \
  CCTK_DECLARE_INIT (CCTK_INT const, array_nz, CCTK_PARAMETER__TESTGLOBALREDUCE__array_nz); \
  CCTK_DECLARE_INIT (CCTK_INT const, dest_proc, CCTK_PARAMETER__TESTGLOBALREDUCE__dest_proc); \
  CCTK_DECLARE_INIT (CCTK_INT const, map_x, CCTK_PARAMETER__TESTGLOBALREDUCE__map_x); \
  CCTK_DECLARE_INIT (CCTK_INT const, map_y, CCTK_PARAMETER__TESTGLOBALREDUCE__map_y); \
  CCTK_DECLARE_INIT (CCTK_INT const, map_z, CCTK_PARAMETER__TESTGLOBALREDUCE__map_z); \


#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__amplitude
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__amplitude PRIVATE_TESTGLOBALREDUCE_STRUCT.amplitude
#endif
#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__radius
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__radius PRIVATE_TESTGLOBALREDUCE_STRUCT.radius
#endif
#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__sigma
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__sigma PRIVATE_TESTGLOBALREDUCE_STRUCT.sigma
#endif
#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__uniform_weight_value
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__uniform_weight_value PRIVATE_TESTGLOBALREDUCE_STRUCT.uniform_weight_value
#endif
#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__array_nx
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__array_nx PRIVATE_TESTGLOBALREDUCE_STRUCT.array_nx
#endif
#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__array_ny
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__array_ny PRIVATE_TESTGLOBALREDUCE_STRUCT.array_ny
#endif
#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__array_nz
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__array_nz PRIVATE_TESTGLOBALREDUCE_STRUCT.array_nz
#endif
#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__dest_proc
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__dest_proc PRIVATE_TESTGLOBALREDUCE_STRUCT.dest_proc
#endif
#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__map_x
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__map_x PRIVATE_TESTGLOBALREDUCE_STRUCT.map_x
#endif
#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__map_y
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__map_y PRIVATE_TESTGLOBALREDUCE_STRUCT.map_y
#endif
#ifndef CCTK_PARAMETER__TESTGLOBALREDUCE__map_z
#  define CCTK_PARAMETER__TESTGLOBALREDUCE__map_z PRIVATE_TESTGLOBALREDUCE_STRUCT.map_z
#endif

