#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL amp;
  CCTK_REAL c;
  CCTK_REAL eta0;
  CCTK_REAL etamax;
  CCTK_REAL sigma;
  CCTK_REAL tolerance;
  CCTK_INT interpolation_order;
  CCTK_INT n;
  CCTK_INT neta;
  CCTK_INT nphi;
  CCTK_INT ntheta;
} PRIVATE_DISTORTEDBHIVP_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_DISTORTEDBHIVP_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, amp, CCTK_PARAMETER__DISTORTEDBHIVP__amp); \
  CCTK_DECLARE_INIT (CCTK_REAL const, c, CCTK_PARAMETER__DISTORTEDBHIVP__c); \
  CCTK_DECLARE_INIT (CCTK_REAL const, eta0, CCTK_PARAMETER__DISTORTEDBHIVP__eta0); \
  CCTK_DECLARE_INIT (CCTK_REAL const, etamax, CCTK_PARAMETER__DISTORTEDBHIVP__etamax); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma, CCTK_PARAMETER__DISTORTEDBHIVP__sigma); \
  CCTK_DECLARE_INIT (CCTK_REAL const, tolerance, CCTK_PARAMETER__DISTORTEDBHIVP__tolerance); \
  CCTK_DECLARE_INIT (CCTK_INT const, interpolation_order, CCTK_PARAMETER__DISTORTEDBHIVP__interpolation_order); \
  CCTK_DECLARE_INIT (CCTK_INT const, n, CCTK_PARAMETER__DISTORTEDBHIVP__n); \
  CCTK_DECLARE_INIT (CCTK_INT const, neta, CCTK_PARAMETER__DISTORTEDBHIVP__neta); \
  CCTK_DECLARE_INIT (CCTK_INT const, nphi, CCTK_PARAMETER__DISTORTEDBHIVP__nphi); \
  CCTK_DECLARE_INIT (CCTK_INT const, ntheta, CCTK_PARAMETER__DISTORTEDBHIVP__ntheta); \


#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__amp
#  define CCTK_PARAMETER__DISTORTEDBHIVP__amp PRIVATE_DISTORTEDBHIVP_STRUCT.amp
#endif
#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__c
#  define CCTK_PARAMETER__DISTORTEDBHIVP__c PRIVATE_DISTORTEDBHIVP_STRUCT.c
#endif
#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__eta0
#  define CCTK_PARAMETER__DISTORTEDBHIVP__eta0 PRIVATE_DISTORTEDBHIVP_STRUCT.eta0
#endif
#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__etamax
#  define CCTK_PARAMETER__DISTORTEDBHIVP__etamax PRIVATE_DISTORTEDBHIVP_STRUCT.etamax
#endif
#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__sigma
#  define CCTK_PARAMETER__DISTORTEDBHIVP__sigma PRIVATE_DISTORTEDBHIVP_STRUCT.sigma
#endif
#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__tolerance
#  define CCTK_PARAMETER__DISTORTEDBHIVP__tolerance PRIVATE_DISTORTEDBHIVP_STRUCT.tolerance
#endif
#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__interpolation_order
#  define CCTK_PARAMETER__DISTORTEDBHIVP__interpolation_order PRIVATE_DISTORTEDBHIVP_STRUCT.interpolation_order
#endif
#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__n
#  define CCTK_PARAMETER__DISTORTEDBHIVP__n PRIVATE_DISTORTEDBHIVP_STRUCT.n
#endif
#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__neta
#  define CCTK_PARAMETER__DISTORTEDBHIVP__neta PRIVATE_DISTORTEDBHIVP_STRUCT.neta
#endif
#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__nphi
#  define CCTK_PARAMETER__DISTORTEDBHIVP__nphi PRIVATE_DISTORTEDBHIVP_STRUCT.nphi
#endif
#ifndef CCTK_PARAMETER__DISTORTEDBHIVP__ntheta
#  define CCTK_PARAMETER__DISTORTEDBHIVP__ntheta PRIVATE_DISTORTEDBHIVP_STRUCT.ntheta
#endif

