#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL amplitude;
  CCTK_REAL kx;
  CCTK_REAL ky;
  CCTK_REAL kz;
  CCTK_REAL radius;
  CCTK_REAL sigma;
} PRIVATE_IDSCALARWAVECXX_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_IDSCALARWAVECXX_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, amplitude, CCTK_PARAMETER__IDSCALARWAVECXX__amplitude); \
  CCTK_DECLARE_INIT (CCTK_REAL const, kx, CCTK_PARAMETER__IDSCALARWAVECXX__kx); \
  CCTK_DECLARE_INIT (CCTK_REAL const, ky, CCTK_PARAMETER__IDSCALARWAVECXX__ky); \
  CCTK_DECLARE_INIT (CCTK_REAL const, kz, CCTK_PARAMETER__IDSCALARWAVECXX__kz); \
  CCTK_DECLARE_INIT (CCTK_REAL const, radius, CCTK_PARAMETER__IDSCALARWAVECXX__radius); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma, CCTK_PARAMETER__IDSCALARWAVECXX__sigma); \


#ifndef CCTK_PARAMETER__IDSCALARWAVECXX__amplitude
#  define CCTK_PARAMETER__IDSCALARWAVECXX__amplitude PRIVATE_IDSCALARWAVECXX_STRUCT.amplitude
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVECXX__kx
#  define CCTK_PARAMETER__IDSCALARWAVECXX__kx PRIVATE_IDSCALARWAVECXX_STRUCT.kx
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVECXX__ky
#  define CCTK_PARAMETER__IDSCALARWAVECXX__ky PRIVATE_IDSCALARWAVECXX_STRUCT.ky
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVECXX__kz
#  define CCTK_PARAMETER__IDSCALARWAVECXX__kz PRIVATE_IDSCALARWAVECXX_STRUCT.kz
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVECXX__radius
#  define CCTK_PARAMETER__IDSCALARWAVECXX__radius PRIVATE_IDSCALARWAVECXX_STRUCT.radius
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVECXX__sigma
#  define CCTK_PARAMETER__IDSCALARWAVECXX__sigma PRIVATE_IDSCALARWAVECXX_STRUCT.sigma
#endif

