#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL auto_res_ratio[42];
  const char * auto_res_grid[42];
  const char * name[42];
  CCTK_INT auto_res[42];
  CCTK_INT maxnphi;
  CCTK_INT maxntheta;
  CCTK_INT nghostsphi[42];
  CCTK_INT nghoststheta[42];
  CCTK_INT nphi[42];
  CCTK_INT nsurfaces;
  CCTK_INT ntheta[42];
  CCTK_INT symmetric_x[42];
  CCTK_INT symmetric_y[42];
  CCTK_INT symmetric_z[42];
  CCTK_INT verbose;
} RESTRICTED_SPHERICALSURFACE_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_RESTRICTED_SPHERICALSURFACE_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const * const, auto_res_ratio, CCTK_PARAMETER__SPHERICALSURFACE__auto_res_ratio); \
  CCTK_DECLARE_INIT (const char * const * const, auto_res_grid, CCTK_PARAMETER__SPHERICALSURFACE__auto_res_grid); \
  CCTK_DECLARE_INIT (const char * const * const, name, CCTK_PARAMETER__SPHERICALSURFACE__name); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, auto_res, CCTK_PARAMETER__SPHERICALSURFACE__auto_res); \
  CCTK_DECLARE_INIT (CCTK_INT const, maxnphi, CCTK_PARAMETER__SPHERICALSURFACE__maxnphi); \
  CCTK_DECLARE_INIT (CCTK_INT const, maxntheta, CCTK_PARAMETER__SPHERICALSURFACE__maxntheta); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, nghostsphi, CCTK_PARAMETER__SPHERICALSURFACE__nghostsphi); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, nghoststheta, CCTK_PARAMETER__SPHERICALSURFACE__nghoststheta); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, nphi, CCTK_PARAMETER__SPHERICALSURFACE__nphi); \
  CCTK_DECLARE_INIT (CCTK_INT const, nsurfaces, CCTK_PARAMETER__SPHERICALSURFACE__nsurfaces); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, ntheta, CCTK_PARAMETER__SPHERICALSURFACE__ntheta); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, symmetric_x, CCTK_PARAMETER__SPHERICALSURFACE__symmetric_x); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, symmetric_y, CCTK_PARAMETER__SPHERICALSURFACE__symmetric_y); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, symmetric_z, CCTK_PARAMETER__SPHERICALSURFACE__symmetric_z); \
  CCTK_DECLARE_INIT (CCTK_INT const, verbose, CCTK_PARAMETER__SPHERICALSURFACE__verbose); \


#ifndef CCTK_PARAMETER__SPHERICALSURFACE__auto_res_ratio
#  define CCTK_PARAMETER__SPHERICALSURFACE__auto_res_ratio RESTRICTED_SPHERICALSURFACE_STRUCT.auto_res_ratio
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__auto_res_grid
#  define CCTK_PARAMETER__SPHERICALSURFACE__auto_res_grid RESTRICTED_SPHERICALSURFACE_STRUCT.auto_res_grid
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__name
#  define CCTK_PARAMETER__SPHERICALSURFACE__name RESTRICTED_SPHERICALSURFACE_STRUCT.name
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__auto_res
#  define CCTK_PARAMETER__SPHERICALSURFACE__auto_res RESTRICTED_SPHERICALSURFACE_STRUCT.auto_res
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__maxnphi
#  define CCTK_PARAMETER__SPHERICALSURFACE__maxnphi RESTRICTED_SPHERICALSURFACE_STRUCT.maxnphi
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__maxntheta
#  define CCTK_PARAMETER__SPHERICALSURFACE__maxntheta RESTRICTED_SPHERICALSURFACE_STRUCT.maxntheta
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__nghostsphi
#  define CCTK_PARAMETER__SPHERICALSURFACE__nghostsphi RESTRICTED_SPHERICALSURFACE_STRUCT.nghostsphi
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__nghoststheta
#  define CCTK_PARAMETER__SPHERICALSURFACE__nghoststheta RESTRICTED_SPHERICALSURFACE_STRUCT.nghoststheta
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__nphi
#  define CCTK_PARAMETER__SPHERICALSURFACE__nphi RESTRICTED_SPHERICALSURFACE_STRUCT.nphi
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__nsurfaces
#  define CCTK_PARAMETER__SPHERICALSURFACE__nsurfaces RESTRICTED_SPHERICALSURFACE_STRUCT.nsurfaces
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__ntheta
#  define CCTK_PARAMETER__SPHERICALSURFACE__ntheta RESTRICTED_SPHERICALSURFACE_STRUCT.ntheta
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__symmetric_x
#  define CCTK_PARAMETER__SPHERICALSURFACE__symmetric_x RESTRICTED_SPHERICALSURFACE_STRUCT.symmetric_x
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__symmetric_y
#  define CCTK_PARAMETER__SPHERICALSURFACE__symmetric_y RESTRICTED_SPHERICALSURFACE_STRUCT.symmetric_y
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__symmetric_z
#  define CCTK_PARAMETER__SPHERICALSURFACE__symmetric_z RESTRICTED_SPHERICALSURFACE_STRUCT.symmetric_z
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__verbose
#  define CCTK_PARAMETER__SPHERICALSURFACE__verbose RESTRICTED_SPHERICALSURFACE_STRUCT.verbose
#endif

