#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL origin_x[42];
  CCTK_REAL origin_y[42];
  CCTK_REAL origin_z[42];
  CCTK_REAL radius[42];
  CCTK_REAL radius_x[42];
  CCTK_REAL radius_y[42];
  CCTK_REAL radius_z[42];
  CCTK_INT set_elliptic[42];
  CCTK_INT set_spherical[42];
} PRIVATE_SPHERICALSURFACE_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_SPHERICALSURFACE_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const * const, origin_x, CCTK_PARAMETER__SPHERICALSURFACE__origin_x); \
  CCTK_DECLARE_INIT (CCTK_REAL const * const, origin_y, CCTK_PARAMETER__SPHERICALSURFACE__origin_y); \
  CCTK_DECLARE_INIT (CCTK_REAL const * const, origin_z, CCTK_PARAMETER__SPHERICALSURFACE__origin_z); \
  CCTK_DECLARE_INIT (CCTK_REAL const * const, radius, CCTK_PARAMETER__SPHERICALSURFACE__radius); \
  CCTK_DECLARE_INIT (CCTK_REAL const * const, radius_x, CCTK_PARAMETER__SPHERICALSURFACE__radius_x); \
  CCTK_DECLARE_INIT (CCTK_REAL const * const, radius_y, CCTK_PARAMETER__SPHERICALSURFACE__radius_y); \
  CCTK_DECLARE_INIT (CCTK_REAL const * const, radius_z, CCTK_PARAMETER__SPHERICALSURFACE__radius_z); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, set_elliptic, CCTK_PARAMETER__SPHERICALSURFACE__set_elliptic); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, set_spherical, CCTK_PARAMETER__SPHERICALSURFACE__set_spherical); \


#ifndef CCTK_PARAMETER__SPHERICALSURFACE__origin_x
#  define CCTK_PARAMETER__SPHERICALSURFACE__origin_x PRIVATE_SPHERICALSURFACE_STRUCT.origin_x
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__origin_y
#  define CCTK_PARAMETER__SPHERICALSURFACE__origin_y PRIVATE_SPHERICALSURFACE_STRUCT.origin_y
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__origin_z
#  define CCTK_PARAMETER__SPHERICALSURFACE__origin_z PRIVATE_SPHERICALSURFACE_STRUCT.origin_z
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__radius
#  define CCTK_PARAMETER__SPHERICALSURFACE__radius PRIVATE_SPHERICALSURFACE_STRUCT.radius
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__radius_x
#  define CCTK_PARAMETER__SPHERICALSURFACE__radius_x PRIVATE_SPHERICALSURFACE_STRUCT.radius_x
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__radius_y
#  define CCTK_PARAMETER__SPHERICALSURFACE__radius_y PRIVATE_SPHERICALSURFACE_STRUCT.radius_y
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__radius_z
#  define CCTK_PARAMETER__SPHERICALSURFACE__radius_z PRIVATE_SPHERICALSURFACE_STRUCT.radius_z
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__set_elliptic
#  define CCTK_PARAMETER__SPHERICALSURFACE__set_elliptic PRIVATE_SPHERICALSURFACE_STRUCT.set_elliptic
#endif
#ifndef CCTK_PARAMETER__SPHERICALSURFACE__set_spherical
#  define CCTK_PARAMETER__SPHERICALSURFACE__set_spherical PRIVATE_SPHERICALSURFACE_STRUCT.set_spherical
#endif

