#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL constant;
  CCTK_REAL timefact;
} PRIVATE_CARPETINTEGRATETEST_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_CARPETINTEGRATETEST_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, constant, CCTK_PARAMETER__CARPETINTEGRATETEST__constant); \
  CCTK_DECLARE_INIT (CCTK_REAL const, timefact, CCTK_PARAMETER__CARPETINTEGRATETEST__timefact); \


#ifndef CCTK_PARAMETER__CARPETINTEGRATETEST__constant
#  define CCTK_PARAMETER__CARPETINTEGRATETEST__constant PRIVATE_CARPETINTEGRATETEST_STRUCT.constant
#endif
#ifndef CCTK_PARAMETER__CARPETINTEGRATETEST__timefact
#  define CCTK_PARAMETER__CARPETINTEGRATETEST__timefact PRIVATE_CARPETINTEGRATETEST_STRUCT.timefact
#endif

