#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL ID_AMP;
  CCTK_REAL Jcoeff_r0;
  CCTK_REAL Jcoeff_r0i;
  CCTK_REAL Jcoeff_r0r;
  CCTK_REAL Jcoeff_r1;
  CCTK_REAL Jcoeff_r1i;
  CCTK_REAL Jcoeff_r1r;
  CCTK_REAL Jcoeff_r3;
  CCTK_REAL Jcoeff_r3i;
  CCTK_REAL Jcoeff_r3r;
  CCTK_REAL N_dissip_one_outside_eq;
  CCTK_REAL N_dissip_zero_outside_eq;
  CCTK_REAL dissip_J;
  CCTK_REAL dissip_Jx;
  CCTK_REAL dissip_Q;
  CCTK_REAL dissip_W;
  CCTK_REAL dissip_fudge_maxx;
  CCTK_REAL null_dissip;
  CCTK_REAL psmax;
  CCTK_REAL psmin;
  CCTK_REAL qsmax;
  CCTK_REAL qsmin;
  CCTK_REAL wrot;
  CCTK_REAL xmax;
  CCTK_REAL xmin;
  const char * dissip_mask_type;
  CCTK_INT ID_POWER;
  CCTK_INT ID_l;
  CCTK_INT ID_m;
  CCTK_INT dissip_fudge;
  CCTK_INT use_rsYlm;
} PRIVATE_NULLEVOLVE_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_NULLEVOLVE_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, ID_AMP, CCTK_PARAMETER__NULLEVOLVE__ID_AMP); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Jcoeff_r0, CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r0); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Jcoeff_r0i, CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r0i); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Jcoeff_r0r, CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r0r); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Jcoeff_r1, CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r1); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Jcoeff_r1i, CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r1i); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Jcoeff_r1r, CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r1r); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Jcoeff_r3, CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r3); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Jcoeff_r3i, CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r3i); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Jcoeff_r3r, CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r3r); \
  CCTK_DECLARE_INIT (CCTK_REAL const, N_dissip_one_outside_eq, CCTK_PARAMETER__NULLEVOLVE__N_dissip_one_outside_eq); \
  CCTK_DECLARE_INIT (CCTK_REAL const, N_dissip_zero_outside_eq, CCTK_PARAMETER__NULLEVOLVE__N_dissip_zero_outside_eq); \
  CCTK_DECLARE_INIT (CCTK_REAL const, dissip_J, CCTK_PARAMETER__NULLEVOLVE__dissip_J); \
  CCTK_DECLARE_INIT (CCTK_REAL const, dissip_Jx, CCTK_PARAMETER__NULLEVOLVE__dissip_Jx); \
  CCTK_DECLARE_INIT (CCTK_REAL const, dissip_Q, CCTK_PARAMETER__NULLEVOLVE__dissip_Q); \
  CCTK_DECLARE_INIT (CCTK_REAL const, dissip_W, CCTK_PARAMETER__NULLEVOLVE__dissip_W); \
  CCTK_DECLARE_INIT (CCTK_REAL const, dissip_fudge_maxx, CCTK_PARAMETER__NULLEVOLVE__dissip_fudge_maxx); \
  CCTK_DECLARE_INIT (CCTK_REAL const, null_dissip, CCTK_PARAMETER__NULLEVOLVE__null_dissip); \
  CCTK_DECLARE_INIT (CCTK_REAL const, psmax, CCTK_PARAMETER__NULLEVOLVE__psmax); \
  CCTK_DECLARE_INIT (CCTK_REAL const, psmin, CCTK_PARAMETER__NULLEVOLVE__psmin); \
  CCTK_DECLARE_INIT (CCTK_REAL const, qsmax, CCTK_PARAMETER__NULLEVOLVE__qsmax); \
  CCTK_DECLARE_INIT (CCTK_REAL const, qsmin, CCTK_PARAMETER__NULLEVOLVE__qsmin); \
  CCTK_DECLARE_INIT (CCTK_REAL const, wrot, CCTK_PARAMETER__NULLEVOLVE__wrot); \
  CCTK_DECLARE_INIT (CCTK_REAL const, xmax, CCTK_PARAMETER__NULLEVOLVE__xmax); \
  CCTK_DECLARE_INIT (CCTK_REAL const, xmin, CCTK_PARAMETER__NULLEVOLVE__xmin); \
  CCTK_DECLARE_INIT (const char * const, dissip_mask_type, CCTK_PARAMETER__NULLEVOLVE__dissip_mask_type); \
  CCTK_DECLARE_INIT (CCTK_INT const, ID_POWER, CCTK_PARAMETER__NULLEVOLVE__ID_POWER); \
  CCTK_DECLARE_INIT (CCTK_INT const, ID_l, CCTK_PARAMETER__NULLEVOLVE__ID_l); \
  CCTK_DECLARE_INIT (CCTK_INT const, ID_m, CCTK_PARAMETER__NULLEVOLVE__ID_m); \
  CCTK_DECLARE_INIT (CCTK_INT const, dissip_fudge, CCTK_PARAMETER__NULLEVOLVE__dissip_fudge); \
  CCTK_DECLARE_INIT (CCTK_INT const, use_rsYlm, CCTK_PARAMETER__NULLEVOLVE__use_rsYlm); \


#ifndef CCTK_PARAMETER__NULLEVOLVE__ID_AMP
#  define CCTK_PARAMETER__NULLEVOLVE__ID_AMP PRIVATE_NULLEVOLVE_STRUCT.ID_AMP
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r0
#  define CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r0 PRIVATE_NULLEVOLVE_STRUCT.Jcoeff_r0
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r0i
#  define CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r0i PRIVATE_NULLEVOLVE_STRUCT.Jcoeff_r0i
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r0r
#  define CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r0r PRIVATE_NULLEVOLVE_STRUCT.Jcoeff_r0r
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r1
#  define CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r1 PRIVATE_NULLEVOLVE_STRUCT.Jcoeff_r1
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r1i
#  define CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r1i PRIVATE_NULLEVOLVE_STRUCT.Jcoeff_r1i
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r1r
#  define CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r1r PRIVATE_NULLEVOLVE_STRUCT.Jcoeff_r1r
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r3
#  define CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r3 PRIVATE_NULLEVOLVE_STRUCT.Jcoeff_r3
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r3i
#  define CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r3i PRIVATE_NULLEVOLVE_STRUCT.Jcoeff_r3i
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r3r
#  define CCTK_PARAMETER__NULLEVOLVE__Jcoeff_r3r PRIVATE_NULLEVOLVE_STRUCT.Jcoeff_r3r
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__N_dissip_one_outside_eq
#  define CCTK_PARAMETER__NULLEVOLVE__N_dissip_one_outside_eq PRIVATE_NULLEVOLVE_STRUCT.N_dissip_one_outside_eq
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__N_dissip_zero_outside_eq
#  define CCTK_PARAMETER__NULLEVOLVE__N_dissip_zero_outside_eq PRIVATE_NULLEVOLVE_STRUCT.N_dissip_zero_outside_eq
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__dissip_J
#  define CCTK_PARAMETER__NULLEVOLVE__dissip_J PRIVATE_NULLEVOLVE_STRUCT.dissip_J
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__dissip_Jx
#  define CCTK_PARAMETER__NULLEVOLVE__dissip_Jx PRIVATE_NULLEVOLVE_STRUCT.dissip_Jx
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__dissip_Q
#  define CCTK_PARAMETER__NULLEVOLVE__dissip_Q PRIVATE_NULLEVOLVE_STRUCT.dissip_Q
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__dissip_W
#  define CCTK_PARAMETER__NULLEVOLVE__dissip_W PRIVATE_NULLEVOLVE_STRUCT.dissip_W
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__dissip_fudge_maxx
#  define CCTK_PARAMETER__NULLEVOLVE__dissip_fudge_maxx PRIVATE_NULLEVOLVE_STRUCT.dissip_fudge_maxx
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__null_dissip
#  define CCTK_PARAMETER__NULLEVOLVE__null_dissip PRIVATE_NULLEVOLVE_STRUCT.null_dissip
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__psmax
#  define CCTK_PARAMETER__NULLEVOLVE__psmax PRIVATE_NULLEVOLVE_STRUCT.psmax
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__psmin
#  define CCTK_PARAMETER__NULLEVOLVE__psmin PRIVATE_NULLEVOLVE_STRUCT.psmin
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__qsmax
#  define CCTK_PARAMETER__NULLEVOLVE__qsmax PRIVATE_NULLEVOLVE_STRUCT.qsmax
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__qsmin
#  define CCTK_PARAMETER__NULLEVOLVE__qsmin PRIVATE_NULLEVOLVE_STRUCT.qsmin
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__wrot
#  define CCTK_PARAMETER__NULLEVOLVE__wrot PRIVATE_NULLEVOLVE_STRUCT.wrot
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__xmax
#  define CCTK_PARAMETER__NULLEVOLVE__xmax PRIVATE_NULLEVOLVE_STRUCT.xmax
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__xmin
#  define CCTK_PARAMETER__NULLEVOLVE__xmin PRIVATE_NULLEVOLVE_STRUCT.xmin
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__dissip_mask_type
#  define CCTK_PARAMETER__NULLEVOLVE__dissip_mask_type PRIVATE_NULLEVOLVE_STRUCT.dissip_mask_type
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__ID_POWER
#  define CCTK_PARAMETER__NULLEVOLVE__ID_POWER PRIVATE_NULLEVOLVE_STRUCT.ID_POWER
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__ID_l
#  define CCTK_PARAMETER__NULLEVOLVE__ID_l PRIVATE_NULLEVOLVE_STRUCT.ID_l
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__ID_m
#  define CCTK_PARAMETER__NULLEVOLVE__ID_m PRIVATE_NULLEVOLVE_STRUCT.ID_m
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__dissip_fudge
#  define CCTK_PARAMETER__NULLEVOLVE__dissip_fudge PRIVATE_NULLEVOLVE_STRUCT.dissip_fudge
#endif
#ifndef CCTK_PARAMETER__NULLEVOLVE__use_rsYlm
#  define CCTK_PARAMETER__NULLEVOLVE__use_rsYlm PRIVATE_NULLEVOLVE_STRUCT.use_rsYlm
#endif

