#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL charge;
  CCTK_REAL radius;
  const char * solver;
  CCTK_INT output_tmp;
  CCTK_INT sor_maxit;
} PRIVATE_IDSCALARWAVEELLIPTIC_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_IDSCALARWAVEELLIPTIC_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, charge, CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__charge); \
  CCTK_DECLARE_INIT (CCTK_REAL const, radius, CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__radius); \
  CCTK_DECLARE_INIT (const char * const, solver, CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__solver); \
  CCTK_DECLARE_INIT (CCTK_INT const, output_tmp, CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__output_tmp); \
  CCTK_DECLARE_INIT (CCTK_INT const, sor_maxit, CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__sor_maxit); \


#ifndef CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__charge
#  define CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__charge PRIVATE_IDSCALARWAVEELLIPTIC_STRUCT.charge
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__radius
#  define CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__radius PRIVATE_IDSCALARWAVEELLIPTIC_STRUCT.radius
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__solver
#  define CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__solver PRIVATE_IDSCALARWAVEELLIPTIC_STRUCT.solver
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__output_tmp
#  define CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__output_tmp PRIVATE_IDSCALARWAVEELLIPTIC_STRUCT.output_tmp
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__sor_maxit
#  define CCTK_PARAMETER__IDSCALARWAVEELLIPTIC__sor_maxit PRIVATE_IDSCALARWAVEELLIPTIC_STRUCT.sor_maxit
#endif

