#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL amp;
  CCTK_REAL amp_me;
  CCTK_REAL byJ;
  CCTK_REAL eta0;
  CCTK_REAL eta0_me;
  CCTK_REAL etamax;
  CCTK_REAL sigma;
  CCTK_REAL sigma_me;
  CCTK_REAL xi;
  CCTK_INT brandt_seidel;
  CCTK_INT interpolation_order;
  CCTK_INT n;
  CCTK_INT n_me;
  CCTK_INT neta;
  CCTK_INT ntheta;
  CCTK_INT sergio;
  CCTK_INT verbose;
} PRIVATE_IDAXIODDBRILLBH_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_IDAXIODDBRILLBH_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, amp, CCTK_PARAMETER__IDAXIODDBRILLBH__amp); \
  CCTK_DECLARE_INIT (CCTK_REAL const, amp_me, CCTK_PARAMETER__IDAXIODDBRILLBH__amp_me); \
  CCTK_DECLARE_INIT (CCTK_REAL const, byJ, CCTK_PARAMETER__IDAXIODDBRILLBH__byJ); \
  CCTK_DECLARE_INIT (CCTK_REAL const, eta0, CCTK_PARAMETER__IDAXIODDBRILLBH__eta0); \
  CCTK_DECLARE_INIT (CCTK_REAL const, eta0_me, CCTK_PARAMETER__IDAXIODDBRILLBH__eta0_me); \
  CCTK_DECLARE_INIT (CCTK_REAL const, etamax, CCTK_PARAMETER__IDAXIODDBRILLBH__etamax); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma, CCTK_PARAMETER__IDAXIODDBRILLBH__sigma); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma_me, CCTK_PARAMETER__IDAXIODDBRILLBH__sigma_me); \
  CCTK_DECLARE_INIT (CCTK_REAL const, xi, CCTK_PARAMETER__IDAXIODDBRILLBH__xi); \
  CCTK_DECLARE_INIT (CCTK_INT const, brandt_seidel, CCTK_PARAMETER__IDAXIODDBRILLBH__brandt_seidel); \
  CCTK_DECLARE_INIT (CCTK_INT const, interpolation_order, CCTK_PARAMETER__IDAXIODDBRILLBH__interpolation_order); \
  CCTK_DECLARE_INIT (CCTK_INT const, n, CCTK_PARAMETER__IDAXIODDBRILLBH__n); \
  CCTK_DECLARE_INIT (CCTK_INT const, n_me, CCTK_PARAMETER__IDAXIODDBRILLBH__n_me); \
  CCTK_DECLARE_INIT (CCTK_INT const, neta, CCTK_PARAMETER__IDAXIODDBRILLBH__neta); \
  CCTK_DECLARE_INIT (CCTK_INT const, ntheta, CCTK_PARAMETER__IDAXIODDBRILLBH__ntheta); \
  CCTK_DECLARE_INIT (CCTK_INT const, sergio, CCTK_PARAMETER__IDAXIODDBRILLBH__sergio); \
  CCTK_DECLARE_INIT (CCTK_INT const, verbose, CCTK_PARAMETER__IDAXIODDBRILLBH__verbose); \


#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__amp
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__amp PRIVATE_IDAXIODDBRILLBH_STRUCT.amp
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__amp_me
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__amp_me PRIVATE_IDAXIODDBRILLBH_STRUCT.amp_me
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__byJ
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__byJ PRIVATE_IDAXIODDBRILLBH_STRUCT.byJ
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__eta0
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__eta0 PRIVATE_IDAXIODDBRILLBH_STRUCT.eta0
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__eta0_me
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__eta0_me PRIVATE_IDAXIODDBRILLBH_STRUCT.eta0_me
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__etamax
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__etamax PRIVATE_IDAXIODDBRILLBH_STRUCT.etamax
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__sigma
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__sigma PRIVATE_IDAXIODDBRILLBH_STRUCT.sigma
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__sigma_me
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__sigma_me PRIVATE_IDAXIODDBRILLBH_STRUCT.sigma_me
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__xi
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__xi PRIVATE_IDAXIODDBRILLBH_STRUCT.xi
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__brandt_seidel
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__brandt_seidel PRIVATE_IDAXIODDBRILLBH_STRUCT.brandt_seidel
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__interpolation_order
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__interpolation_order PRIVATE_IDAXIODDBRILLBH_STRUCT.interpolation_order
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__n
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__n PRIVATE_IDAXIODDBRILLBH_STRUCT.n
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__n_me
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__n_me PRIVATE_IDAXIODDBRILLBH_STRUCT.n_me
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__neta
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__neta PRIVATE_IDAXIODDBRILLBH_STRUCT.neta
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__ntheta
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__ntheta PRIVATE_IDAXIODDBRILLBH_STRUCT.ntheta
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__sergio
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__sergio PRIVATE_IDAXIODDBRILLBH_STRUCT.sergio
#endif
#ifndef CCTK_PARAMETER__IDAXIODDBRILLBH__verbose
#  define CCTK_PARAMETER__IDAXIODDBRILLBH__verbose PRIVATE_IDAXIODDBRILLBH_STRUCT.verbose
#endif

