#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL GAMMA_SPEED_LIMIT;
  CCTK_REAL K_poly;
  CCTK_REAL Psi6threshold;
  CCTK_REAL Sym_Bz;
  CCTK_REAL gamma_th;
  CCTK_REAL rho_b_atm;
  CCTK_REAL rho_b_max;
  CCTK_REAL tau_atm;
  const char * EM_BC;
  const char * Matter_BC;
  const char * Symmetry;
  CCTK_INT IllinoisGRMHD_MaxNumEvolvedVars;
  CCTK_INT conserv_to_prims_debug;
  CCTK_INT neos;
  CCTK_INT update_Tmunu;
} RESTRICTED_ILLINOISGRMHD_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_RESTRICTED_ILLINOISGRMHD_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, GAMMA_SPEED_LIMIT, CCTK_PARAMETER__ILLINOISGRMHD__GAMMA_SPEED_LIMIT); \
  CCTK_DECLARE_INIT (CCTK_REAL const, K_poly, CCTK_PARAMETER__ILLINOISGRMHD__K_poly); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Psi6threshold, CCTK_PARAMETER__ILLINOISGRMHD__Psi6threshold); \
  CCTK_DECLARE_INIT (CCTK_REAL const, Sym_Bz, CCTK_PARAMETER__ILLINOISGRMHD__Sym_Bz); \
  CCTK_DECLARE_INIT (CCTK_REAL const, gamma_th, CCTK_PARAMETER__ILLINOISGRMHD__gamma_th); \
  CCTK_DECLARE_INIT (CCTK_REAL const, rho_b_atm, CCTK_PARAMETER__ILLINOISGRMHD__rho_b_atm); \
  CCTK_DECLARE_INIT (CCTK_REAL const, rho_b_max, CCTK_PARAMETER__ILLINOISGRMHD__rho_b_max); \
  CCTK_DECLARE_INIT (CCTK_REAL const, tau_atm, CCTK_PARAMETER__ILLINOISGRMHD__tau_atm); \
  CCTK_DECLARE_INIT (const char * const, EM_BC, CCTK_PARAMETER__ILLINOISGRMHD__EM_BC); \
  CCTK_DECLARE_INIT (const char * const, Matter_BC, CCTK_PARAMETER__ILLINOISGRMHD__Matter_BC); \
  CCTK_DECLARE_INIT (const char * const, Symmetry, CCTK_PARAMETER__ILLINOISGRMHD__Symmetry); \
  CCTK_DECLARE_INIT (CCTK_INT const, IllinoisGRMHD_MaxNumEvolvedVars, CCTK_PARAMETER__ILLINOISGRMHD__IllinoisGRMHD_MaxNumEvolvedVars); \
  CCTK_DECLARE_INIT (CCTK_INT const, conserv_to_prims_debug, CCTK_PARAMETER__ILLINOISGRMHD__conserv_to_prims_debug); \
  CCTK_DECLARE_INIT (CCTK_INT const, neos, CCTK_PARAMETER__ILLINOISGRMHD__neos); \
  CCTK_DECLARE_INIT (CCTK_INT const, update_Tmunu, CCTK_PARAMETER__ILLINOISGRMHD__update_Tmunu); \


#ifndef CCTK_PARAMETER__ILLINOISGRMHD__GAMMA_SPEED_LIMIT
#  define CCTK_PARAMETER__ILLINOISGRMHD__GAMMA_SPEED_LIMIT RESTRICTED_ILLINOISGRMHD_STRUCT.GAMMA_SPEED_LIMIT
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__K_poly
#  define CCTK_PARAMETER__ILLINOISGRMHD__K_poly RESTRICTED_ILLINOISGRMHD_STRUCT.K_poly
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__Psi6threshold
#  define CCTK_PARAMETER__ILLINOISGRMHD__Psi6threshold RESTRICTED_ILLINOISGRMHD_STRUCT.Psi6threshold
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__Sym_Bz
#  define CCTK_PARAMETER__ILLINOISGRMHD__Sym_Bz RESTRICTED_ILLINOISGRMHD_STRUCT.Sym_Bz
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__gamma_th
#  define CCTK_PARAMETER__ILLINOISGRMHD__gamma_th RESTRICTED_ILLINOISGRMHD_STRUCT.gamma_th
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__rho_b_atm
#  define CCTK_PARAMETER__ILLINOISGRMHD__rho_b_atm RESTRICTED_ILLINOISGRMHD_STRUCT.rho_b_atm
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__rho_b_max
#  define CCTK_PARAMETER__ILLINOISGRMHD__rho_b_max RESTRICTED_ILLINOISGRMHD_STRUCT.rho_b_max
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__tau_atm
#  define CCTK_PARAMETER__ILLINOISGRMHD__tau_atm RESTRICTED_ILLINOISGRMHD_STRUCT.tau_atm
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__EM_BC
#  define CCTK_PARAMETER__ILLINOISGRMHD__EM_BC RESTRICTED_ILLINOISGRMHD_STRUCT.EM_BC
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__Matter_BC
#  define CCTK_PARAMETER__ILLINOISGRMHD__Matter_BC RESTRICTED_ILLINOISGRMHD_STRUCT.Matter_BC
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__Symmetry
#  define CCTK_PARAMETER__ILLINOISGRMHD__Symmetry RESTRICTED_ILLINOISGRMHD_STRUCT.Symmetry
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__IllinoisGRMHD_MaxNumEvolvedVars
#  define CCTK_PARAMETER__ILLINOISGRMHD__IllinoisGRMHD_MaxNumEvolvedVars RESTRICTED_ILLINOISGRMHD_STRUCT.IllinoisGRMHD_MaxNumEvolvedVars
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__conserv_to_prims_debug
#  define CCTK_PARAMETER__ILLINOISGRMHD__conserv_to_prims_debug RESTRICTED_ILLINOISGRMHD_STRUCT.conserv_to_prims_debug
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__neos
#  define CCTK_PARAMETER__ILLINOISGRMHD__neos RESTRICTED_ILLINOISGRMHD_STRUCT.neos
#endif
#ifndef CCTK_PARAMETER__ILLINOISGRMHD__update_Tmunu
#  define CCTK_PARAMETER__ILLINOISGRMHD__update_Tmunu RESTRICTED_ILLINOISGRMHD_STRUCT.update_Tmunu
#endif

