#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL amplitude;
  CCTK_REAL kx;
  CCTK_REAL ky;
  CCTK_REAL kz;
  CCTK_REAL radius;
  CCTK_REAL sigma;
} PRIVATE_IDSCALARWAVEC_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_IDSCALARWAVEC_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, amplitude, CCTK_PARAMETER__IDSCALARWAVEC__amplitude); \
  CCTK_DECLARE_INIT (CCTK_REAL const, kx, CCTK_PARAMETER__IDSCALARWAVEC__kx); \
  CCTK_DECLARE_INIT (CCTK_REAL const, ky, CCTK_PARAMETER__IDSCALARWAVEC__ky); \
  CCTK_DECLARE_INIT (CCTK_REAL const, kz, CCTK_PARAMETER__IDSCALARWAVEC__kz); \
  CCTK_DECLARE_INIT (CCTK_REAL const, radius, CCTK_PARAMETER__IDSCALARWAVEC__radius); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma, CCTK_PARAMETER__IDSCALARWAVEC__sigma); \


#ifndef CCTK_PARAMETER__IDSCALARWAVEC__amplitude
#  define CCTK_PARAMETER__IDSCALARWAVEC__amplitude PRIVATE_IDSCALARWAVEC_STRUCT.amplitude
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVEC__kx
#  define CCTK_PARAMETER__IDSCALARWAVEC__kx PRIVATE_IDSCALARWAVEC_STRUCT.kx
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVEC__ky
#  define CCTK_PARAMETER__IDSCALARWAVEC__ky PRIVATE_IDSCALARWAVEC_STRUCT.ky
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVEC__kz
#  define CCTK_PARAMETER__IDSCALARWAVEC__kz PRIVATE_IDSCALARWAVEC_STRUCT.kz
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVEC__radius
#  define CCTK_PARAMETER__IDSCALARWAVEC__radius PRIVATE_IDSCALARWAVEC_STRUCT.radius
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVEC__sigma
#  define CCTK_PARAMETER__IDSCALARWAVEC__sigma PRIVATE_IDSCALARWAVEC_STRUCT.sigma
#endif

