#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL A_b;
  CCTK_REAL P_cut;
  CCTK_REAL n_s;
  CCTK_INT enable_IllinoisGRMHD_staggered_A_fields;
} RESTRICTED_SEED_MAGNETIC_FIELDS_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_RESTRICTED_SEED_MAGNETIC_FIELDS_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, A_b, CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__A_b); \
  CCTK_DECLARE_INIT (CCTK_REAL const, P_cut, CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__P_cut); \
  CCTK_DECLARE_INIT (CCTK_REAL const, n_s, CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__n_s); \
  CCTK_DECLARE_INIT (CCTK_INT const, enable_IllinoisGRMHD_staggered_A_fields, CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__enable_IllinoisGRMHD_staggered_A_fields); \


#ifndef CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__A_b
#  define CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__A_b RESTRICTED_SEED_MAGNETIC_FIELDS_STRUCT.A_b
#endif
#ifndef CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__P_cut
#  define CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__P_cut RESTRICTED_SEED_MAGNETIC_FIELDS_STRUCT.P_cut
#endif
#ifndef CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__n_s
#  define CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__n_s RESTRICTED_SEED_MAGNETIC_FIELDS_STRUCT.n_s
#endif
#ifndef CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__enable_IllinoisGRMHD_staggered_A_fields
#  define CCTK_PARAMETER__SEED_MAGNETIC_FIELDS__enable_IllinoisGRMHD_staggered_A_fields RESTRICTED_SEED_MAGNETIC_FIELDS_STRUCT.enable_IllinoisGRMHD_staggered_A_fields
#endif

