#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL amplitude;
  CCTK_REAL radius;
  CCTK_REAL sigma;
} PRIVATE_CARPETREGRIDTEST_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_CARPETREGRIDTEST_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, amplitude, CCTK_PARAMETER__CARPETREGRIDTEST__amplitude); \
  CCTK_DECLARE_INIT (CCTK_REAL const, radius, CCTK_PARAMETER__CARPETREGRIDTEST__radius); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma, CCTK_PARAMETER__CARPETREGRIDTEST__sigma); \


#ifndef CCTK_PARAMETER__CARPETREGRIDTEST__amplitude
#  define CCTK_PARAMETER__CARPETREGRIDTEST__amplitude PRIVATE_CARPETREGRIDTEST_STRUCT.amplitude
#endif
#ifndef CCTK_PARAMETER__CARPETREGRIDTEST__radius
#  define CCTK_PARAMETER__CARPETREGRIDTEST__radius PRIVATE_CARPETREGRIDTEST_STRUCT.radius
#endif
#ifndef CCTK_PARAMETER__CARPETREGRIDTEST__sigma
#  define CCTK_PARAMETER__CARPETREGRIDTEST__sigma PRIVATE_CARPETREGRIDTEST_STRUCT.sigma
#endif

