#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL interp_xmax;
  CCTK_REAL interp_xmin;
  CCTK_REAL interp_ymax;
  CCTK_REAL interp_ymin;
  CCTK_REAL interp_zmax;
  CCTK_REAL interp_zmin;
  const char * interpolator;
  const char * interpolator_options;
  const char * prolongation;
  CCTK_INT interp_nx;
  CCTK_INT interp_ny;
  CCTK_INT interp_nz;
  CCTK_INT power_t;
  CCTK_INT power_x;
  CCTK_INT power_y;
  CCTK_INT power_z;
} PRIVATE_CARPETPROLONGATETEST_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_CARPETPROLONGATETEST_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, interp_xmax, CCTK_PARAMETER__CARPETPROLONGATETEST__interp_xmax); \
  CCTK_DECLARE_INIT (CCTK_REAL const, interp_xmin, CCTK_PARAMETER__CARPETPROLONGATETEST__interp_xmin); \
  CCTK_DECLARE_INIT (CCTK_REAL const, interp_ymax, CCTK_PARAMETER__CARPETPROLONGATETEST__interp_ymax); \
  CCTK_DECLARE_INIT (CCTK_REAL const, interp_ymin, CCTK_PARAMETER__CARPETPROLONGATETEST__interp_ymin); \
  CCTK_DECLARE_INIT (CCTK_REAL const, interp_zmax, CCTK_PARAMETER__CARPETPROLONGATETEST__interp_zmax); \
  CCTK_DECLARE_INIT (CCTK_REAL const, interp_zmin, CCTK_PARAMETER__CARPETPROLONGATETEST__interp_zmin); \
  CCTK_DECLARE_INIT (const char * const, interpolator, CCTK_PARAMETER__CARPETPROLONGATETEST__interpolator); \
  CCTK_DECLARE_INIT (const char * const, interpolator_options, CCTK_PARAMETER__CARPETPROLONGATETEST__interpolator_options); \
  CCTK_DECLARE_INIT (const char * const, prolongation, CCTK_PARAMETER__CARPETPROLONGATETEST__prolongation); \
  CCTK_DECLARE_INIT (CCTK_INT const, interp_nx, CCTK_PARAMETER__CARPETPROLONGATETEST__interp_nx); \
  CCTK_DECLARE_INIT (CCTK_INT const, interp_ny, CCTK_PARAMETER__CARPETPROLONGATETEST__interp_ny); \
  CCTK_DECLARE_INIT (CCTK_INT const, interp_nz, CCTK_PARAMETER__CARPETPROLONGATETEST__interp_nz); \
  CCTK_DECLARE_INIT (CCTK_INT const, power_t, CCTK_PARAMETER__CARPETPROLONGATETEST__power_t); \
  CCTK_DECLARE_INIT (CCTK_INT const, power_x, CCTK_PARAMETER__CARPETPROLONGATETEST__power_x); \
  CCTK_DECLARE_INIT (CCTK_INT const, power_y, CCTK_PARAMETER__CARPETPROLONGATETEST__power_y); \
  CCTK_DECLARE_INIT (CCTK_INT const, power_z, CCTK_PARAMETER__CARPETPROLONGATETEST__power_z); \


#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interp_xmax
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interp_xmax PRIVATE_CARPETPROLONGATETEST_STRUCT.interp_xmax
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interp_xmin
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interp_xmin PRIVATE_CARPETPROLONGATETEST_STRUCT.interp_xmin
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interp_ymax
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interp_ymax PRIVATE_CARPETPROLONGATETEST_STRUCT.interp_ymax
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interp_ymin
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interp_ymin PRIVATE_CARPETPROLONGATETEST_STRUCT.interp_ymin
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interp_zmax
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interp_zmax PRIVATE_CARPETPROLONGATETEST_STRUCT.interp_zmax
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interp_zmin
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interp_zmin PRIVATE_CARPETPROLONGATETEST_STRUCT.interp_zmin
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interpolator
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interpolator PRIVATE_CARPETPROLONGATETEST_STRUCT.interpolator
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interpolator_options
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interpolator_options PRIVATE_CARPETPROLONGATETEST_STRUCT.interpolator_options
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__prolongation
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__prolongation PRIVATE_CARPETPROLONGATETEST_STRUCT.prolongation
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interp_nx
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interp_nx PRIVATE_CARPETPROLONGATETEST_STRUCT.interp_nx
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interp_ny
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interp_ny PRIVATE_CARPETPROLONGATETEST_STRUCT.interp_ny
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__interp_nz
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__interp_nz PRIVATE_CARPETPROLONGATETEST_STRUCT.interp_nz
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__power_t
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__power_t PRIVATE_CARPETPROLONGATETEST_STRUCT.power_t
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__power_x
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__power_x PRIVATE_CARPETPROLONGATETEST_STRUCT.power_x
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__power_y
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__power_y PRIVATE_CARPETPROLONGATETEST_STRUCT.power_y
#endif
#ifndef CCTK_PARAMETER__CARPETPROLONGATETEST__power_z
#  define CCTK_PARAMETER__CARPETPROLONGATETEST__power_z PRIVATE_CARPETPROLONGATETEST_STRUCT.power_z
#endif

