#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL amp;
  CCTK_REAL byJ;
  CCTK_REAL eta0;
  CCTK_REAL etamax;
  CCTK_REAL mm;
  CCTK_REAL sigma;
  CCTK_INT interpolation_order;
  CCTK_INT kerr_shift;
  CCTK_INT kerr_slice;
  CCTK_INT neta;
  CCTK_INT nphi;
  CCTK_INT ntheta;
  CCTK_INT verbose;
} PRIVATE_ROTATINGDBHIVP_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_ROTATINGDBHIVP_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, amp, CCTK_PARAMETER__ROTATINGDBHIVP__amp); \
  CCTK_DECLARE_INIT (CCTK_REAL const, byJ, CCTK_PARAMETER__ROTATINGDBHIVP__byJ); \
  CCTK_DECLARE_INIT (CCTK_REAL const, eta0, CCTK_PARAMETER__ROTATINGDBHIVP__eta0); \
  CCTK_DECLARE_INIT (CCTK_REAL const, etamax, CCTK_PARAMETER__ROTATINGDBHIVP__etamax); \
  CCTK_DECLARE_INIT (CCTK_REAL const, mm, CCTK_PARAMETER__ROTATINGDBHIVP__mm); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma, CCTK_PARAMETER__ROTATINGDBHIVP__sigma); \
  CCTK_DECLARE_INIT (CCTK_INT const, interpolation_order, CCTK_PARAMETER__ROTATINGDBHIVP__interpolation_order); \
  CCTK_DECLARE_INIT (CCTK_INT const, kerr_shift, CCTK_PARAMETER__ROTATINGDBHIVP__kerr_shift); \
  CCTK_DECLARE_INIT (CCTK_INT const, kerr_slice, CCTK_PARAMETER__ROTATINGDBHIVP__kerr_slice); \
  CCTK_DECLARE_INIT (CCTK_INT const, neta, CCTK_PARAMETER__ROTATINGDBHIVP__neta); \
  CCTK_DECLARE_INIT (CCTK_INT const, nphi, CCTK_PARAMETER__ROTATINGDBHIVP__nphi); \
  CCTK_DECLARE_INIT (CCTK_INT const, ntheta, CCTK_PARAMETER__ROTATINGDBHIVP__ntheta); \
  CCTK_DECLARE_INIT (CCTK_INT const, verbose, CCTK_PARAMETER__ROTATINGDBHIVP__verbose); \


#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__amp
#  define CCTK_PARAMETER__ROTATINGDBHIVP__amp PRIVATE_ROTATINGDBHIVP_STRUCT.amp
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__byJ
#  define CCTK_PARAMETER__ROTATINGDBHIVP__byJ PRIVATE_ROTATINGDBHIVP_STRUCT.byJ
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__eta0
#  define CCTK_PARAMETER__ROTATINGDBHIVP__eta0 PRIVATE_ROTATINGDBHIVP_STRUCT.eta0
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__etamax
#  define CCTK_PARAMETER__ROTATINGDBHIVP__etamax PRIVATE_ROTATINGDBHIVP_STRUCT.etamax
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__mm
#  define CCTK_PARAMETER__ROTATINGDBHIVP__mm PRIVATE_ROTATINGDBHIVP_STRUCT.mm
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__sigma
#  define CCTK_PARAMETER__ROTATINGDBHIVP__sigma PRIVATE_ROTATINGDBHIVP_STRUCT.sigma
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__interpolation_order
#  define CCTK_PARAMETER__ROTATINGDBHIVP__interpolation_order PRIVATE_ROTATINGDBHIVP_STRUCT.interpolation_order
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__kerr_shift
#  define CCTK_PARAMETER__ROTATINGDBHIVP__kerr_shift PRIVATE_ROTATINGDBHIVP_STRUCT.kerr_shift
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__kerr_slice
#  define CCTK_PARAMETER__ROTATINGDBHIVP__kerr_slice PRIVATE_ROTATINGDBHIVP_STRUCT.kerr_slice
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__neta
#  define CCTK_PARAMETER__ROTATINGDBHIVP__neta PRIVATE_ROTATINGDBHIVP_STRUCT.neta
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__nphi
#  define CCTK_PARAMETER__ROTATINGDBHIVP__nphi PRIVATE_ROTATINGDBHIVP_STRUCT.nphi
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__ntheta
#  define CCTK_PARAMETER__ROTATINGDBHIVP__ntheta PRIVATE_ROTATINGDBHIVP_STRUCT.ntheta
#endif
#ifndef CCTK_PARAMETER__ROTATINGDBHIVP__verbose
#  define CCTK_PARAMETER__ROTATINGDBHIVP__verbose PRIVATE_ROTATINGDBHIVP_STRUCT.verbose
#endif

