#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL adjust_timestep__maximum_time_step;
  CCTK_REAL adjust_timestep__rate_of_change;
  CCTK_REAL dt_tolerance;
  CCTK_REAL initial_relaxation_time;
  CCTK_REAL initial_time;
  const char * file;
  const char * file_gxx[3];
  const char * file_gxy[3];
  const char * file_gxz[3];
  const char * file_gyy[3];
  const char * file_gyz[3];
  const char * file_gzz[3];
  const char * file_lapse[3];
  const char * file_shiftx[3];
  const char * file_shifty[3];
  const char * file_shiftz[3];
  const char * format;
  const char * path;
  const char * sYlm_convention;
  CCTK_INT adjust_timestep;
  CCTK_INT adjust_timestep__target_steps_per_time_level;
  CCTK_INT cached_timesteps;
  CCTK_INT column_data;
  CCTK_INT column_gxx[3];
  CCTK_INT column_gxy[3];
  CCTK_INT column_gxz[3];
  CCTK_INT column_gyy[3];
  CCTK_INT column_gyz[3];
  CCTK_INT column_gzz[3];
  CCTK_INT column_iteration;
  CCTK_INT column_lapse[3];
  CCTK_INT column_lmax;
  CCTK_INT column_n_variables;
  CCTK_INT column_radius;
  CCTK_INT column_shiftx[3];
  CCTK_INT column_shifty[3];
  CCTK_INT column_shiftz[3];
  CCTK_INT column_time;
  CCTK_INT disable_auto_time_offset;
  CCTK_INT lmaxInFile;
  CCTK_INT sphere_number;
  CCTK_INT time_derivative_in_file;
  CCTK_INT time_fd_order;
  CCTK_INT time_interpolate;
  CCTK_INT verbose;
} PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, adjust_timestep__maximum_time_step, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep__maximum_time_step); \
  CCTK_DECLARE_INIT (CCTK_REAL const, adjust_timestep__rate_of_change, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep__rate_of_change); \
  CCTK_DECLARE_INIT (CCTK_REAL const, dt_tolerance, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__dt_tolerance); \
  CCTK_DECLARE_INIT (CCTK_REAL const, initial_relaxation_time, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__initial_relaxation_time); \
  CCTK_DECLARE_INIT (CCTK_REAL const, initial_time, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__initial_time); \
  CCTK_DECLARE_INIT (const char * const, file, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file); \
  CCTK_DECLARE_INIT (const char * const * const, file_gxx, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gxx); \
  CCTK_DECLARE_INIT (const char * const * const, file_gxy, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gxy); \
  CCTK_DECLARE_INIT (const char * const * const, file_gxz, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gxz); \
  CCTK_DECLARE_INIT (const char * const * const, file_gyy, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gyy); \
  CCTK_DECLARE_INIT (const char * const * const, file_gyz, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gyz); \
  CCTK_DECLARE_INIT (const char * const * const, file_gzz, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gzz); \
  CCTK_DECLARE_INIT (const char * const * const, file_lapse, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_lapse); \
  CCTK_DECLARE_INIT (const char * const * const, file_shiftx, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_shiftx); \
  CCTK_DECLARE_INIT (const char * const * const, file_shifty, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_shifty); \
  CCTK_DECLARE_INIT (const char * const * const, file_shiftz, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_shiftz); \
  CCTK_DECLARE_INIT (const char * const, format, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__format); \
  CCTK_DECLARE_INIT (const char * const, path, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__path); \
  CCTK_DECLARE_INIT (const char * const, sYlm_convention, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__sYlm_convention); \
  CCTK_DECLARE_INIT (CCTK_INT const, adjust_timestep, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep); \
  CCTK_DECLARE_INIT (CCTK_INT const, adjust_timestep__target_steps_per_time_level, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep__target_steps_per_time_level); \
  CCTK_DECLARE_INIT (CCTK_INT const, cached_timesteps, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__cached_timesteps); \
  CCTK_DECLARE_INIT (CCTK_INT const, column_data, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_data); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, column_gxx, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gxx); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, column_gxy, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gxy); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, column_gxz, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gxz); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, column_gyy, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gyy); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, column_gyz, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gyz); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, column_gzz, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gzz); \
  CCTK_DECLARE_INIT (CCTK_INT const, column_iteration, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_iteration); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, column_lapse, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_lapse); \
  CCTK_DECLARE_INIT (CCTK_INT const, column_lmax, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_lmax); \
  CCTK_DECLARE_INIT (CCTK_INT const, column_n_variables, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_n_variables); \
  CCTK_DECLARE_INIT (CCTK_INT const, column_radius, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_radius); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, column_shiftx, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_shiftx); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, column_shifty, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_shifty); \
  CCTK_DECLARE_INIT (CCTK_INT const * const, column_shiftz, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_shiftz); \
  CCTK_DECLARE_INIT (CCTK_INT const, column_time, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_time); \
  CCTK_DECLARE_INIT (CCTK_INT const, disable_auto_time_offset, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__disable_auto_time_offset); \
  CCTK_DECLARE_INIT (CCTK_INT const, lmaxInFile, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__lmaxInFile); \
  CCTK_DECLARE_INIT (CCTK_INT const, sphere_number, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__sphere_number); \
  CCTK_DECLARE_INIT (CCTK_INT const, time_derivative_in_file, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__time_derivative_in_file); \
  CCTK_DECLARE_INIT (CCTK_INT const, time_fd_order, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__time_fd_order); \
  CCTK_DECLARE_INIT (CCTK_INT const, time_interpolate, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__time_interpolate); \
  CCTK_DECLARE_INIT (CCTK_INT const, verbose, CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__verbose); \


#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep__maximum_time_step
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep__maximum_time_step PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.adjust_timestep__maximum_time_step
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep__rate_of_change
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep__rate_of_change PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.adjust_timestep__rate_of_change
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__dt_tolerance
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__dt_tolerance PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.dt_tolerance
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__initial_relaxation_time
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__initial_relaxation_time PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.initial_relaxation_time
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__initial_time
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__initial_time PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.initial_time
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gxx
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gxx PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file_gxx
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gxy
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gxy PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file_gxy
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gxz
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gxz PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file_gxz
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gyy
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gyy PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file_gyy
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gyz
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gyz PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file_gyz
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gzz
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_gzz PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file_gzz
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_lapse
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_lapse PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file_lapse
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_shiftx
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_shiftx PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file_shiftx
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_shifty
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_shifty PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file_shifty
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_shiftz
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__file_shiftz PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.file_shiftz
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__format
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__format PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.format
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__path
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__path PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.path
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__sYlm_convention
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__sYlm_convention PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.sYlm_convention
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.adjust_timestep
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep__target_steps_per_time_level
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__adjust_timestep__target_steps_per_time_level PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.adjust_timestep__target_steps_per_time_level
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__cached_timesteps
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__cached_timesteps PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.cached_timesteps
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_data
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_data PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_data
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gxx
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gxx PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_gxx
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gxy
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gxy PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_gxy
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gxz
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gxz PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_gxz
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gyy
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gyy PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_gyy
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gyz
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gyz PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_gyz
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gzz
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_gzz PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_gzz
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_iteration
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_iteration PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_iteration
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_lapse
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_lapse PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_lapse
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_lmax
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_lmax PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_lmax
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_n_variables
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_n_variables PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_n_variables
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_radius
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_radius PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_radius
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_shiftx
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_shiftx PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_shiftx
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_shifty
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_shifty PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_shifty
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_shiftz
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_shiftz PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_shiftz
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_time
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__column_time PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.column_time
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__disable_auto_time_offset
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__disable_auto_time_offset PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.disable_auto_time_offset
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__lmaxInFile
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__lmaxInFile PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.lmaxInFile
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__sphere_number
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__sphere_number PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.sphere_number
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__time_derivative_in_file
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__time_derivative_in_file PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.time_derivative_in_file
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__time_fd_order
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__time_fd_order PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.time_fd_order
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__time_interpolate
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__time_interpolate PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.time_interpolate
#endif
#ifndef CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__verbose
#  define CCTK_PARAMETER__SPHERICALHARMONICRECONGEN__verbose PRIVATE_SPHERICALHARMONICRECONGEN_STRUCT.verbose
#endif

