#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL a_Kerr;
  CCTK_REAL bl_M_1;
  CCTK_REAL bl_M_2;
  CCTK_REAL bl_M_3;
  CCTK_REAL bl_M_4;
  CCTK_REAL bl_x0_1;
  CCTK_REAL bl_x0_2;
  CCTK_REAL bl_x0_3;
  CCTK_REAL bl_x0_4;
  CCTK_REAL bl_y0_1;
  CCTK_REAL bl_y0_2;
  CCTK_REAL bl_y0_3;
  CCTK_REAL bl_y0_4;
  CCTK_REAL bl_z0_1;
  CCTK_REAL bl_z0_2;
  CCTK_REAL bl_z0_3;
  CCTK_REAL bl_z0_4;
  CCTK_REAL epsilon;
  CCTK_REAL mass;
  CCTK_REAL mu;
  CCTK_INT bl_nbh;
  CCTK_INT misner_nbh;
  CCTK_INT nmax;
} PRIVATE_IDANALYTICBH_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_IDANALYTICBH_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, a_Kerr, CCTK_PARAMETER__IDANALYTICBH__a_Kerr); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_M_1, CCTK_PARAMETER__IDANALYTICBH__bl_M_1); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_M_2, CCTK_PARAMETER__IDANALYTICBH__bl_M_2); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_M_3, CCTK_PARAMETER__IDANALYTICBH__bl_M_3); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_M_4, CCTK_PARAMETER__IDANALYTICBH__bl_M_4); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_x0_1, CCTK_PARAMETER__IDANALYTICBH__bl_x0_1); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_x0_2, CCTK_PARAMETER__IDANALYTICBH__bl_x0_2); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_x0_3, CCTK_PARAMETER__IDANALYTICBH__bl_x0_3); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_x0_4, CCTK_PARAMETER__IDANALYTICBH__bl_x0_4); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_y0_1, CCTK_PARAMETER__IDANALYTICBH__bl_y0_1); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_y0_2, CCTK_PARAMETER__IDANALYTICBH__bl_y0_2); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_y0_3, CCTK_PARAMETER__IDANALYTICBH__bl_y0_3); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_y0_4, CCTK_PARAMETER__IDANALYTICBH__bl_y0_4); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_z0_1, CCTK_PARAMETER__IDANALYTICBH__bl_z0_1); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_z0_2, CCTK_PARAMETER__IDANALYTICBH__bl_z0_2); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_z0_3, CCTK_PARAMETER__IDANALYTICBH__bl_z0_3); \
  CCTK_DECLARE_INIT (CCTK_REAL const, bl_z0_4, CCTK_PARAMETER__IDANALYTICBH__bl_z0_4); \
  CCTK_DECLARE_INIT (CCTK_REAL const, epsilon, CCTK_PARAMETER__IDANALYTICBH__epsilon); \
  CCTK_DECLARE_INIT (CCTK_REAL const, mass, CCTK_PARAMETER__IDANALYTICBH__mass); \
  CCTK_DECLARE_INIT (CCTK_REAL const, mu, CCTK_PARAMETER__IDANALYTICBH__mu); \
  CCTK_DECLARE_INIT (CCTK_INT const, bl_nbh, CCTK_PARAMETER__IDANALYTICBH__bl_nbh); \
  CCTK_DECLARE_INIT (CCTK_INT const, misner_nbh, CCTK_PARAMETER__IDANALYTICBH__misner_nbh); \
  CCTK_DECLARE_INIT (CCTK_INT const, nmax, CCTK_PARAMETER__IDANALYTICBH__nmax); \


#ifndef CCTK_PARAMETER__IDANALYTICBH__a_Kerr
#  define CCTK_PARAMETER__IDANALYTICBH__a_Kerr PRIVATE_IDANALYTICBH_STRUCT.a_Kerr
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_M_1
#  define CCTK_PARAMETER__IDANALYTICBH__bl_M_1 PRIVATE_IDANALYTICBH_STRUCT.bl_M_1
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_M_2
#  define CCTK_PARAMETER__IDANALYTICBH__bl_M_2 PRIVATE_IDANALYTICBH_STRUCT.bl_M_2
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_M_3
#  define CCTK_PARAMETER__IDANALYTICBH__bl_M_3 PRIVATE_IDANALYTICBH_STRUCT.bl_M_3
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_M_4
#  define CCTK_PARAMETER__IDANALYTICBH__bl_M_4 PRIVATE_IDANALYTICBH_STRUCT.bl_M_4
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_x0_1
#  define CCTK_PARAMETER__IDANALYTICBH__bl_x0_1 PRIVATE_IDANALYTICBH_STRUCT.bl_x0_1
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_x0_2
#  define CCTK_PARAMETER__IDANALYTICBH__bl_x0_2 PRIVATE_IDANALYTICBH_STRUCT.bl_x0_2
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_x0_3
#  define CCTK_PARAMETER__IDANALYTICBH__bl_x0_3 PRIVATE_IDANALYTICBH_STRUCT.bl_x0_3
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_x0_4
#  define CCTK_PARAMETER__IDANALYTICBH__bl_x0_4 PRIVATE_IDANALYTICBH_STRUCT.bl_x0_4
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_y0_1
#  define CCTK_PARAMETER__IDANALYTICBH__bl_y0_1 PRIVATE_IDANALYTICBH_STRUCT.bl_y0_1
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_y0_2
#  define CCTK_PARAMETER__IDANALYTICBH__bl_y0_2 PRIVATE_IDANALYTICBH_STRUCT.bl_y0_2
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_y0_3
#  define CCTK_PARAMETER__IDANALYTICBH__bl_y0_3 PRIVATE_IDANALYTICBH_STRUCT.bl_y0_3
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_y0_4
#  define CCTK_PARAMETER__IDANALYTICBH__bl_y0_4 PRIVATE_IDANALYTICBH_STRUCT.bl_y0_4
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_z0_1
#  define CCTK_PARAMETER__IDANALYTICBH__bl_z0_1 PRIVATE_IDANALYTICBH_STRUCT.bl_z0_1
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_z0_2
#  define CCTK_PARAMETER__IDANALYTICBH__bl_z0_2 PRIVATE_IDANALYTICBH_STRUCT.bl_z0_2
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_z0_3
#  define CCTK_PARAMETER__IDANALYTICBH__bl_z0_3 PRIVATE_IDANALYTICBH_STRUCT.bl_z0_3
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_z0_4
#  define CCTK_PARAMETER__IDANALYTICBH__bl_z0_4 PRIVATE_IDANALYTICBH_STRUCT.bl_z0_4
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__epsilon
#  define CCTK_PARAMETER__IDANALYTICBH__epsilon PRIVATE_IDANALYTICBH_STRUCT.epsilon
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__mass
#  define CCTK_PARAMETER__IDANALYTICBH__mass PRIVATE_IDANALYTICBH_STRUCT.mass
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__mu
#  define CCTK_PARAMETER__IDANALYTICBH__mu PRIVATE_IDANALYTICBH_STRUCT.mu
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__bl_nbh
#  define CCTK_PARAMETER__IDANALYTICBH__bl_nbh PRIVATE_IDANALYTICBH_STRUCT.bl_nbh
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__misner_nbh
#  define CCTK_PARAMETER__IDANALYTICBH__misner_nbh PRIVATE_IDANALYTICBH_STRUCT.misner_nbh
#endif
#ifndef CCTK_PARAMETER__IDANALYTICBH__nmax
#  define CCTK_PARAMETER__IDANALYTICBH__nmax PRIVATE_IDANALYTICBH_STRUCT.nmax
#endif

