#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL amplitude;
  CCTK_REAL kx;
  CCTK_REAL ky;
  CCTK_REAL kz;
  CCTK_REAL radius;
  CCTK_REAL sigma;
} PRIVATE_IDSCALARWAVE_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_IDSCALARWAVE_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, amplitude, CCTK_PARAMETER__IDSCALARWAVE__amplitude); \
  CCTK_DECLARE_INIT (CCTK_REAL const, kx, CCTK_PARAMETER__IDSCALARWAVE__kx); \
  CCTK_DECLARE_INIT (CCTK_REAL const, ky, CCTK_PARAMETER__IDSCALARWAVE__ky); \
  CCTK_DECLARE_INIT (CCTK_REAL const, kz, CCTK_PARAMETER__IDSCALARWAVE__kz); \
  CCTK_DECLARE_INIT (CCTK_REAL const, radius, CCTK_PARAMETER__IDSCALARWAVE__radius); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma, CCTK_PARAMETER__IDSCALARWAVE__sigma); \


#ifndef CCTK_PARAMETER__IDSCALARWAVE__amplitude
#  define CCTK_PARAMETER__IDSCALARWAVE__amplitude PRIVATE_IDSCALARWAVE_STRUCT.amplitude
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVE__kx
#  define CCTK_PARAMETER__IDSCALARWAVE__kx PRIVATE_IDSCALARWAVE_STRUCT.kx
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVE__ky
#  define CCTK_PARAMETER__IDSCALARWAVE__ky PRIVATE_IDSCALARWAVE_STRUCT.ky
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVE__kz
#  define CCTK_PARAMETER__IDSCALARWAVE__kz PRIVATE_IDSCALARWAVE_STRUCT.kz
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVE__radius
#  define CCTK_PARAMETER__IDSCALARWAVE__radius PRIVATE_IDSCALARWAVE_STRUCT.radius
#endif
#ifndef CCTK_PARAMETER__IDSCALARWAVE__sigma
#  define CCTK_PARAMETER__IDSCALARWAVE__sigma PRIVATE_IDSCALARWAVE_STRUCT.sigma
#endif

