#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL amplitude;
  CCTK_REAL radius;
  CCTK_REAL sigma;
} PRIVATE_IDCONSTRAINTVIOLATE_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_IDCONSTRAINTVIOLATE_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, amplitude, CCTK_PARAMETER__IDCONSTRAINTVIOLATE__amplitude); \
  CCTK_DECLARE_INIT (CCTK_REAL const, radius, CCTK_PARAMETER__IDCONSTRAINTVIOLATE__radius); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma, CCTK_PARAMETER__IDCONSTRAINTVIOLATE__sigma); \


#ifndef CCTK_PARAMETER__IDCONSTRAINTVIOLATE__amplitude
#  define CCTK_PARAMETER__IDCONSTRAINTVIOLATE__amplitude PRIVATE_IDCONSTRAINTVIOLATE_STRUCT.amplitude
#endif
#ifndef CCTK_PARAMETER__IDCONSTRAINTVIOLATE__radius
#  define CCTK_PARAMETER__IDCONSTRAINTVIOLATE__radius PRIVATE_IDCONSTRAINTVIOLATE_STRUCT.radius
#endif
#ifndef CCTK_PARAMETER__IDCONSTRAINTVIOLATE__sigma
#  define CCTK_PARAMETER__IDCONSTRAINTVIOLATE__sigma PRIVATE_IDCONSTRAINTVIOLATE_STRUCT.sigma
#endif

