#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL amplitude;
  CCTK_REAL centrex;
  CCTK_REAL centrey;
  CCTK_REAL centrez;
  CCTK_REAL kx;
  CCTK_REAL ky;
  CCTK_REAL kz;
  CCTK_REAL offsett;
  CCTK_REAL offsetx;
  CCTK_REAL offsety;
  CCTK_REAL offsetz;
  CCTK_REAL radius;
  CCTK_REAL sigma;
  CCTK_REAL slopet;
  CCTK_REAL slopex;
  CCTK_REAL slopey;
  CCTK_REAL slopez;
} PRIVATE_IDWAVEMOL_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_PRIVATE_IDWAVEMOL_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, amplitude, CCTK_PARAMETER__IDWAVEMOL__amplitude); \
  CCTK_DECLARE_INIT (CCTK_REAL const, centrex, CCTK_PARAMETER__IDWAVEMOL__centrex); \
  CCTK_DECLARE_INIT (CCTK_REAL const, centrey, CCTK_PARAMETER__IDWAVEMOL__centrey); \
  CCTK_DECLARE_INIT (CCTK_REAL const, centrez, CCTK_PARAMETER__IDWAVEMOL__centrez); \
  CCTK_DECLARE_INIT (CCTK_REAL const, kx, CCTK_PARAMETER__IDWAVEMOL__kx); \
  CCTK_DECLARE_INIT (CCTK_REAL const, ky, CCTK_PARAMETER__IDWAVEMOL__ky); \
  CCTK_DECLARE_INIT (CCTK_REAL const, kz, CCTK_PARAMETER__IDWAVEMOL__kz); \
  CCTK_DECLARE_INIT (CCTK_REAL const, offsett, CCTK_PARAMETER__IDWAVEMOL__offsett); \
  CCTK_DECLARE_INIT (CCTK_REAL const, offsetx, CCTK_PARAMETER__IDWAVEMOL__offsetx); \
  CCTK_DECLARE_INIT (CCTK_REAL const, offsety, CCTK_PARAMETER__IDWAVEMOL__offsety); \
  CCTK_DECLARE_INIT (CCTK_REAL const, offsetz, CCTK_PARAMETER__IDWAVEMOL__offsetz); \
  CCTK_DECLARE_INIT (CCTK_REAL const, radius, CCTK_PARAMETER__IDWAVEMOL__radius); \
  CCTK_DECLARE_INIT (CCTK_REAL const, sigma, CCTK_PARAMETER__IDWAVEMOL__sigma); \
  CCTK_DECLARE_INIT (CCTK_REAL const, slopet, CCTK_PARAMETER__IDWAVEMOL__slopet); \
  CCTK_DECLARE_INIT (CCTK_REAL const, slopex, CCTK_PARAMETER__IDWAVEMOL__slopex); \
  CCTK_DECLARE_INIT (CCTK_REAL const, slopey, CCTK_PARAMETER__IDWAVEMOL__slopey); \
  CCTK_DECLARE_INIT (CCTK_REAL const, slopez, CCTK_PARAMETER__IDWAVEMOL__slopez); \


#ifndef CCTK_PARAMETER__IDWAVEMOL__amplitude
#  define CCTK_PARAMETER__IDWAVEMOL__amplitude PRIVATE_IDWAVEMOL_STRUCT.amplitude
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__centrex
#  define CCTK_PARAMETER__IDWAVEMOL__centrex PRIVATE_IDWAVEMOL_STRUCT.centrex
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__centrey
#  define CCTK_PARAMETER__IDWAVEMOL__centrey PRIVATE_IDWAVEMOL_STRUCT.centrey
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__centrez
#  define CCTK_PARAMETER__IDWAVEMOL__centrez PRIVATE_IDWAVEMOL_STRUCT.centrez
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__kx
#  define CCTK_PARAMETER__IDWAVEMOL__kx PRIVATE_IDWAVEMOL_STRUCT.kx
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__ky
#  define CCTK_PARAMETER__IDWAVEMOL__ky PRIVATE_IDWAVEMOL_STRUCT.ky
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__kz
#  define CCTK_PARAMETER__IDWAVEMOL__kz PRIVATE_IDWAVEMOL_STRUCT.kz
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__offsett
#  define CCTK_PARAMETER__IDWAVEMOL__offsett PRIVATE_IDWAVEMOL_STRUCT.offsett
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__offsetx
#  define CCTK_PARAMETER__IDWAVEMOL__offsetx PRIVATE_IDWAVEMOL_STRUCT.offsetx
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__offsety
#  define CCTK_PARAMETER__IDWAVEMOL__offsety PRIVATE_IDWAVEMOL_STRUCT.offsety
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__offsetz
#  define CCTK_PARAMETER__IDWAVEMOL__offsetz PRIVATE_IDWAVEMOL_STRUCT.offsetz
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__radius
#  define CCTK_PARAMETER__IDWAVEMOL__radius PRIVATE_IDWAVEMOL_STRUCT.radius
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__sigma
#  define CCTK_PARAMETER__IDWAVEMOL__sigma PRIVATE_IDWAVEMOL_STRUCT.sigma
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__slopet
#  define CCTK_PARAMETER__IDWAVEMOL__slopet PRIVATE_IDWAVEMOL_STRUCT.slopet
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__slopex
#  define CCTK_PARAMETER__IDWAVEMOL__slopex PRIVATE_IDWAVEMOL_STRUCT.slopex
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__slopey
#  define CCTK_PARAMETER__IDWAVEMOL__slopey PRIVATE_IDWAVEMOL_STRUCT.slopey
#endif
#ifndef CCTK_PARAMETER__IDWAVEMOL__slopez
#  define CCTK_PARAMETER__IDWAVEMOL__slopez PRIVATE_IDWAVEMOL_STRUCT.slopez
#endif

