#ifdef __cplusplus
extern "C"
{
#endif

extern struct
{
  CCTK_REAL MinimumDistanceTo2Bp1;
  CCTK_REAL cr;
  CCTK_REAL mass;
  CCTK_INT l_max;
} RESTRICTED_NULLSHREXTRACT_STRUCT;

#ifdef __cplusplus
}
#endif

#define DECLARE_RESTRICTED_NULLSHREXTRACT_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_REAL const, MinimumDistanceTo2Bp1, CCTK_PARAMETER__NULLSHREXTRACT__MinimumDistanceTo2Bp1); \
  CCTK_DECLARE_INIT (CCTK_REAL const, cr, CCTK_PARAMETER__NULLSHREXTRACT__cr); \
  CCTK_DECLARE_INIT (CCTK_REAL const, mass, CCTK_PARAMETER__NULLSHREXTRACT__mass); \
  CCTK_DECLARE_INIT (CCTK_INT const, l_max, CCTK_PARAMETER__NULLSHREXTRACT__l_max); \


#ifndef CCTK_PARAMETER__NULLSHREXTRACT__MinimumDistanceTo2Bp1
#  define CCTK_PARAMETER__NULLSHREXTRACT__MinimumDistanceTo2Bp1 RESTRICTED_NULLSHREXTRACT_STRUCT.MinimumDistanceTo2Bp1
#endif
#ifndef CCTK_PARAMETER__NULLSHREXTRACT__cr
#  define CCTK_PARAMETER__NULLSHREXTRACT__cr RESTRICTED_NULLSHREXTRACT_STRUCT.cr
#endif
#ifndef CCTK_PARAMETER__NULLSHREXTRACT__mass
#  define CCTK_PARAMETER__NULLSHREXTRACT__mass RESTRICTED_NULLSHREXTRACT_STRUCT.mass
#endif
#ifndef CCTK_PARAMETER__NULLSHREXTRACT__l_max
#  define CCTK_PARAMETER__NULLSHREXTRACT__l_max RESTRICTED_NULLSHREXTRACT_STRUCT.l_max
#endif

