/*@@
   @header  TestLoop_Prototypes.h
   @author  Automatically generated by CreateFunctionBindings.pl
   @desc
            Prototypes for overloaded functions used by this thorn
   @enddesc
  @@*/


#ifndef _TESTLOOP_PROTOTYPES_H_
#define _TESTLOOP_PROTOTYPES_H_  1

#ifdef CCODE
#ifdef __cplusplus
extern "C" {
#endif

CCTK_INT GetBoundarySizesAndTypes(const CCTK_POINTER_TO_CONST cctkGH ,
 const CCTK_INT size ,
 CCTK_INT* bndsize ,
 CCTK_INT* is_ghostbnd ,
 CCTK_INT* is_symbnd ,
 CCTK_INT* is_physbnd);

#ifdef __cplusplus
}
#endif
#endif /* CCODE */

#ifdef FCODE
#ifdef F90CODE
#define DECLARE_TESTLOOP_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \
  interface &&\
     CCTK_INT function GetBoundarySizesAndTypes (cctkGH, size, bndsize, is_ghostbnd, is_symbnd, is_physbnd) &&\
       implicit none &&\
       CCTK_POINTER_TO_CONST cctkGH &&\
       CCTK_INT size &&\
       CCTK_INT bndsize(*) &&\
       CCTK_INT is_ghostbnd(*) &&\
       CCTK_INT is_symbnd(*) &&\
       CCTK_INT is_physbnd(*) &&\
     end function GetBoundarySizesAndTypes &&\
  end interface &&\

#else /* ! F90CODE */

#define DECLARE_TESTLOOP_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \
  external GetBoundarySizesAndTypes &&\
  CCTK_INT GetBoundarySizesAndTypes &&\

#endif /* ! F90CODE */
#endif /* FCODE */

#endif

