#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,out0D_dt,)&&\
CCTK_DECLARE(CCTK_REAL,out0D_point_x,)&&\
CCTK_DECLARE(CCTK_REAL,out0D_point_y,)&&\
CCTK_DECLARE(CCTK_REAL,out0D_point_z,)&&\
CCTK_DECLARE(CCTK_REAL,out1D_dt,)&&\
CCTK_DECLARE(CCTK_REAL,out1D_xline_y,)&&\
CCTK_DECLARE(CCTK_REAL,out1D_xline_z,)&&\
CCTK_DECLARE(CCTK_REAL,out1D_yline_x,)&&\
CCTK_DECLARE(CCTK_REAL,out1D_yline_z,)&&\
CCTK_DECLARE(CCTK_REAL,out1D_zline_x,)&&\
CCTK_DECLARE(CCTK_REAL,out1D_zline_y,)&&\
CCTK_DECLARE(CCTK_REAL,out2D_dt,)&&\
CCTK_DECLARE(CCTK_REAL,out2D_xyplane_z,)&&\
CCTK_DECLARE(CCTK_REAL,out2D_xzplane_y,)&&\
CCTK_DECLARE(CCTK_REAL,out2D_yzplane_x,)&&\
CCTK_DECLARE(CCTK_REAL,out3D_dt,)&&\
CCTK_DECLARE(CCTK_STRING,out0D_criterion,)&&\
CCTK_DECLARE(CCTK_STRING,out0D_dir,)&&\
CCTK_DECLARE(CCTK_STRING,out0D_vars,)&&\
CCTK_DECLARE(CCTK_STRING,out1D_criterion,)&&\
CCTK_DECLARE(CCTK_STRING,out1D_dir,)&&\
CCTK_DECLARE(CCTK_STRING,out1D_vars,)&&\
CCTK_DECLARE(CCTK_STRING,out2D_criterion,)&&\
CCTK_DECLARE(CCTK_STRING,out2D_dir,)&&\
CCTK_DECLARE(CCTK_STRING,out2D_vars,)&&\
CCTK_DECLARE(CCTK_STRING,out3D_criterion,)&&\
CCTK_DECLARE(CCTK_STRING,out3D_dir,)&&\
CCTK_DECLARE(CCTK_STRING,out3D_vars,)&&\
CCTK_DECLARE(CCTK_INT,compact_format,)&&\
CCTK_DECLARE(CCTK_INT,one_file_per_group,)&&\
CCTK_DECLARE(CCTK_INT,out0D_every,)&&\
CCTK_DECLARE(CCTK_INT,out0D_point_xi,)&&\
CCTK_DECLARE(CCTK_INT,out0D_point_yi,)&&\
CCTK_DECLARE(CCTK_INT,out0D_point_zi,)&&\
CCTK_DECLARE(CCTK_INT,out1D_d,)&&\
CCTK_DECLARE(CCTK_INT,out1D_every,)&&\
CCTK_DECLARE(CCTK_INT,out1D_x,)&&\
CCTK_DECLARE(CCTK_INT,out1D_xline_yi,)&&\
CCTK_DECLARE(CCTK_INT,out1D_xline_zi,)&&\
CCTK_DECLARE(CCTK_INT,out1D_y,)&&\
CCTK_DECLARE(CCTK_INT,out1D_yline_xi,)&&\
CCTK_DECLARE(CCTK_INT,out1D_yline_zi,)&&\
CCTK_DECLARE(CCTK_INT,out1D_z,)&&\
CCTK_DECLARE(CCTK_INT,out1D_zline_xi,)&&\
CCTK_DECLARE(CCTK_INT,out1D_zline_yi,)&&\
CCTK_DECLARE(CCTK_INT,out2D_every,)&&\
CCTK_DECLARE(CCTK_INT,out2D_xy,)&&\
CCTK_DECLARE(CCTK_INT,out2D_xyplane_zi,)&&\
CCTK_DECLARE(CCTK_INT,out2D_xz,)&&\
CCTK_DECLARE(CCTK_INT,out2D_xzplane_yi,)&&\
CCTK_DECLARE(CCTK_INT,out2D_yz,)&&\
CCTK_DECLARE(CCTK_INT,out2D_yzplane_xi,)&&\
CCTK_DECLARE(CCTK_INT,out3D_every,)&&\
CCTK_DECLARE(CCTK_INT,out3D_ghosts,)&&\
CCTK_DECLARE(CCTK_INT,out3D_outer_ghosts,)&&\
CCTK_DECLARE(CCTK_INT,out_precision,)&&\
CCTK_DECLARE(CCTK_INT,output_all_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,output_boundary_points,)&&\
CCTK_DECLARE(CCTK_INT,output_ghost_points,)&&\
CCTK_DECLARE(CCTK_INT,output_symmetry_points,)&&\
CCTK_DECLARE(CCTK_INT,separate_components,)&&\
CCTK_DECLARE(CCTK_INT,separate_grids,)&&\
CCTK_DECLARE(CCTK_INT,use_grid_coordinates,)&&\
COMMON /CarpetIOASCIIpriv/out0D_dt, out0D_point_x, out0D_point_y, out0D_point_z, out1D_dt, out1D_xline_y, out1D_xline_z, out1D_yline_x, out1D_yline_z, out1D_zline_x, out1D_zline_y, out2D_dt, out2D_xyplane_z, out2D_xzplane_y, out2D_yzplane_x, out3D_dt, out0D_criterion, out0D_dir, out0D_vars, out1D_criterion, out1D_dir, out1D_vars, out2D_criterion, out2D_dir, out2D_vars, out3D_criterion, out3D_dir, out3D_vars, compact_format, one_file_per_group, out0D_every, out0D_point_xi, out0D_point_yi, out0D_point_zi, out1D_d, out1D_every, out1D_x, out1D_xline_yi, out1D_xline_zi, out1D_y, out1D_yline_xi, out1D_yline_zi, out1D_z, out1D_zline_xi, out1D_zline_yi, out2D_every, out2D_xy, out2D_xyplane_zi, out2D_xz, out2D_xzplane_yi, out2D_yz, out2D_yzplane_xi, out3D_every, out3D_ghosts, out3D_outer_ghosts, out_precision, output_all_timelevels, output_boundary_points, output_ghost_points, output_symmetry_points, separate_components, separate_grids, use_grid_coordinates&&\
CCTK_DECLARE(CCTK_REAL,CCTKH5,)&&\
CCTK_DECLARE(CCTK_REAL,out_dt,)&&\
CCTK_DECLARE(CCTK_REAL,out_xline_y,)&&\
CCTK_DECLARE(CCTK_REAL,out_xline_z,)&&\
CCTK_DECLARE(CCTK_REAL,out_xyplane_z,)&&\
CCTK_DECLARE(CCTK_REAL,out_xzplane_y,)&&\
CCTK_DECLARE(CCTK_REAL,out_yline_x,)&&\
CCTK_DECLARE(CCTK_REAL,out_yline_z,)&&\
CCTK_DECLARE(CCTK_REAL,out_yzplane_x,)&&\
CCTK_DECLARE(CCTK_REAL,out_zline_x,)&&\
CCTK_DECLARE(CCTK_REAL,out_zline_y,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH10,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH11,)&&\
CCTK_DECLARE(CCTK_STRING,out_criterion,)&&\
CCTK_DECLARE(CCTK_STRING,out_dir,)&&\
CCTK_DECLARE(CCTK_STRING,out_fileinfo,)&&\
CCTK_DECLARE(CCTK_STRING,out_group_separator,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH16,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH18,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH22,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH24,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH26,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH28,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH29,)&&\
CCTK_DECLARE(CCTK_STRING,verbose,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH0,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH1,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH4,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH7,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH8,)&&\
CCTK_DECLARE(CCTK_INT,new_filename_scheme,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH12,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH13,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH14,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH15,)&&\
CCTK_DECLARE(CCTK_INT,out_every,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH17,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH19,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH20,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH21,)&&\
CCTK_DECLARE(CCTK_INT,out_xline_yi,)&&\
CCTK_DECLARE(CCTK_INT,out_xline_zi,)&&\
CCTK_DECLARE(CCTK_INT,out_xyplane_zi,)&&\
CCTK_DECLARE(CCTK_INT,out_xzplane_yi,)&&\
CCTK_DECLARE(CCTK_INT,out_yline_xi,)&&\
CCTK_DECLARE(CCTK_INT,out_yline_zi,)&&\
CCTK_DECLARE(CCTK_INT,out_yzplane_xi,)&&\
CCTK_DECLARE(CCTK_INT,out_zline_xi,)&&\
CCTK_DECLARE(CCTK_INT,out_zline_yi,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH23,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH25,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH27,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH30,)&&\
CCTK_DECLARE(CCTK_INT,strict_io_parameter_check,)&&\
COMMON /IOrest/CCTKH5, out_dt, out_xline_y, out_xline_z, out_xyplane_z, out_xzplane_y, out_yline_x, out_yline_z, out_yzplane_x, out_zline_x, out_zline_y, CCTKH2, CCTKH3, CCTKH6, CCTKH9, CCTKH10, CCTKH11, out_criterion, out_dir, out_fileinfo, out_group_separator, CCTKH16, CCTKH18, CCTKH22, CCTKH24, CCTKH26, CCTKH28, CCTKH29, verbose, CCTKH0, CCTKH1, CCTKH4, CCTKH7, CCTKH8, new_filename_scheme, CCTKH12, CCTKH13, CCTKH14, CCTKH15, out_every, CCTKH17, CCTKH19, CCTKH20, CCTKH21, out_xline_yi, out_xline_zi, out_xyplane_zi, out_xzplane_yi, out_yline_xi, out_yline_zi, out_yzplane_xi, out_zline_xi, out_zline_yi, CCTKH23, CCTKH25, CCTKH27, CCTKH30, strict_io_parameter_check&&\

