#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,SetMask_RadiusFactor,(10))&&\
CCTK_DECLARE(CCTK_STRING,SetMask_MaskName,)&&\
CCTK_DECLARE(CCTK_STRING,SetMask_SurfaceName,(10))&&\
CCTK_DECLARE(CCTK_INT,SetMask_SurfaceIndex,(10))&&\
CCTK_DECLARE(CCTK_INT,SetMask_TrueShape,(10))&&\
COMMON /SetMask_SphericalSurfacepriv/SetMask_RadiusFactor, SetMask_MaskName, SetMask_SurfaceName, SetMask_SurfaceIndex, SetMask_TrueShape&&\
CCTK_DECLARE(CCTK_REAL,CCTKH2,(42))&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,(42))&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH0,(42))&&\
CCTK_DECLARE(CCTK_INT,maxnphi,)&&\
CCTK_DECLARE(CCTK_INT,maxntheta,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH4,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH5,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH6,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH7,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH8,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH9,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH11,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH12,)&&\
COMMON /SPHERICALSURFACErest/CCTKH2, CCTKH1, CCTKH3, CCTKH0, maxnphi, maxntheta, CCTKH4, CCTKH5, CCTKH6, CCTKH7, CCTKH8, CCTKH9, CCTKH10, CCTKH11, CCTKH12&&\

