#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,eps,)&&\
CCTK_DECLARE(CCTK_REAL,exact_offset,)&&\
CCTK_DECLARE(CCTK_REAL,omega,)&&\
CCTK_DECLARE(CCTK_REAL,reset_value,(10))&&\
CCTK_DECLARE(CCTK_REAL,reset_x,)&&\
CCTK_DECLARE(CCTK_REAL,reset_y,)&&\
CCTK_DECLARE(CCTK_REAL,reset_z,)&&\
CCTK_DECLARE(CCTK_REAL,tol,)&&\
CCTK_DECLARE(CCTK_STRING,a0_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,a1_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,a2_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,a3_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,a4_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,boundary_conditions,)&&\
CCTK_DECLARE(CCTK_STRING,c0_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,c1_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,c2_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,c3_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,c4_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,compare_to_exact,)&&\
CCTK_DECLARE(CCTK_STRING,cx_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,cxx_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,cxy_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,cxz_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,cy_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,cycle_type,)&&\
CCTK_DECLARE(CCTK_STRING,cyy_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,cyz_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,cz_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,czz_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,disable,(10))&&\
CCTK_DECLARE(CCTK_STRING,exact_laplacian_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,exact_solution_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,fill_ADM,)&&\
CCTK_DECLARE(CCTK_STRING,fill_Aij,)&&\
CCTK_DECLARE(CCTK_STRING,inipsi_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,mode,)&&\
CCTK_DECLARE(CCTK_STRING,model,)&&\
CCTK_DECLARE(CCTK_STRING,other_gfname,(10))&&\
CCTK_DECLARE(CCTK_STRING,output_norms,)&&\
CCTK_DECLARE(CCTK_STRING,output_walk,)&&\
CCTK_DECLARE(CCTK_STRING,reset_psi,)&&\
CCTK_DECLARE(CCTK_STRING,verbose,)&&\
CCTK_DECLARE(CCTK_STRING,veryverbose,)&&\
CCTK_DECLARE(CCTK_INT,enforce_int,)&&\
CCTK_DECLARE(CCTK_INT,fd_order,)&&\
CCTK_DECLARE(CCTK_INT,integral_refinement,)&&\
CCTK_DECLARE(CCTK_INT,n0,(10))&&\
CCTK_DECLARE(CCTK_INT,n1,(10))&&\
CCTK_DECLARE(CCTK_INT,n2,(10))&&\
CCTK_DECLARE(CCTK_INT,n3,(10))&&\
CCTK_DECLARE(CCTK_INT,n4,(10))&&\
CCTK_DECLARE(CCTK_INT,nrelsteps_bottom,)&&\
CCTK_DECLARE(CCTK_INT,nrelsteps_down,)&&\
CCTK_DECLARE(CCTK_INT,nrelsteps_top,)&&\
CCTK_DECLARE(CCTK_INT,nrelsteps_up,)&&\
CCTK_DECLARE(CCTK_INT,number_of_auxiliaries,)&&\
CCTK_DECLARE(CCTK_INT,number_of_equations,)&&\
CCTK_DECLARE(CCTK_INT,reset_every,)&&\
CCTK_DECLARE(CCTK_INT,topMGlevel,)&&\
COMMON /CT_MultiLevelpriv/eps, exact_offset, omega, reset_value, reset_x, reset_y, reset_z, tol, a0_gfname, a1_gfname, a2_gfname, a3_gfname, a4_gfname, boundary_conditions, c0_gfname, c1_gfname, c2_gfname, c3_gfname, c4_gfname, compare_to_exact, cx_gfname, cxx_gfname, cxy_gfname, cxz_gfname, cy_gfname, cycle_type, cyy_gfname, cyz_gfname, cz_gfname, czz_gfname, disable, exact_laplacian_gfname, exact_solution_gfname, fill_ADM, fill_Aij, inipsi_gfname, mode, model, other_gfname, output_norms, output_walk, reset_psi, verbose, veryverbose, enforce_int, fd_order, integral_refinement, n0, n1, n2, n3, n4, nrelsteps_bottom, nrelsteps_down, nrelsteps_top, nrelsteps_up, number_of_auxiliaries, number_of_equations, reset_every, topMGlevel&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,initial_data,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH8,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH11,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH13,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH14,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH15,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH12,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH16,)&&\
COMMON /ADMBASErest/CCTKH0, CCTKH1, CCTKH2, CCTKH3, initial_data, CCTKH4, CCTKH5, CCTKH6, CCTKH7, CCTKH8, CCTKH9, CCTKH11, CCTKH13, CCTKH14, CCTKH15, CCTKH10, CCTKH12, CCTKH16&&\

