#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,Kc,)&&\
CCTK_DECLARE(CCTK_REAL,Ke,)&&\
CCTK_DECLARE(CCTK_REAL,Pax,)&&\
CCTK_DECLARE(CCTK_REAL,Pay,)&&\
CCTK_DECLARE(CCTK_REAL,Paz,)&&\
CCTK_DECLARE(CCTK_REAL,Pbx,)&&\
CCTK_DECLARE(CCTK_REAL,Pby,)&&\
CCTK_DECLARE(CCTK_REAL,Pbz,)&&\
CCTK_DECLARE(CCTK_REAL,amp,(20))&&\
CCTK_DECLARE(CCTK_REAL,ampC,)&&\
CCTK_DECLARE(CCTK_REAL,ampC1,)&&\
CCTK_DECLARE(CCTK_REAL,ampG,)&&\
CCTK_DECLARE(CCTK_REAL,ampI,)&&\
CCTK_DECLARE(CCTK_REAL,ampS,)&&\
CCTK_DECLARE(CCTK_REAL,ampSg,)&&\
CCTK_DECLARE(CCTK_REAL,ampV,)&&\
CCTK_DECLARE(CCTK_REAL,ampVG,)&&\
CCTK_DECLARE(CCTK_REAL,edgeL,)&&\
CCTK_DECLARE(CCTK_REAL,eps,)&&\
CCTK_DECLARE(CCTK_REAL,kx,)&&\
CCTK_DECLARE(CCTK_REAL,ky,)&&\
CCTK_DECLARE(CCTK_REAL,kz,)&&\
CCTK_DECLARE(CCTK_REAL,l,)&&\
CCTK_DECLARE(CCTK_REAL,massa,)&&\
CCTK_DECLARE(CCTK_REAL,massb,)&&\
CCTK_DECLARE(CCTK_REAL,phasex,)&&\
CCTK_DECLARE(CCTK_REAL,phasey,)&&\
CCTK_DECLARE(CCTK_REAL,phasez,)&&\
CCTK_DECLARE(CCTK_REAL,rBall,)&&\
CCTK_DECLARE(CCTK_REAL,sigma,)&&\
CCTK_DECLARE(CCTK_REAL,sigmax,(20))&&\
CCTK_DECLARE(CCTK_REAL,sigmay,(20))&&\
CCTK_DECLARE(CCTK_REAL,sigmaz,(20))&&\
CCTK_DECLARE(CCTK_REAL,vecA,)&&\
CCTK_DECLARE(CCTK_REAL,x0,(20))&&\
CCTK_DECLARE(CCTK_REAL,xa,)&&\
CCTK_DECLARE(CCTK_REAL,xb,)&&\
CCTK_DECLARE(CCTK_REAL,y0,(20))&&\
CCTK_DECLARE(CCTK_REAL,ya,)&&\
CCTK_DECLARE(CCTK_REAL,yb,)&&\
CCTK_DECLARE(CCTK_REAL,z0,(20))&&\
CCTK_DECLARE(CCTK_REAL,za,)&&\
CCTK_DECLARE(CCTK_REAL,zb,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_BY_Calc_calc_every,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_BY_Calc_calc_offset,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_ExactBoundary_calc_every,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_ExactBoundary_calc_offset,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_Exact_Calc_calc_every,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_Exact_Calc_calc_offset,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_ExpandingLattice_Calc_calc_every,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_ExpandingLattice_Calc_calc_offset,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_LumpBoundary_calc_every,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_LumpBoundary_calc_offset,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_Lump_Calc_calc_every,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_Lump_Calc_calc_offset,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_MaxNumArrayEvolvedVars,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_MaxNumEvolvedVars,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_Poisson_Calc_calc_every,)&&\
CCTK_DECLARE(CCTK_INT,CT_Analytic_Poisson_Calc_calc_offset,)&&\
CCTK_DECLARE(CCTK_INT,imaxF,)&&\
CCTK_DECLARE(CCTK_INT,jmaxF,)&&\
CCTK_DECLARE(CCTK_INT,kmaxF,)&&\
CCTK_DECLARE(CCTK_INT,other_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,rhs_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,tile_size,)&&\
CCTK_DECLARE(CCTK_INT,timelevels,)&&\
CCTK_DECLARE(CCTK_INT,verbose,)&&\
COMMON /CT_Analyticrest/Kc, Ke, Pax, Pay, Paz, Pbx, Pby, Pbz, amp, ampC, ampC1, ampG, ampI, ampS, ampSg, ampV, ampVG, edgeL, eps, kx, ky, kz, l, massa, massb, phasex, phasey, phasez, rBall, sigma, sigmax, sigmay, sigmaz, vecA, x0, xa, xb, y0, ya, yb, z0, za, zb, CT_Analytic_BY_Calc_calc_every, CT_Analytic_BY_Calc_calc_offset, CT_Analytic_ExactBoundary_calc_every, CT_Analytic_ExactBoundary_calc_offset, CT_Analytic_Exact_Calc_calc_every, CT_Analytic_Exact_Calc_calc_offset, CT_Analytic_ExpandingLattice_Calc_calc_every, CT_Analytic_ExpandingLattice_Calc_calc_offset, CT_Analytic_LumpBoundary_calc_every, CT_Analytic_LumpBoundary_calc_offset, CT_Analytic_Lump_Calc_calc_every, CT_Analytic_Lump_Calc_calc_offset, CT_Analytic_MaxNumArrayEvolvedVars, CT_Analytic_MaxNumEvolvedVars, CT_Analytic_Poisson_Calc_calc_every, CT_Analytic_Poisson_Calc_calc_offset, imaxF, jmaxF, kmaxF, other_timelevels, rhs_timelevels, tile_size, timelevels, verbose&&\
CCTK_DECLARE(CCTK_STRING,free_data,)&&\
COMMON /CT_Analyticpriv/free_data&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH0,)&&\
CCTK_DECLARE(CCTK_INT,assume_stress_energy_state,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH1,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH2,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH6,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH8,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH9,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH11,)&&\
COMMON /GENERICFDrest/CCTKH3, CCTKH4, CCTKH5, CCTKH7, CCTKH0, assume_stress_energy_state, CCTKH1, CCTKH2, CCTKH6, CCTKH8, CCTKH9, CCTKH10, CCTKH11&&\
CCTK_DECLARE(CCTK_INT,CCTKH12,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH13,)&&\
CCTK_DECLARE(CCTK_INT,MoL_Num_ArrayEvolved_Vars,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH14,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH15,)&&\
CCTK_DECLARE(CCTK_INT,MoL_Num_Evolved_Vars,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH16,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH17,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH18,)&&\
COMMON /METHODOFLINESrest/CCTKH12, CCTKH13, MoL_Num_ArrayEvolved_Vars, CCTKH14, CCTKH15, MoL_Num_Evolved_Vars, CCTKH16, CCTKH17, CCTKH18&&\

