#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_INT,EHFinder_MaxNumEvolvedVars,)&&\
CCTK_DECLARE(CCTK_INT,EHFinder_Max_Evolved_Array_Size,)&&\
CCTK_DECLARE(CCTK_INT,EHFinder_Num_ArrayEvolved_Vars,)&&\
COMMON /ehfinderrest/EHFinder_MaxNumEvolvedVars, EHFinder_Max_Evolved_Array_Size, EHFinder_Num_ArrayEvolved_Vars&&\
CCTK_DECLARE(CCTK_REAL,cas_a,(10))&&\
CCTK_DECLARE(CCTK_REAL,cas_b,(10))&&\
CCTK_DECLARE(CCTK_REAL,center_x,)&&\
CCTK_DECLARE(CCTK_REAL,center_y,)&&\
CCTK_DECLARE(CCTK_REAL,center_z,)&&\
CCTK_DECLARE(CCTK_REAL,initial_a,(10))&&\
CCTK_DECLARE(CCTK_REAL,initial_b,(10))&&\
CCTK_DECLARE(CCTK_REAL,initial_c,(10))&&\
CCTK_DECLARE(CCTK_REAL,initial_rad,(10))&&\
CCTK_DECLARE(CCTK_REAL,rotation_alpha,(10))&&\
CCTK_DECLARE(CCTK_REAL,rotation_beta,(10))&&\
CCTK_DECLARE(CCTK_REAL,rotation_gamma,(10))&&\
CCTK_DECLARE(CCTK_REAL,shell_width,)&&\
CCTK_DECLARE(CCTK_REAL,translate_x,(10))&&\
CCTK_DECLARE(CCTK_REAL,translate_y,(10))&&\
CCTK_DECLARE(CCTK_REAL,translate_z,(10))&&\
CCTK_DECLARE(CCTK_STRING,area_calculation_method,)&&\
CCTK_DECLARE(CCTK_STRING,area_interpolator,)&&\
CCTK_DECLARE(CCTK_STRING,eh_lapse_type,)&&\
CCTK_DECLARE(CCTK_STRING,eh_metric_type,)&&\
CCTK_DECLARE(CCTK_STRING,eh_shift_type,)&&\
CCTK_DECLARE(CCTK_STRING,file_type,)&&\
CCTK_DECLARE(CCTK_STRING,generator_distribution,)&&\
CCTK_DECLARE(CCTK_STRING,generator_interpolator,)&&\
CCTK_DECLARE(CCTK_STRING,generator_tracking_method,)&&\
CCTK_DECLARE(CCTK_STRING,initial_f,(10))&&\
CCTK_DECLARE(CCTK_STRING,mode,)&&\
CCTK_DECLARE(CCTK_STRING,pde_differences,)&&\
CCTK_DECLARE(CCTK_STRING,re_init_int_method,)&&\
CCTK_DECLARE(CCTK_STRING,surface_direction,)&&\
CCTK_DECLARE(CCTK_STRING,surface_interpolator,)&&\
CCTK_DECLARE(CCTK_STRING,upwind_type,)&&\
CCTK_DECLARE(CCTK_INT,area_interpolation_order,)&&\
CCTK_DECLARE(CCTK_INT,cheat,)&&\
CCTK_DECLARE(CCTK_INT,cheat_iterations,)&&\
CCTK_DECLARE(CCTK_INT,eh_number_level_sets,)&&\
CCTK_DECLARE(CCTK_INT,evolve_generators,)&&\
CCTK_DECLARE(CCTK_INT,generator_interpolation_order,)&&\
CCTK_DECLARE(CCTK_INT,last_iteration_number,)&&\
CCTK_DECLARE(CCTK_INT,maximum_surface_number,)&&\
CCTK_DECLARE(CCTK_INT,n_array_ghosts,)&&\
CCTK_DECLARE(CCTK_INT,nphi,)&&\
CCTK_DECLARE(CCTK_INT,ntheta,)&&\
CCTK_DECLARE(CCTK_INT,number_of_generators,)&&\
CCTK_DECLARE(CCTK_INT,number_of_generators_phi,)&&\
CCTK_DECLARE(CCTK_INT,number_of_generators_theta,)&&\
CCTK_DECLARE(CCTK_INT,re_init_max_iter,)&&\
CCTK_DECLARE(CCTK_INT,re_init_undo,)&&\
CCTK_DECLARE(CCTK_INT,re_init_verbose,)&&\
CCTK_DECLARE(CCTK_INT,re_initialize_every,)&&\
CCTK_DECLARE(CCTK_INT,read_conformal_factor_once,)&&\
CCTK_DECLARE(CCTK_INT,saved_iteration_every,)&&\
CCTK_DECLARE(CCTK_INT,surface_interpolation_order,)&&\
CCTK_DECLARE(CCTK_INT,use_inner_excision,)&&\
CCTK_DECLARE(CCTK_INT,use_outer_excision,)&&\
CCTK_DECLARE(CCTK_INT,use_user_center,)&&\
COMMON /EHFinderpriv/cas_a, cas_b, center_x, center_y, center_z, initial_a, initial_b, initial_c, initial_rad, rotation_alpha, rotation_beta, rotation_gamma, shell_width, translate_x, translate_y, translate_z, area_calculation_method, area_interpolator, eh_lapse_type, eh_metric_type, eh_shift_type, file_type, generator_distribution, generator_interpolator, generator_tracking_method, initial_f, mode, pde_differences, re_init_int_method, surface_direction, surface_interpolator, upwind_type, area_interpolation_order, cheat, cheat_iterations, eh_number_level_sets, evolve_generators, generator_interpolation_order, last_iteration_number, maximum_surface_number, n_array_ghosts, nphi, ntheta, number_of_generators, number_of_generators_phi, number_of_generators_theta, re_init_max_iter, re_init_undo, re_init_verbose, re_initialize_every, read_conformal_factor_once, saved_iteration_every, surface_interpolation_order, use_inner_excision, use_outer_excision, use_user_center&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,initial_data,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,initial_lapse,)&&\
CCTK_DECLARE(CCTK_STRING,initial_shift,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,metric_type,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH11,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH12,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH8,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH13,)&&\
COMMON /ADMBASErest/CCTKH0, CCTKH1, CCTKH2, CCTKH3, initial_data, CCTKH4, CCTKH5, initial_lapse, initial_shift, CCTKH6, CCTKH7, CCTKH9, metric_type, CCTKH11, CCTKH12, CCTKH8, CCTKH10, CCTKH13&&\
CCTK_DECLARE(CCTK_REAL,CCTKH14,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH15,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH16,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH17,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH26,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH27,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH28,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH29,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH30,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH31,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH32,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH33,)&&\
CCTK_DECLARE(CCTK_STRING,bitant_plane,)&&\
CCTK_DECLARE(CCTK_STRING,domain,)&&\
CCTK_DECLARE(CCTK_STRING,quadrant_direction,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH18,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH25,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH19,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH20,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH21,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH22,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH23,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH24,)&&\
COMMON /GRIDrest/CCTKH14, CCTKH15, CCTKH16, CCTKH17, CCTKH26, CCTKH27, CCTKH28, CCTKH29, CCTKH30, CCTKH31, CCTKH32, CCTKH33, bitant_plane, domain, quadrant_direction, CCTKH18, CCTKH25, CCTKH19, CCTKH20, CCTKH21, CCTKH22, CCTKH23, CCTKH24&&\
CCTK_DECLARE(CCTK_INT,MoL_Max_Evolved_Array_Size,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH34,)&&\
CCTK_DECLARE(CCTK_INT,MoL_Num_ArrayEvolved_Vars,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH35,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH36,)&&\
CCTK_DECLARE(CCTK_INT,MoL_Num_Evolved_Vars,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH37,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH38,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH39,)&&\
COMMON /METHODOFLINESrest/MoL_Max_Evolved_Array_Size, CCTKH34, MoL_Num_ArrayEvolved_Vars, CCTKH35, CCTKH36, MoL_Num_Evolved_Vars, CCTKH37, CCTKH38, CCTKH39&&\
CCTK_DECLARE(CCTK_INT,use_mask,)&&\
COMMON /SPACEMASKrest/use_mask&&\

