#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,min_fraction,)&&\
CCTK_DECLARE(CCTK_REAL,movement_threshold_1,)&&\
CCTK_DECLARE(CCTK_REAL,movement_threshold_10,)&&\
CCTK_DECLARE(CCTK_REAL,movement_threshold_2,)&&\
CCTK_DECLARE(CCTK_REAL,movement_threshold_3,)&&\
CCTK_DECLARE(CCTK_REAL,movement_threshold_4,)&&\
CCTK_DECLARE(CCTK_REAL,movement_threshold_5,)&&\
CCTK_DECLARE(CCTK_REAL,movement_threshold_6,)&&\
CCTK_DECLARE(CCTK_REAL,movement_threshold_7,)&&\
CCTK_DECLARE(CCTK_REAL,movement_threshold_8,)&&\
CCTK_DECLARE(CCTK_REAL,movement_threshold_9,)&&\
CCTK_DECLARE(CCTK_REAL,position_x_1,)&&\
CCTK_DECLARE(CCTK_REAL,position_x_10,)&&\
CCTK_DECLARE(CCTK_REAL,position_x_2,)&&\
CCTK_DECLARE(CCTK_REAL,position_x_3,)&&\
CCTK_DECLARE(CCTK_REAL,position_x_4,)&&\
CCTK_DECLARE(CCTK_REAL,position_x_5,)&&\
CCTK_DECLARE(CCTK_REAL,position_x_6,)&&\
CCTK_DECLARE(CCTK_REAL,position_x_7,)&&\
CCTK_DECLARE(CCTK_REAL,position_x_8,)&&\
CCTK_DECLARE(CCTK_REAL,position_x_9,)&&\
CCTK_DECLARE(CCTK_REAL,position_y_1,)&&\
CCTK_DECLARE(CCTK_REAL,position_y_10,)&&\
CCTK_DECLARE(CCTK_REAL,position_y_2,)&&\
CCTK_DECLARE(CCTK_REAL,position_y_3,)&&\
CCTK_DECLARE(CCTK_REAL,position_y_4,)&&\
CCTK_DECLARE(CCTK_REAL,position_y_5,)&&\
CCTK_DECLARE(CCTK_REAL,position_y_6,)&&\
CCTK_DECLARE(CCTK_REAL,position_y_7,)&&\
CCTK_DECLARE(CCTK_REAL,position_y_8,)&&\
CCTK_DECLARE(CCTK_REAL,position_y_9,)&&\
CCTK_DECLARE(CCTK_REAL,position_z_1,)&&\
CCTK_DECLARE(CCTK_REAL,position_z_10,)&&\
CCTK_DECLARE(CCTK_REAL,position_z_2,)&&\
CCTK_DECLARE(CCTK_REAL,position_z_3,)&&\
CCTK_DECLARE(CCTK_REAL,position_z_4,)&&\
CCTK_DECLARE(CCTK_REAL,position_z_5,)&&\
CCTK_DECLARE(CCTK_REAL,position_z_6,)&&\
CCTK_DECLARE(CCTK_REAL,position_z_7,)&&\
CCTK_DECLARE(CCTK_REAL,position_z_8,)&&\
CCTK_DECLARE(CCTK_REAL,position_z_9,)&&\
CCTK_DECLARE(CCTK_REAL,radius_1,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_10,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_2,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_3,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_4,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_5,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_6,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_7,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_8,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_9,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_rel_change_threshold_1,)&&\
CCTK_DECLARE(CCTK_REAL,radius_rel_change_threshold_10,)&&\
CCTK_DECLARE(CCTK_REAL,radius_rel_change_threshold_2,)&&\
CCTK_DECLARE(CCTK_REAL,radius_rel_change_threshold_3,)&&\
CCTK_DECLARE(CCTK_REAL,radius_rel_change_threshold_4,)&&\
CCTK_DECLARE(CCTK_REAL,radius_rel_change_threshold_5,)&&\
CCTK_DECLARE(CCTK_REAL,radius_rel_change_threshold_6,)&&\
CCTK_DECLARE(CCTK_REAL,radius_rel_change_threshold_7,)&&\
CCTK_DECLARE(CCTK_REAL,radius_rel_change_threshold_8,)&&\
CCTK_DECLARE(CCTK_REAL,radius_rel_change_threshold_9,)&&\
CCTK_DECLARE(CCTK_REAL,radius_x_1,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_x_10,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_x_2,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_x_3,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_x_4,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_x_5,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_x_6,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_x_7,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_x_8,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_x_9,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_y_1,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_y_10,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_y_2,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_y_3,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_y_4,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_y_5,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_y_6,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_y_7,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_y_8,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_y_9,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_z_1,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_z_10,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_z_2,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_z_3,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_z_4,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_z_5,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_z_6,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_z_7,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_z_8,(30))&&\
CCTK_DECLARE(CCTK_REAL,radius_z_9,(30))&&\
CCTK_DECLARE(CCTK_INT,active_1,)&&\
CCTK_DECLARE(CCTK_INT,active_10,)&&\
CCTK_DECLARE(CCTK_INT,active_2,)&&\
CCTK_DECLARE(CCTK_INT,active_3,)&&\
CCTK_DECLARE(CCTK_INT,active_4,)&&\
CCTK_DECLARE(CCTK_INT,active_5,)&&\
CCTK_DECLARE(CCTK_INT,active_6,)&&\
CCTK_DECLARE(CCTK_INT,active_7,)&&\
CCTK_DECLARE(CCTK_INT,active_8,)&&\
CCTK_DECLARE(CCTK_INT,active_9,)&&\
CCTK_DECLARE(CCTK_INT,adaptive_block_size,)&&\
CCTK_DECLARE(CCTK_INT,adaptive_block_size_x,)&&\
CCTK_DECLARE(CCTK_INT,adaptive_block_size_y,)&&\
CCTK_DECLARE(CCTK_INT,adaptive_block_size_z,)&&\
CCTK_DECLARE(CCTK_INT,adaptive_refinement,)&&\
CCTK_DECLARE(CCTK_INT,add_levels_automatically,)&&\
CCTK_DECLARE(CCTK_INT,boundary_shiftout,)&&\
CCTK_DECLARE(CCTK_INT,ensure_proper_nesting,)&&\
CCTK_DECLARE(CCTK_INT,expect_symmetric_grids,)&&\
CCTK_DECLARE(CCTK_INT,freeze_unaligned_levels,)&&\
CCTK_DECLARE(CCTK_INT,freeze_unaligned_parent_levels,)&&\
CCTK_DECLARE(CCTK_INT,min_distance,)&&\
CCTK_DECLARE(CCTK_INT,num_centres,)&&\
CCTK_DECLARE(CCTK_INT,num_levels_1,)&&\
CCTK_DECLARE(CCTK_INT,num_levels_10,)&&\
CCTK_DECLARE(CCTK_INT,num_levels_2,)&&\
CCTK_DECLARE(CCTK_INT,num_levels_3,)&&\
CCTK_DECLARE(CCTK_INT,num_levels_4,)&&\
CCTK_DECLARE(CCTK_INT,num_levels_5,)&&\
CCTK_DECLARE(CCTK_INT,num_levels_6,)&&\
CCTK_DECLARE(CCTK_INT,num_levels_7,)&&\
CCTK_DECLARE(CCTK_INT,num_levels_8,)&&\
CCTK_DECLARE(CCTK_INT,num_levels_9,)&&\
CCTK_DECLARE(CCTK_INT,regrid_every,)&&\
CCTK_DECLARE(CCTK_INT,snap_to_coarse,)&&\
CCTK_DECLARE(CCTK_INT,symmetry_parity,)&&\
CCTK_DECLARE(CCTK_INT,symmetry_periodic_x,)&&\
CCTK_DECLARE(CCTK_INT,symmetry_periodic_y,)&&\
CCTK_DECLARE(CCTK_INT,symmetry_periodic_z,)&&\
CCTK_DECLARE(CCTK_INT,symmetry_rotating180,)&&\
CCTK_DECLARE(CCTK_INT,symmetry_rotating90,)&&\
CCTK_DECLARE(CCTK_INT,verbose,)&&\
CCTK_DECLARE(CCTK_INT,veryverbose,)&&\
COMMON /CarpetRegrid2priv/min_fraction, movement_threshold_1, movement_threshold_10, movement_threshold_2, movement_threshold_3, movement_threshold_4, movement_threshold_5, movement_threshold_6, movement_threshold_7, movement_threshold_8, movement_threshold_9, position_x_1, position_x_10, position_x_2, position_x_3, position_x_4, position_x_5, position_x_6, position_x_7, position_x_8, position_x_9, position_y_1, position_y_10, position_y_2, position_y_3, position_y_4, position_y_5, position_y_6, position_y_7, position_y_8, position_y_9, position_z_1, position_z_10, position_z_2, position_z_3, position_z_4, position_z_5, position_z_6, position_z_7, position_z_8, position_z_9, radius_1, radius_10, radius_2, radius_3, radius_4, radius_5, radius_6, radius_7, radius_8, radius_9, radius_rel_change_threshold_1, radius_rel_change_threshold_10, radius_rel_change_threshold_2, radius_rel_change_threshold_3, radius_rel_change_threshold_4, radius_rel_change_threshold_5, radius_rel_change_threshold_6, radius_rel_change_threshold_7, radius_rel_change_threshold_8, radius_rel_change_threshold_9, radius_x_1, radius_x_10, radius_x_2, radius_x_3, radius_x_4, radius_x_5, radius_x_6, radius_x_7, radius_x_8, radius_x_9, radius_y_1, radius_y_10, radius_y_2, radius_y_3, radius_y_4, radius_y_5, radius_y_6, radius_y_7, radius_y_8, radius_y_9, radius_z_1, radius_z_10, radius_z_2, radius_z_3, radius_z_4, radius_z_5, radius_z_6, radius_z_7, radius_z_8, radius_z_9, active_1, active_10, active_2, active_3, active_4, active_5, active_6, active_7, active_8, active_9, adaptive_block_size, adaptive_block_size_x, adaptive_block_size_y, adaptive_block_size_z, adaptive_refinement, add_levels_automatically, boundary_shiftout, ensure_proper_nesting, expect_symmetric_grids, freeze_unaligned_levels, freeze_unaligned_parent_levels, min_distance, num_centres, num_levels_1, num_levels_10, num_levels_2, num_levels_3, num_levels_4, num_levels_5, num_levels_6, num_levels_7, num_levels_8, num_levels_9, regrid_every, snap_to_coarse, symmetry_parity, symmetry_periodic_x, symmetry_periodic_y, symmetry_periodic_z, symmetry_rotating180, symmetry_rotating90, verbose, veryverbose&&\

