/*@@
   @file    InterpToArray.c
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Creates the CCTK variables for thorn InterpToArray
   @enddesc
 @@*/



#include <stddef.h>

#include "InterpToArray/cctk.h"
#include "InterpToArray/cctk_Arguments.h"
#include "cctk_Parameter.h"
#include "cctk_WarnLevel.h"
#include "cctki_Groups.h"
#include "cctki_FortranWrappers.h"
#include "InterpToArray/cctk_ScheduleFunctions.h"

int CactusBindingsVariables_InterpToArray_Initialise(void);
static int CCTKi_BindingsFortranWrapperInterpToArray(void *_GH, void *fpointer);

static int CCTKi_BindingsFortranWrapperInterpToArray(void *_GH, void *fpointer)
{
  cGH const *const GH = _GH;
  const int _cctk_zero = 0;
  void (*function)(INTERPTOARRAY_C2F_PROTO);
  DECLARE_INTERPTOARRAY_C2F
  INITIALISE_INTERPTOARRAY_C2F
  (void) (_cctk_zero + 0);

  function = (void (*) (INTERPTOARRAY_C2F_PROTO)) fpointer;
  function (PASS_INTERPTOARRAY_C2F (GH));

  return (0);
}

int CactusBindingsVariables_InterpToArray_Initialise(void)
{
  const char * warn_mixeddim_gfs = "";
  int warn_mixeddim = 0;
  const CCTK_INT *allow_mixeddim_gfs;


  allow_mixeddim_gfs = CCTK_ParameterGet ("allow_mixeddim_gfs", "Cactus", 0);

  if (CCTKi_CreateGroup ("SCALARS", "INTERPTOARRAY", "INTERPTOARRAY",
                         "SCALAR", "REAL", "PUBLIC",
                         0, 1,
                         "CONSTANT",
                         "", "",
                         "",
                         "nscalars",
                         1,
                         "scalars") == 1)
  {
    warn_mixeddim_gfs = "scalars";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("ARRAYS1D", "INTERPTOARRAY", "INTERPTOARRAY",
                         "ARRAY", "REAL", "PUBLIC",
                         1, 1,
                         "CONSTANT",
                         "ARRAY1D_NPOINTS_I", "",
                         "",
                         "narrays1d",
                         1,
                         "arrays1d") == 1)
  {
    warn_mixeddim_gfs = "arrays1d";
    warn_mixeddim = 1;
  }
  if (CCTKi_CreateGroup ("ARRAYS2D", "INTERPTOARRAY", "INTERPTOARRAY",
                         "ARRAY", "REAL", "PUBLIC",
                         2, 1,
                         "CONSTANT",
                         "ARRAY2D_NPOINTS_I,ARRAY2D_NPOINTS_J", "",
                         "",
                         "narrays2d",
                         1,
                         "arrays2d") == 1)
  {
    warn_mixeddim_gfs = "arrays2d";
    warn_mixeddim = 2;
  }
  if (CCTKi_CreateGroup ("ARRAYS3D", "INTERPTOARRAY", "INTERPTOARRAY",
                         "ARRAY", "REAL", "PUBLIC",
                         3, 1,
                         "CONSTANT",
                         "ARRAY3D_NPOINTS_I,ARRAY3D_NPOINTS_J,ARRAY3D_NPOINTS_K", "",
                         "",
                         "narrays3d",
                         1,
                         "arrays3d") == 1)
  {
    warn_mixeddim_gfs = "arrays3d";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("PARRAYS1D", "INTERPTOARRAY", "INTERPTOARRAY",
                         "ARRAY", "REAL", "PUBLIC",
                         1, 1,
                         "DEFAULT",
                         "PARRAY1D_NPOINTS_I", "NGHOSTS",
                         "",
                         "nparrays1d",
                         1,
                         "parrays1d") == 1)
  {
    warn_mixeddim_gfs = "parrays1d";
    warn_mixeddim = 1;
  }
  if (CCTKi_CreateGroup ("PARRAYS2D", "INTERPTOARRAY", "INTERPTOARRAY",
                         "ARRAY", "REAL", "PUBLIC",
                         2, 1,
                         "DEFAULT",
                         "PARRAY2D_NPOINTS_I,PARRAY2D_NPOINTS_J", "NGHOSTS,NGHOSTS",
                         "",
                         "nparrays2d",
                         1,
                         "parrays2d") == 1)
  {
    warn_mixeddim_gfs = "parrays2d";
    warn_mixeddim = 2;
  }
  if (CCTKi_CreateGroup ("PARRAYS3D", "INTERPTOARRAY", "INTERPTOARRAY",
                         "ARRAY", "REAL", "PUBLIC",
                         3, 1,
                         "DEFAULT",
                         "PARRAY3D_NPOINTS_I,PARRAY3D_NPOINTS_J,PARRAY3D_NPOINTS_K", "NGHOSTS,NGHOSTS,NGHOSTS",
                         "",
                         "nparrays3d",
                         1,
                         "parrays3d") == 1)
  {
    warn_mixeddim_gfs = "parrays3d";
    warn_mixeddim = 3;
  }

  if (*warn_mixeddim_gfs)
  {
    if (allow_mixeddim_gfs && *allow_mixeddim_gfs)
    {
      CCTK_VWarn (2, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "creating GF group '%s' with different dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
    else
    {
      CCTK_VWarn (0, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "cannot create GF group '%s' with dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
 }

  CCTKi_RegisterFortranWrapper("InterpToArray", CCTKi_BindingsFortranWrapperInterpToArray);

  return 0;
}

