/*@@
   @file    TestMoL.c
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Creates the CCTK variables for thorn TestMoL
   @enddesc
 @@*/



#include <stddef.h>

#include "TestMoL/cctk.h"
#include "TestMoL/cctk_Arguments.h"
#include "cctk_Parameter.h"
#include "cctk_WarnLevel.h"
#include "cctki_Groups.h"
#include "cctki_FortranWrappers.h"
#include "TestMoL/cctk_ScheduleFunctions.h"

int CactusBindingsVariables_TestMoL_Initialise(void);
static int CCTKi_BindingsFortranWrapperTestMoL(void *_GH, void *fpointer);

static int CCTKi_BindingsFortranWrapperTestMoL(void *_GH, void *fpointer)
{
  cGH const *const GH = _GH;
  const int _cctk_zero = 0;
  void (*function)(TESTMOL_C2F_PROTO);
  DECLARE_TESTMOL_C2F
  INITIALISE_TESTMOL_C2F
  (void) (_cctk_zero + 0);

  function = (void (*) (TESTMOL_C2F_PROTO)) fpointer;
  function (PASS_TESTMOL_C2F (GH));

  return (0);
}

int CactusBindingsVariables_TestMoL_Initialise(void)
{
  const char * warn_mixeddim_gfs = "";
  int warn_mixeddim = 0;
  const CCTK_INT *allow_mixeddim_gfs;


  allow_mixeddim_gfs = CCTK_ParameterGet ("allow_mixeddim_gfs", "Cactus", 0);

  if (CCTKi_CreateGroup ("EVOLVED_GF", "TESTMOL", "TESTMOL",
                         "GF", "REAL", "PRIVATE",
                         3, 3,
                         "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "evolved_gf") == 1)
  {
    warn_mixeddim_gfs = "evolved_gf";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("RHS_GF", "TESTMOL", "TESTMOL",
                         "GF", "REAL", "PRIVATE",
                         3, 1,
                         "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "rhs_gf") == 1)
  {
    warn_mixeddim_gfs = "rhs_gf";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("EVOLVEDSLOW_GF", "TESTMOL", "TESTMOL",
                         "GF", "REAL", "PRIVATE",
                         3, 3,
                         "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "evolvedslow_gf") == 1)
  {
    warn_mixeddim_gfs = "evolvedslow_gf";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("RHSSLOW_GF", "TESTMOL", "TESTMOL",
                         "GF", "REAL", "PRIVATE",
                         3, 1,
                         "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "rhsslow_gf") == 1)
  {
    warn_mixeddim_gfs = "rhsslow_gf";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("CONSTRAINED_GF", "TESTMOL", "TESTMOL",
                         "GF", "REAL", "PRIVATE",
                         3, 3,
                         "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "constrained_gf") == 1)
  {
    warn_mixeddim_gfs = "constrained_gf";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("SANDR_GF", "TESTMOL", "TESTMOL",
                         "GF", "REAL", "PRIVATE",
                         3, 3,
                         "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "sandr_gf") == 1)
  {
    warn_mixeddim_gfs = "sandr_gf";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("DIFF_GF", "TESTMOL", "TESTMOL",
                         "GF", "REAL", "PRIVATE",
                         3, 1,
                         "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "diff_gf") == 1)
  {
    warn_mixeddim_gfs = "diff_gf";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("ANALYTIC_GF", "TESTMOL", "TESTMOL",
                         "GF", "REAL", "PRIVATE",
                         3, 1,
                         "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "analytic_gf") == 1)
  {
    warn_mixeddim_gfs = "analytic_gf";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("DIFFSLOW_GF", "TESTMOL", "TESTMOL",
                         "GF", "REAL", "PRIVATE",
                         3, 1,
                         "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "diffslow_gf") == 1)
  {
    warn_mixeddim_gfs = "diffslow_gf";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("ANALYTICSLOW_GF", "TESTMOL", "TESTMOL",
                         "GF", "REAL", "PRIVATE",
                         3, 1,
                         "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "analyticslow_gf") == 1)
  {
    warn_mixeddim_gfs = "analyticslow_gf";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("EVOLVED_GA", "TESTMOL", "TESTMOL",
                         "ARRAY", "REAL", "PRIVATE",
                         1, 3,
                         "CONSTANT",
                         "1", "",
                         "",
                         NULL,
                         1,
                         "evolved_ga") == 1)
  {
    warn_mixeddim_gfs = "evolved_ga";
    warn_mixeddim = 1;
  }
  if (CCTKi_CreateGroup ("RHS_GA", "TESTMOL", "TESTMOL",
                         "ARRAY", "REAL", "PRIVATE",
                         1, 3,
                         "CONSTANT",
                         "1", "",
                         "",
                         NULL,
                         1,
                         "rhs_ga") == 1)
  {
    warn_mixeddim_gfs = "rhs_ga";
    warn_mixeddim = 1;
  }
  if (CCTKi_CreateGroup ("CONSTRAINED_GA", "TESTMOL", "TESTMOL",
                         "ARRAY", "REAL", "PRIVATE",
                         1, 3,
                         "CONSTANT",
                         "1", "",
                         "",
                         NULL,
                         1,
                         "constrained_ga") == 1)
  {
    warn_mixeddim_gfs = "constrained_ga";
    warn_mixeddim = 1;
  }
  if (CCTKi_CreateGroup ("SANDR_GA", "TESTMOL", "TESTMOL",
                         "ARRAY", "REAL", "PRIVATE",
                         1, 3,
                         "CONSTANT",
                         "1", "",
                         "",
                         NULL,
                         1,
                         "sandr_ga") == 1)
  {
    warn_mixeddim_gfs = "sandr_ga";
    warn_mixeddim = 1;
  }
  if (CCTKi_CreateGroup ("DIFF_GA", "TESTMOL", "TESTMOL",
                         "ARRAY", "REAL", "PRIVATE",
                         1, 3,
                         "CONSTANT",
                         "1", "",
                         "",
                         NULL,
                         1,
                         "diff_ga") == 1)
  {
    warn_mixeddim_gfs = "diff_ga";
    warn_mixeddim = 1;
  }
  if (CCTKi_CreateGroup ("ANALYTIC_GA", "TESTMOL", "TESTMOL",
                         "ARRAY", "REAL", "PRIVATE",
                         1, 3,
                         "CONSTANT",
                         "1", "",
                         "",
                         NULL,
                         1,
                         "analytic_ga") == 1)
  {
    warn_mixeddim_gfs = "analytic_ga";
    warn_mixeddim = 1;
  }

  if (*warn_mixeddim_gfs)
  {
    if (allow_mixeddim_gfs && *allow_mixeddim_gfs)
    {
      CCTK_VWarn (2, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "creating GF group '%s' with different dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
    else
    {
      CCTK_VWarn (0, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "cannot create GF group '%s' with dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
 }

  CCTKi_RegisterFortranWrapper("TestMoL", CCTKi_BindingsFortranWrapperTestMoL);

  return 0;
}

