/*@@
   @header  Extract/CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn Extract
   @enddesc
 @@*/


#ifndef _EXTRACT_PARAMETERS_H_
#define _EXTRACT_PARAMETERS_H_ 1

#include "CParameterStructNames.h"
#include "ParameterCGlobal.h"
#include "ParameterCPrivateEXTRACT.h"
#include "ParameterCRestrictedADMBASE.h"
#include "ParameterCRestrictedGRID.h"
#include "ParameterCRestrictedIO.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_PRIVATE_EXTRACT_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (const char * const, metric_type, CCTK_PARAMETER__ADMBase__metric_type); \
  CCTK_DECLARE_INIT (const char * const, domain, CCTK_PARAMETER__CartGrid3D__domain); \
  CCTK_DECLARE_INIT (const char * const, out_dir, CCTK_PARAMETER__IOUtil__out_dir); \

#ifndef CCTK_PARAMETER__ADMBase__metric_type
#  define CCTK_PARAMETER__ADMBase__metric_type RESTRICTED_ADMBASE_STRUCT.metric_type
#endif
#ifndef CCTK_PARAMETER__CartGrid3D__domain
#  define CCTK_PARAMETER__CartGrid3D__domain RESTRICTED_GRID_STRUCT.domain
#endif
#ifndef CCTK_PARAMETER__IOUtil__out_dir
#  define CCTK_PARAMETER__IOUtil__out_dir RESTRICTED_IO_STRUCT.out_dir
#endif

#endif  /* _EXTRACT_PARAMETERS_H_ */

