#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,offsetx,(10))&&\
CCTK_DECLARE(CCTK_REAL,offsety,(10))&&\
CCTK_DECLARE(CCTK_REAL,offsetz,(10))&&\
CCTK_DECLARE(CCTK_INT,num_offsets,)&&\
CCTK_DECLARE(CCTK_INT,offset_firstlevel,)&&\
COMMON /CarpetRegridrest/offsetx, offsety, offsetz, num_offsets, offset_firstlevel&&\
CCTK_DECLARE(CCTK_REAL,l1xmax,)&&\
CCTK_DECLARE(CCTK_REAL,l1xmin,)&&\
CCTK_DECLARE(CCTK_REAL,l1ymax,)&&\
CCTK_DECLARE(CCTK_REAL,l1ymin,)&&\
CCTK_DECLARE(CCTK_REAL,l1zmax,)&&\
CCTK_DECLARE(CCTK_REAL,l1zmin,)&&\
CCTK_DECLARE(CCTK_REAL,l2xmax,)&&\
CCTK_DECLARE(CCTK_REAL,l2xmin,)&&\
CCTK_DECLARE(CCTK_REAL,l2ymax,)&&\
CCTK_DECLARE(CCTK_REAL,l2ymin,)&&\
CCTK_DECLARE(CCTK_REAL,l2zmax,)&&\
CCTK_DECLARE(CCTK_REAL,l2zmin,)&&\
CCTK_DECLARE(CCTK_REAL,l3xmax,)&&\
CCTK_DECLARE(CCTK_REAL,l3xmin,)&&\
CCTK_DECLARE(CCTK_REAL,l3ymax,)&&\
CCTK_DECLARE(CCTK_REAL,l3ymin,)&&\
CCTK_DECLARE(CCTK_REAL,l3zmax,)&&\
CCTK_DECLARE(CCTK_REAL,l3zmin,)&&\
CCTK_DECLARE(CCTK_REAL,maxerror,)&&\
CCTK_DECLARE(CCTK_REAL,minfraction,)&&\
CCTK_DECLARE(CCTK_REAL,moving_centre_x,)&&\
CCTK_DECLARE(CCTK_REAL,moving_centre_y,)&&\
CCTK_DECLARE(CCTK_REAL,moving_centre_z,)&&\
CCTK_DECLARE(CCTK_REAL,moving_circle_frequency,)&&\
CCTK_DECLARE(CCTK_REAL,moving_circle_radius,)&&\
CCTK_DECLARE(CCTK_REAL,moving_region_radius,)&&\
CCTK_DECLARE(CCTK_STRING,activate_levels_on_regrid,)&&\
CCTK_DECLARE(CCTK_STRING,coordinates,)&&\
CCTK_DECLARE(CCTK_STRING,errorvar,)&&\
CCTK_DECLARE(CCTK_STRING,gridpoints,)&&\
CCTK_DECLARE(CCTK_STRING,moving_trajectory,)&&\
CCTK_DECLARE(CCTK_STRING,outerbounds,)&&\
CCTK_DECLARE(CCTK_STRING,refined_regions,)&&\
CCTK_DECLARE(CCTK_INT,activate_next,)&&\
CCTK_DECLARE(CCTK_INT,keep_same_grid_structure,)&&\
CCTK_DECLARE(CCTK_INT,l1ixmax,)&&\
CCTK_DECLARE(CCTK_INT,l1ixmin,)&&\
CCTK_DECLARE(CCTK_INT,l1iymax,)&&\
CCTK_DECLARE(CCTK_INT,l1iymin,)&&\
CCTK_DECLARE(CCTK_INT,l1izmax,)&&\
CCTK_DECLARE(CCTK_INT,l1izmin,)&&\
CCTK_DECLARE(CCTK_INT,l2ixmax,)&&\
CCTK_DECLARE(CCTK_INT,l2ixmin,)&&\
CCTK_DECLARE(CCTK_INT,l2iymax,)&&\
CCTK_DECLARE(CCTK_INT,l2iymin,)&&\
CCTK_DECLARE(CCTK_INT,l2izmax,)&&\
CCTK_DECLARE(CCTK_INT,l2izmin,)&&\
CCTK_DECLARE(CCTK_INT,l3ixmax,)&&\
CCTK_DECLARE(CCTK_INT,l3ixmin,)&&\
CCTK_DECLARE(CCTK_INT,l3iymax,)&&\
CCTK_DECLARE(CCTK_INT,l3iymin,)&&\
CCTK_DECLARE(CCTK_INT,l3izmax,)&&\
CCTK_DECLARE(CCTK_INT,l3izmin,)&&\
CCTK_DECLARE(CCTK_INT,merge_overlapping_components,)&&\
CCTK_DECLARE(CCTK_INT,minwidth,)&&\
CCTK_DECLARE(CCTK_INT,num_new_levels,)&&\
CCTK_DECLARE(CCTK_INT,refinement_levels,)&&\
CCTK_DECLARE(CCTK_INT,regrid_every,)&&\
CCTK_DECLARE(CCTK_INT,smart_outer_boundaries,)&&\
CCTK_DECLARE(CCTK_INT,symmetry_x,)&&\
CCTK_DECLARE(CCTK_INT,symmetry_y,)&&\
CCTK_DECLARE(CCTK_INT,symmetry_z,)&&\
CCTK_DECLARE(CCTK_INT,tracking,)&&\
CCTK_DECLARE(CCTK_INT,verbose,)&&\
CCTK_DECLARE(CCTK_INT,veryverbose,)&&\
COMMON /CarpetRegridpriv/l1xmax, l1xmin, l1ymax, l1ymin, l1zmax, l1zmin, l2xmax, l2xmin, l2ymax, l2ymin, l2zmax, l2zmin, l3xmax, l3xmin, l3ymax, l3ymin, l3zmax, l3zmin, maxerror, minfraction, moving_centre_x, moving_centre_y, moving_centre_z, moving_circle_frequency, moving_circle_radius, moving_region_radius, activate_levels_on_regrid, coordinates, errorvar, gridpoints, moving_trajectory, outerbounds, refined_regions, activate_next, keep_same_grid_structure, l1ixmax, l1ixmin, l1iymax, l1iymin, l1izmax, l1izmin, l2ixmax, l2ixmin, l2iymax, l2iymin, l2izmax, l2izmin, l3ixmax, l3ixmin, l3iymax, l3iymin, l3izmax, l3izmin, merge_overlapping_components, minwidth, num_new_levels, refinement_levels, regrid_every, smart_outer_boundaries, symmetry_x, symmetry_y, symmetry_z, tracking, verbose, veryverbose&&\

