#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,amp,)&&\
CCTK_DECLARE(CCTK_REAL,amp_me,)&&\
CCTK_DECLARE(CCTK_REAL,byJ,)&&\
CCTK_DECLARE(CCTK_REAL,eta0,)&&\
CCTK_DECLARE(CCTK_REAL,eta0_me,)&&\
CCTK_DECLARE(CCTK_REAL,etamax,)&&\
CCTK_DECLARE(CCTK_REAL,sigma,)&&\
CCTK_DECLARE(CCTK_REAL,sigma_me,)&&\
CCTK_DECLARE(CCTK_REAL,xi,)&&\
CCTK_DECLARE(CCTK_INT,brandt_seidel,)&&\
CCTK_DECLARE(CCTK_INT,interpolation_order,)&&\
CCTK_DECLARE(CCTK_INT,n,)&&\
CCTK_DECLARE(CCTK_INT,n_me,)&&\
CCTK_DECLARE(CCTK_INT,neta,)&&\
CCTK_DECLARE(CCTK_INT,ntheta,)&&\
CCTK_DECLARE(CCTK_INT,sergio,)&&\
CCTK_DECLARE(CCTK_INT,verbose,)&&\
COMMON /IDAxiOddBrillBHpriv/amp, amp_me, byJ, eta0, eta0_me, etamax, sigma, sigma_me, xi, brandt_seidel, interpolation_order, n, n_me, neta, ntheta, sergio, verbose&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,initial_data,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,initial_lapse,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH8,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH10,)&&\
CCTK_DECLARE(CCTK_STRING,metric_type,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH12,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH13,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH9,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH11,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH14,)&&\
COMMON /ADMBASErest/CCTKH0, CCTKH1, CCTKH2, CCTKH3, initial_data, CCTKH4, CCTKH5, initial_lapse, CCTKH6, CCTKH7, CCTKH8, CCTKH10, metric_type, CCTKH12, CCTKH13, CCTKH9, CCTKH11, CCTKH14&&\
CCTK_DECLARE(CCTK_STRING,conformal_storage,)&&\
COMMON /STATICCONFORMALrest/conformal_storage&&\

