#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,a_Kerr,)&&\
CCTK_DECLARE(CCTK_REAL,bl_M_1,)&&\
CCTK_DECLARE(CCTK_REAL,bl_M_2,)&&\
CCTK_DECLARE(CCTK_REAL,bl_M_3,)&&\
CCTK_DECLARE(CCTK_REAL,bl_M_4,)&&\
CCTK_DECLARE(CCTK_REAL,bl_x0_1,)&&\
CCTK_DECLARE(CCTK_REAL,bl_x0_2,)&&\
CCTK_DECLARE(CCTK_REAL,bl_x0_3,)&&\
CCTK_DECLARE(CCTK_REAL,bl_x0_4,)&&\
CCTK_DECLARE(CCTK_REAL,bl_y0_1,)&&\
CCTK_DECLARE(CCTK_REAL,bl_y0_2,)&&\
CCTK_DECLARE(CCTK_REAL,bl_y0_3,)&&\
CCTK_DECLARE(CCTK_REAL,bl_y0_4,)&&\
CCTK_DECLARE(CCTK_REAL,bl_z0_1,)&&\
CCTK_DECLARE(CCTK_REAL,bl_z0_2,)&&\
CCTK_DECLARE(CCTK_REAL,bl_z0_3,)&&\
CCTK_DECLARE(CCTK_REAL,bl_z0_4,)&&\
CCTK_DECLARE(CCTK_REAL,epsilon,)&&\
CCTK_DECLARE(CCTK_REAL,mass,)&&\
CCTK_DECLARE(CCTK_REAL,mu,)&&\
CCTK_DECLARE(CCTK_INT,bl_nbh,)&&\
CCTK_DECLARE(CCTK_INT,misner_nbh,)&&\
CCTK_DECLARE(CCTK_INT,nmax,)&&\
COMMON /IDAnalyticBHpriv/a_Kerr, bl_M_1, bl_M_2, bl_M_3, bl_M_4, bl_x0_1, bl_x0_2, bl_x0_3, bl_x0_4, bl_y0_1, bl_y0_2, bl_y0_3, bl_y0_4, bl_z0_1, bl_z0_2, bl_z0_3, bl_z0_4, epsilon, mass, mu, bl_nbh, misner_nbh, nmax&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,initial_data,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,initial_lapse,)&&\
CCTK_DECLARE(CCTK_STRING,initial_shift,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,metric_type,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH11,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH12,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH8,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH13,)&&\
COMMON /ADMBASErest/CCTKH0, CCTKH1, CCTKH2, CCTKH3, initial_data, CCTKH4, CCTKH5, initial_lapse, initial_shift, CCTKH6, CCTKH7, CCTKH9, metric_type, CCTKH11, CCTKH12, CCTKH8, CCTKH10, CCTKH13&&\
CCTK_DECLARE(CCTK_STRING,conformal_storage,)&&\
COMMON /STATICCONFORMALrest/conformal_storage&&\

