#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,adjust_timestep__maximum_time_step,)&&\
CCTK_DECLARE(CCTK_REAL,adjust_timestep__rate_of_change,)&&\
CCTK_DECLARE(CCTK_REAL,dt_tolerance,)&&\
CCTK_DECLARE(CCTK_REAL,initial_relaxation_time,)&&\
CCTK_DECLARE(CCTK_REAL,initial_time,)&&\
CCTK_DECLARE(CCTK_STRING,file,)&&\
CCTK_DECLARE(CCTK_STRING,file_gxx,(3))&&\
CCTK_DECLARE(CCTK_STRING,file_gxy,(3))&&\
CCTK_DECLARE(CCTK_STRING,file_gxz,(3))&&\
CCTK_DECLARE(CCTK_STRING,file_gyy,(3))&&\
CCTK_DECLARE(CCTK_STRING,file_gyz,(3))&&\
CCTK_DECLARE(CCTK_STRING,file_gzz,(3))&&\
CCTK_DECLARE(CCTK_STRING,file_lapse,(3))&&\
CCTK_DECLARE(CCTK_STRING,file_shiftx,(3))&&\
CCTK_DECLARE(CCTK_STRING,file_shifty,(3))&&\
CCTK_DECLARE(CCTK_STRING,file_shiftz,(3))&&\
CCTK_DECLARE(CCTK_STRING,format,)&&\
CCTK_DECLARE(CCTK_STRING,path,)&&\
CCTK_DECLARE(CCTK_STRING,sYlm_convention,)&&\
CCTK_DECLARE(CCTK_INT,adjust_timestep,)&&\
CCTK_DECLARE(CCTK_INT,adjust_timestep__target_steps_per_time_level,)&&\
CCTK_DECLARE(CCTK_INT,cached_timesteps,)&&\
CCTK_DECLARE(CCTK_INT,column_data,)&&\
CCTK_DECLARE(CCTK_INT,column_gxx,(3))&&\
CCTK_DECLARE(CCTK_INT,column_gxy,(3))&&\
CCTK_DECLARE(CCTK_INT,column_gxz,(3))&&\
CCTK_DECLARE(CCTK_INT,column_gyy,(3))&&\
CCTK_DECLARE(CCTK_INT,column_gyz,(3))&&\
CCTK_DECLARE(CCTK_INT,column_gzz,(3))&&\
CCTK_DECLARE(CCTK_INT,column_iteration,)&&\
CCTK_DECLARE(CCTK_INT,column_lapse,(3))&&\
CCTK_DECLARE(CCTK_INT,column_lmax,)&&\
CCTK_DECLARE(CCTK_INT,column_n_variables,)&&\
CCTK_DECLARE(CCTK_INT,column_radius,)&&\
CCTK_DECLARE(CCTK_INT,column_shiftx,(3))&&\
CCTK_DECLARE(CCTK_INT,column_shifty,(3))&&\
CCTK_DECLARE(CCTK_INT,column_shiftz,(3))&&\
CCTK_DECLARE(CCTK_INT,column_time,)&&\
CCTK_DECLARE(CCTK_INT,disable_auto_time_offset,)&&\
CCTK_DECLARE(CCTK_INT,lmaxInFile,)&&\
CCTK_DECLARE(CCTK_INT,sphere_number,)&&\
CCTK_DECLARE(CCTK_INT,time_derivative_in_file,)&&\
CCTK_DECLARE(CCTK_INT,time_fd_order,)&&\
CCTK_DECLARE(CCTK_INT,time_interpolate,)&&\
CCTK_DECLARE(CCTK_INT,verbose,)&&\
COMMON /SphericalHarmonicReconGenpriv/adjust_timestep__maximum_time_step, adjust_timestep__rate_of_change, dt_tolerance, initial_relaxation_time, initial_time, file, file_gxx, file_gxy, file_gxz, file_gyy, file_gyz, file_gzz, file_lapse, file_shiftx, file_shifty, file_shiftz, format, path, sYlm_convention, adjust_timestep, adjust_timestep__target_steps_per_time_level, cached_timesteps, column_data, column_gxx, column_gxy, column_gxz, column_gyy, column_gyz, column_gzz, column_iteration, column_lapse, column_lmax, column_n_variables, column_radius, column_shiftx, column_shifty, column_shiftz, column_time, disable_auto_time_offset, lmaxInFile, sphere_number, time_derivative_in_file, time_fd_order, time_interpolate, verbose&&\
CCTK_DECLARE(CCTK_REAL,CCTKH0,)&&\
CCTK_DECLARE(CCTK_REAL,cr,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH1,)&&\
CCTK_DECLARE(CCTK_INT,l_max,)&&\
COMMON /NULLSHREXTRACTrest/CCTKH0, cr, CCTKH1, l_max&&\

