/*@@
   @file       ScheduleSphericalHarmonicDecomp.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn SphericalHarmonicDecomp
   @enddesc
@@*/


#include "SphericalHarmonicDecomp/cctk.h"
#include "SphericalHarmonicDecomp/CParameters.h"
#include "cctki_ScheduleBindings.h"
#include "SphericalHarmonicDecomp/cctk_ScheduleFunctions.h"

/* Prototypes for Fortran schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */


void CCTKi_BindingsSchedule_SphericalHarmonicDecomp(void);
void CCTKi_BindingsSchedule_SphericalHarmonicDecomp(void)
{
  DECLARE_CCTK_PARAMETERS
if (do_test)
{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)SphericalHarmonicDecomp_Test,
                           "SphericalHarmonicDecomp_Test",
                           "SphericalHarmonicDecomp",
                           "SphericalHarmonicDecomp",
                           "test",
                           "CCTK_INITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "");
  }
}
if (extract_spacetime_metric_every)
{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)SphericalHarmonicDecomp_DumpMetric,
                           "SphericalHarmonicDecomp_DumpMetric",
                           "SphericalHarmonicDecomp",
                           "SphericalHarmonicDecomp",
                           "extract and decompose spacetime metric",
                           "CCTK_POSTSTEP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "");
  }
}
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_SphericalHarmonicDecomp
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn SphericalHarmonicDecomp
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_SphericalHarmonicDecomp(void);
int CCTKi_BindingsParameterRecovery_SphericalHarmonicDecomp(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

