/*@@
   @file       Schedulehwloc.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn hwloc
   @enddesc
@@*/


#include "hwloc/cctk.h"
#include "hwloc/CParameters.h"
#include "cctki_ScheduleBindings.h"
#include "hwloc/cctk_ScheduleFunctions.h"

/* Prototypes for Fortran schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */


void CCTKi_BindingsSchedule_hwloc(void);
void CCTKi_BindingsSchedule_hwloc(void)
{
  DECLARE_CCTK_PARAMETERS
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_hwloc
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn hwloc
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_hwloc(void);
int CCTKi_BindingsParameterRecovery_hwloc(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

