/*@@
   @file       ScheduleSystemStatistics.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn SystemStatistics
   @enddesc
@@*/


#include "SystemStatistics/cctk.h"
#include "SystemStatistics/CParameters.h"
#include "cctki_ScheduleBindings.h"
#include "SystemStatistics/cctk_ScheduleFunctions.h"

/* Prototypes for Fortran schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */


void CCTKi_BindingsSchedule_SystemStatistics(void);
void CCTKi_BindingsSchedule_SystemStatistics(void)
{
  DECLARE_CCTK_PARAMETERS
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("SystemStatistics::process_memory")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "SystemStatistics::process_memory", CCTK_DeclaredTimeLevels("SystemStatistics::process_memory"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("SystemStatistics::process_memory_mb")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "SystemStatistics::process_memory_mb", CCTK_DeclaredTimeLevels("SystemStatistics::process_memory_mb"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("SystemStatistics::process_memory_kb")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "SystemStatistics::process_memory_kb", CCTK_DeclaredTimeLevels("SystemStatistics::process_memory_kb"));
  CCTKi_ScheduleGroupStorage("SystemStatistics::process_memory",1);
  CCTKi_ScheduleGroupStorage("SystemStatistics::process_memory_mb",1);
  CCTKi_ScheduleGroupStorage("SystemStatistics::process_memory_kb",1);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)SystemStatistics_Collect,
                           "SystemStatistics_Collect",
                           "SystemStatistics",
                           "SystemStatistics",
                           "Collect system statistics",
                           "CCTK_ANALYSIS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "");
  }
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_SystemStatistics
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn SystemStatistics
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_SystemStatistics(void);
int CCTKi_BindingsParameterRecovery_SystemStatistics(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

