/*@@
   @file       ScheduleTestReduce.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn TestReduce
   @enddesc
@@*/


#include "TestReduce/cctk.h"
#include "TestReduce/CParameters.h"
#include "cctki_ScheduleBindings.h"
#include "TestReduce/cctk_ScheduleFunctions.h"

/* Prototypes for Fortran schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */
extern int CCTK_FNAME(TestReduceF_Maximum)(void);
extern int CCTK_FNAME(TestReduceF_Sum)(void);

void CCTKi_BindingsSchedule_TestReduce(void);
void CCTKi_BindingsSchedule_TestReduce(void)
{
  DECLARE_CCTK_PARAMETERS
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("TestReduce::testreduce_3gfs")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "TestReduce::testreduce_3gfs", CCTK_DeclaredTimeLevels("TestReduce::testreduce_3gfs"));
  CCTKi_ScheduleGroupStorage("TestReduce::testreduce_3gfs",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("TestReduce::testreduce_2gfs")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "TestReduce::testreduce_2gfs", CCTK_DeclaredTimeLevels("TestReduce::testreduce_2gfs"));
  CCTKi_ScheduleGroupStorage("TestReduce::testreduce_2gfs",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("TestReduce::testreduce_1gfs")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "TestReduce::testreduce_1gfs", CCTK_DeclaredTimeLevels("TestReduce::testreduce_1gfs"));
  CCTKi_ScheduleGroupStorage("TestReduce::testreduce_1gfs",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("TestReduce::testreduce_3igfs")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "TestReduce::testreduce_3igfs", CCTK_DeclaredTimeLevels("TestReduce::testreduce_3igfs"));
  CCTKi_ScheduleGroupStorage("TestReduce::testreduce_3igfs",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("TestReduce::testreduce_2igfs")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "TestReduce::testreduce_2igfs", CCTK_DeclaredTimeLevels("TestReduce::testreduce_2igfs"));
  CCTKi_ScheduleGroupStorage("TestReduce::testreduce_2igfs",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("TestReduce::testreduce_1igfs")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "TestReduce::testreduce_1igfs", CCTK_DeclaredTimeLevels("TestReduce::testreduce_1igfs"));
  CCTKi_ScheduleGroupStorage("TestReduce::testreduce_1igfs",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("TestReduce::testreduce_scalars")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "TestReduce::testreduce_scalars", CCTK_DeclaredTimeLevels("TestReduce::testreduce_scalars"));
  CCTKi_ScheduleGroupStorage("TestReduce::testreduce_scalars",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("TestReduce::testreduce_iscalars")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "TestReduce::testreduce_iscalars", CCTK_DeclaredTimeLevels("TestReduce::testreduce_iscalars"));
  CCTKi_ScheduleGroupStorage("TestReduce::testreduce_iscalars",1);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)TestReduce_Initial,
                           "TestReduce_Initial",
                           "TestReduce",
                           "testreduce",
                           "Initialise variables",
                           "CCTK_INITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)TestReduceC_Maximum,
                           "TestReduceC_Maximum",
                           "TestReduce",
                           "testreduce",
                           "Test out maximum reductions from C",
                           "CCTK_POSTINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(TestReduceF_Maximum),
                           "TestReduceF_Maximum",
                           "TestReduce",
                           "testreduce",
                           "Test out maximum reductions from Fortran",
                           "CCTK_POSTINITIAL",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)TestReduceC_Sum,
                           "TestReduceC_Sum",
                           "TestReduce",
                           "testreduce",
                           "Test out sum reductions from C",
                           "CCTK_POSTINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(TestReduceF_Sum),
                           "TestReduceF_Sum",
                           "TestReduce",
                           "testreduce",
                           "Test out sum reductions from Fortran",
                           "CCTK_POSTINITIAL",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "");
  }
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_TestReduce
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn TestReduce
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_TestReduce(void);
int CCTKi_BindingsParameterRecovery_TestReduce(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

