/*@@
   @file       ScheduleHighOrderWaveTest.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn HighOrderWaveTest
   @enddesc
@@*/


#include "HighOrderWaveTest/cctk.h"
#include "HighOrderWaveTest/CParameters.h"
#include "cctki_ScheduleBindings.h"
#include "HighOrderWaveTest/cctk_ScheduleFunctions.h"

/* Prototypes for Fortran schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */


void CCTKi_BindingsSchedule_HighOrderWaveTest(void);
void CCTKi_BindingsSchedule_HighOrderWaveTest(void)
{
  DECLARE_CCTK_PARAMETERS
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_HighOrderWaveTest
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn HighOrderWaveTest
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_HighOrderWaveTest(void);
int CCTKi_BindingsParameterRecovery_HighOrderWaveTest(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

