/*@@
   @file       ScheduleRotatingSymmetry180.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn RotatingSymmetry180
   @enddesc
@@*/


#include "RotatingSymmetry180/cctk.h"
#include "RotatingSymmetry180/CParameters.h"
#include "cctki_ScheduleBindings.h"
#include "RotatingSymmetry180/cctk_ScheduleFunctions.h"

/* Prototypes for Fortran schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */


void CCTKi_BindingsSchedule_RotatingSymmetry180(void);
void CCTKi_BindingsSchedule_RotatingSymmetry180(void)
{
  DECLARE_CCTK_PARAMETERS
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)Rot180_CheckTensorTypes,
                           "Rot180_CheckTensorTypes",
                           "RotatingSymmetry180",
                           "RotatingSymmetry180",
                           "Check tensor type definitions for consistency",
                           "CCTK_PARAMCHECK",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)Rot180_RegisterSymmetry,
                           "Rot180_RegisterSymmetry",
                           "RotatingSymmetry180",
                           "RotatingSymmetry180",
                           "Register symmetry boundaries",
                           "SymmetryRegister",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)Rot180_ComputeLevelExtent,
                           "Rot180_ComputeLevelExtent",
                           "RotatingSymmetry180",
                           "RotatingSymmetry180",
                           "Compute extent of level",
                           "BoundaryConditions",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           1, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "LEVEL",
                           "",
                           "Rot180_ApplyBC");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)Rot180_ApplyBC,
                           "Rot180_ApplyBC",
                           "RotatingSymmetry180",
                           "RotatingSymmetry180",
                           "Apply 180 degree rotational symmetry boundary condition",
                           "BoundaryConditions",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "");
  }
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_RotatingSymmetry180
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn RotatingSymmetry180
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_RotatingSymmetry180(void);
int CCTKi_BindingsParameterRecovery_RotatingSymmetry180(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

