/*@@
   @file       ScheduleIOJpeg.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn IOJpeg
   @enddesc
@@*/


#include "IOJpeg/cctk.h"
#include "IOJpeg/CParameters.h"
#include "cctki_ScheduleBindings.h"
#include "IOJpeg/cctk_ScheduleFunctions.h"

/* Prototypes for Fortran schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */


void CCTKi_BindingsSchedule_IOJpeg(void);
void CCTKi_BindingsSchedule_IOJpeg(void)
{
  DECLARE_CCTK_PARAMETERS
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)IOJpeg_Startup,
                           "IOJpeg_Startup",
                           "IOJpeg",
                           "IOJpeg",
                           "Startup routine",
                           "CCTK_STARTUP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "",
                           "IOUtil_Startup");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)IOJpeg_ChooseOutput,
                           "IOJpeg_ChooseOutput",
                           "IOJpeg",
                           "IOJpeg",
                           "Choose 2D output planes",
                           "CCTK_BASEGRID",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "",
                           "SpatialCoordinates");
  }
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_IOJpeg
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn IOJpeg
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_IOJpeg(void);
int CCTKi_BindingsParameterRecovery_IOJpeg(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

