/*@@
   @file       ScheduleNullSHRExtract.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn NullSHRExtract
   @enddesc
@@*/


#include "NullSHRExtract/cctk.h"
#include "NullSHRExtract/CParameters.h"
#include "cctki_ScheduleBindings.h"
#include "NullSHRExtract/cctk_ScheduleFunctions.h"

/* Prototypes for Fortran schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */
extern int CCTK_FNAME(NullSHRE_FullMetricRecon)(void);
extern int CCTK_FNAME(NullSHRE_PreCalcNSYlm)(void);
extern int CCTK_FNAME(NullSHRE_PreCalcNSYlm)(void);
extern int CCTK_FNAME(NullSHRE_SchPreCalc)(void);
extern int CCTK_FNAME(NullSHRE_SchReadClm)(void);
extern int CCTK_FNAME(NullSHRE_SchMetricRecon)(void);
extern int CCTK_FNAME(NullSHRE_AnaSchMetricRecon)(void);
extern int CCTK_FNAME(NullSHRE_MetricReconPast)(void);
extern int CCTK_FNAME(NullSHRE_Pointing_p_p)(void);
extern int CCTK_FNAME(NullSHRE_InitialWT)(void);
extern int CCTK_FNAME(NullSHRE_Pointing_p)(void);
extern int CCTK_FNAME(NullSHRE_InitialWT)(void);
extern int CCTK_FNAME(NullSHRE_Pointing)(void);
extern int CCTK_FNAME(NullSHRE_ExtractWT)(void);
extern int CCTK_FNAME(NullSHRE_SchReadClm)(void);
extern int CCTK_FNAME(NullSHRE_SchMetricRecon)(void);
extern int CCTK_FNAME(NullSHRE_AnaSchMetricRecon)(void);
extern int CCTK_FNAME(NullSHRE_Pointing)(void);
extern int CCTK_FNAME(NullSHRE_ExtractWT)(void);
extern int CCTK_FNAME(NullSHRE_WTSphHarm)(void);
extern int CCTK_FNAME(wt_WriteSphHarmWT)(void);

void CCTKi_BindingsSchedule_NullSHRExtract(void);
void CCTKi_BindingsSchedule_NullSHRExtract(void)
{
  DECLARE_CCTK_PARAMETERS
if (CCTK_EQUALS(boundary_data,"SHRE")) 
{
  if(!(3 >= 0 && 3  <= CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_gij")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)3, "NullSHRExtract::SHRE_gij", CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_gij"));
  if(!(3 >= 0 && 3  <= CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_git")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)3, "NullSHRExtract::SHRE_git", CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_git"));
  if(!(3 >= 0 && 3  <= CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_beta")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)3, "NullSHRExtract::SHRE_beta", CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_beta"));
  if(!(3 >= 0 && 3  <= CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_alpha")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)3, "NullSHRExtract::SHRE_alpha", CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_alpha"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::SHRE_gij",3);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::SHRE_git",3);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::SHRE_beta",3);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::SHRE_alpha",3);
  if(!(3 >= 0 && 3  <= CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_dgij")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)3, "NullSHRExtract::SHRE_dgij", CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_dgij"));
  if(!(3 >= 0 && 3  <= CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_dgit")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)3, "NullSHRExtract::SHRE_dgit", CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_dgit"));
  if(!(3 >= 0 && 3  <= CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_dbeta")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)3, "NullSHRExtract::SHRE_dbeta", CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_dbeta"));
  if(!(3 >= 0 && 3  <= CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_dalpha")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)3, "NullSHRExtract::SHRE_dalpha", CCTK_DeclaredTimeLevels("NullSHRExtract::SHRE_dalpha"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::SHRE_dgij",3);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::SHRE_dgit",3);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::SHRE_dbeta",3);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::SHRE_dalpha",3);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_r0")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_r0", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_r0"));
  if(!(3 >= 0 && 3  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_r1")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)3, "NullSHRExtract::WT_r1", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_r1"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_dj0_vect")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_dj0_vect", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_dj0_vect"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_r0",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_r1",3);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_dj0_vect",1);
  if(!(2 >= 0 && 2  <= CCTK_DeclaredTimeLevels("NullVars::realcharfuncs")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)2, "NullVars::realcharfuncs", CCTK_DeclaredTimeLevels("NullVars::realcharfuncs"));
  CCTKi_ScheduleGroupStorage("NullVars::realcharfuncs",2);
  if(!(2 >= 0 && 2  <= CCTK_DeclaredTimeLevels("NullVars::cmplxcharfuncs_basic")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)2, "NullVars::cmplxcharfuncs_basic", CCTK_DeclaredTimeLevels("NullVars::cmplxcharfuncs_basic"));
  CCTKi_ScheduleGroupStorage("NullVars::cmplxcharfuncs_basic",2);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullVars::null_mask")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullVars::null_mask", CCTK_DeclaredTimeLevels("NullVars::null_mask"));
  CCTKi_ScheduleGroupStorage("NullVars::null_mask",1);
  if (first_order_scheme) {
  if(!(2 >= 0 && 2  <= CCTK_DeclaredTimeLevels("NullVars::cmplxcharfuncs_aux")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)2, "NullVars::cmplxcharfuncs_aux", CCTK_DeclaredTimeLevels("NullVars::cmplxcharfuncs_aux"));
  CCTKi_ScheduleGroupStorage("NullVars::cmplxcharfuncs_aux",2);
  }
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_CmpxCoord")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_CmpxCoord", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_CmpxCoord"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_CmpxCoord",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_scalars")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_scalars", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_scalars"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_3vectors")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_3vectors", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_3vectors"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_4vectors")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_4vectors", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_4vectors"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_d4vectors")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_d4vectors", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_d4vectors"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_scalars",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_3vectors",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_4vectors",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_d4vectors",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_dsigma_vect")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_dsigma_vect", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_dsigma_vect"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_g1_vect")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_g1_vect", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_g1_vect"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_gup_vect")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_gup_vect", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_gup_vect"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_dsigma_vect",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_g1_vect",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_gup_vect",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_jac")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_jac", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_jac"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_affine_metric")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_affine_metric", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_affine_metric"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_deta0_vect")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::WT_deta0_vect", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_deta0_vect"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_jac",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_affine_metric",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::WT_deta0_vect",1);
  if(!(2 >= 0 && 2  <= CCTK_DeclaredTimeLevels("NullSHRExtract::x_wt")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)2, "NullSHRExtract::x_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::x_wt"));
  if(!(2 >= 0 && 2  <= CCTK_DeclaredTimeLevels("NullSHRExtract::j_wt")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)2, "NullSHRExtract::j_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::j_wt"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::j_l")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::j_l", CCTK_DeclaredTimeLevels("NullSHRExtract::j_l"));
  if(!(2 >= 0 && 2  <= CCTK_DeclaredTimeLevels("NullSHRExtract::beta_wt")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)2, "NullSHRExtract::beta_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::beta_wt"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::beta_l")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::beta_l", CCTK_DeclaredTimeLevels("NullSHRExtract::beta_l"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::x_wt",2);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::j_wt",2);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::j_l",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::beta_wt",2);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::beta_l",1);
  if(!(2 >= 0 && 2  <= CCTK_DeclaredTimeLevels("NullSHRExtract::q_wt")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)2, "NullSHRExtract::q_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::q_wt"));
  if(!(2 >= 0 && 2  <= CCTK_DeclaredTimeLevels("NullSHRExtract::u_wt")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)2, "NullSHRExtract::u_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::u_wt"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::u_l")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::u_l", CCTK_DeclaredTimeLevels("NullSHRExtract::u_l"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::u_x_wt")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::u_x_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::u_x_wt"));
  if(!(2 >= 0 && 2  <= CCTK_DeclaredTimeLevels("NullSHRExtract::w_wt")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)2, "NullSHRExtract::w_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::w_wt"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::w_l")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::w_l", CCTK_DeclaredTimeLevels("NullSHRExtract::w_l"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::q_wt",2);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::u_wt",2);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::u_l",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::u_x_wt",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::w_wt",2);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::w_l",1);
  if (CCTK_EQUALS(WT_metric, "Full")) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_FullMetricRecon),
                           "NullSHRE_FullMetricRecon",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Current extraction of Full Metric and its Derivatives on the Sphere",
                           "MetricReconstruction",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "");
  }
  } 
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::NYlm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::NYlm", CCTK_DeclaredTimeLevels("NullSHRExtract::NYlm"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::SYlm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::SYlm", CCTK_DeclaredTimeLevels("NullSHRExtract::SYlm"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::N1Ylm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::N1Ylm", CCTK_DeclaredTimeLevels("NullSHRExtract::N1Ylm"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::S1Ylm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::S1Ylm", CCTK_DeclaredTimeLevels("NullSHRExtract::S1Ylm"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::NYlm",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::SYlm",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::N1Ylm",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::S1Ylm",1);
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::Clm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::Clm", CCTK_DeclaredTimeLevels("NullSHRExtract::Clm"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::drClm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::drClm", CCTK_DeclaredTimeLevels("NullSHRExtract::drClm"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::dtClm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::dtClm", CCTK_DeclaredTimeLevels("NullSHRExtract::dtClm"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::Clm",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::drClm",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::dtClm",1);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_PreCalcNSYlm),
                           "NullSHRE_PreCalcNSYlm",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Precalculate spherical harmonics in (p,q) coordinates",
                           "CCTK_INITIAL",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           2, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "",
                           "NullEvol_BoundaryInit",
                           "NullEvol_Initial");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_PreCalcNSYlm),
                           "NullSHRE_PreCalcNSYlm",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Precalculate spherical harmonics in (p,q) coordinates",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "");
  }
   if (CCTK_EQUALS(WT_metric, "SchIEF")) {
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::NTYlm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::NTYlm", CCTK_DeclaredTimeLevels("NullSHRExtract::NTYlm"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::STYlm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::STYlm", CCTK_DeclaredTimeLevels("NullSHRExtract::STYlm"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::NT1Ylm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::NT1Ylm", CCTK_DeclaredTimeLevels("NullSHRExtract::NT1Ylm"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::ST1Ylm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::ST1Ylm", CCTK_DeclaredTimeLevels("NullSHRExtract::ST1Ylm"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::NTYlm",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::STYlm",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::NT1Ylm",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::ST1Ylm",1);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_SchPreCalc),
                           "NullSHRE_SchPreCalc",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Computes the Schwarzchild Metric Spherical Harmonic Coefficients",
                           "CCTK_INITIAL",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_PreCalcNSYlm");
  }
   }
  {
    int cctkschedulei_tlevelarray[] = {1,1,1,1,1,1,1,1,1,1,1,2,2,1,2,1,2,1,1,2,1,2,0};
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_CmpxCoord")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_CmpxCoord", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_CmpxCoord"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_scalars")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_scalars", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_scalars"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_3vectors")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_3vectors", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_3vectors"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_4vectors")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_4vectors", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_4vectors"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_d4vectors")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_d4vectors", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_d4vectors"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_dsigma_vect")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_dsigma_vect", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_dsigma_vect"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_g1_vect")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_g1_vect", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_g1_vect"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_gup_vect")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_gup_vect", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_gup_vect"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_jac")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_jac", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_jac"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_affine_metric")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_affine_metric", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_affine_metric"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::WT_deta0_vect")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::WT_deta0_vect", CCTK_DeclaredTimeLevels("NullSHRExtract::WT_deta0_vect"));
    if(!(2 >= 0 && 2 <= CCTK_DeclaredTimeLevels("NullSHRExtract::x_wt")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)2, "NullSHRExtract::x_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::x_wt"));
    if(!(2 >= 0 && 2 <= CCTK_DeclaredTimeLevels("NullSHRExtract::j_wt")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)2, "NullSHRExtract::j_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::j_wt"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::j_l")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::j_l", CCTK_DeclaredTimeLevels("NullSHRExtract::j_l"));
    if(!(2 >= 0 && 2 <= CCTK_DeclaredTimeLevels("NullSHRExtract::beta_wt")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)2, "NullSHRExtract::beta_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::beta_wt"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::beta_l")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::beta_l", CCTK_DeclaredTimeLevels("NullSHRExtract::beta_l"));
    if(!(2 >= 0 && 2 <= CCTK_DeclaredTimeLevels("NullSHRExtract::u_wt")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)2, "NullSHRExtract::u_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::u_wt"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::u_l")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::u_l", CCTK_DeclaredTimeLevels("NullSHRExtract::u_l"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::u_x_wt")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::u_x_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::u_x_wt"));
    if(!(2 >= 0 && 2 <= CCTK_DeclaredTimeLevels("NullSHRExtract::w_wt")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)2, "NullSHRExtract::w_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::w_wt"));
    if(!(1 >= 0 && 1 <= CCTK_DeclaredTimeLevels("NullSHRExtract::w_l")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)1, "NullSHRExtract::w_l", CCTK_DeclaredTimeLevels("NullSHRExtract::w_l"));
    if(!(2 >= 0 && 2 <= CCTK_DeclaredTimeLevels("NullSHRExtract::q_wt")))
        CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                   "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                   "Value must be between 0 and %d (inclusive)",
                   (long)2, "NullSHRExtract::q_wt", CCTK_DeclaredTimeLevels("NullSHRExtract::q_wt"));
    CCTKi_ScheduleGroup("NullSHRExtractInitial",
"NullSHRExtractInitial",
                        "NullSHRExtract",
                        "NullSHRExtract",
                        "Group of the waveform extraction initialization",
                        "NullEvol_BoundaryInit",
                        22,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        0, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "NullSHRExtract::WT_CmpxCoord",
                        "NullSHRExtract::WT_scalars",
                        "NullSHRExtract::WT_3vectors",
                        "NullSHRExtract::WT_4vectors",
                        "NullSHRExtract::WT_d4vectors",
                        "NullSHRExtract::WT_dsigma_vect",
                        "NullSHRExtract::WT_g1_vect",
                        "NullSHRExtract::WT_gup_vect",
                        "NullSHRExtract::WT_jac",
                        "NullSHRExtract::WT_affine_metric",
                        "NullSHRExtract::WT_deta0_vect",
                        "NullSHRExtract::x_wt",
                        "NullSHRExtract::j_wt",
                        "NullSHRExtract::j_l",
                        "NullSHRExtract::beta_wt",
                        "NullSHRExtract::beta_l",
                        "NullSHRExtract::u_wt",
                        "NullSHRExtract::u_l",
                        "NullSHRExtract::u_x_wt",
                        "NullSHRExtract::w_wt",
                        "NullSHRExtract::w_l",
                        "NullSHRExtract::q_wt",
                        "");
  }
   if (CCTK_EQUALS(WT_metric, "Full")) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("SphericalHarmonicReconRead",
"SphericalHarmonicReconRead",
                        "NullSHRExtract",
                        "NullSHRExtract",
                        "Schedule group for reconstructing initial world-tube data",
                        "NullEvol_BoundaryInit",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        1, /* Number of BEFORE   routines  */
                        0, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "NullSHRExtractInitial");
  }
   } 
   if (CCTK_EQUALS(WT_metric, "SchIEF")) {
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::TClm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::TClm", CCTK_DeclaredTimeLevels("NullSHRExtract::TClm"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::TCtlm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::TCtlm", CCTK_DeclaredTimeLevels("NullSHRExtract::TCtlm"));
  if(!(1 >= 0 && 1  <= CCTK_DeclaredTimeLevels("NullSHRExtract::TCrlm")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)1, "NullSHRExtract::TCrlm", CCTK_DeclaredTimeLevels("NullSHRExtract::TCrlm"));
  CCTKi_ScheduleGroupStorage("NullSHRExtract::TClm",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::TCtlm",1);
  CCTKi_ScheduleGroupStorage("NullSHRExtract::TCrlm",1);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_SchReadClm),
                           "NullSHRE_SchReadClm",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Computes the Schwarzchild Spherical Harmonic Coefficients",
                           "NullSHRExtractInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           2, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_SchMetricRecon",
                           "NullSHRE_MetricReconPast");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_SchMetricRecon),
                           "NullSHRE_SchMetricRecon",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Schwarzchild Metric and its Derivatives on the Sphere",
                           "NullSHRExtractInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           1, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_MetricReconPast",
                           "NullSHRE_SchReadClm");
  }
     if (ana_metric) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_AnaSchMetricRecon),
                           "NullSHRE_AnaSchMetricRecon",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Analytic Schwarzchild Metric and its Derivatives on the Sphere",
                           "NullSHRExtractInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           1, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_MetricReconPast",
                           "NullSHRE_SchMetricRecon");
  }
     }
   }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_MetricReconPast),
                           "NullSHRE_MetricReconPast",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Copy current metric to Past Levels",
                           "NullSHRExtractInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           1, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_Pointing_p_p");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_Pointing_p_p),
                           "NullSHRE_Pointing_p_p",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Target P-P Level Variables for the pointers used in initialization",
                           "NullSHRExtractInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           1, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_InitialWT_p_p");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_InitialWT),
                           "NullSHRE_InitialWT_p_p",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Extracted variables on the world tube for the p_p_Init level only up to rl",
                           "NullSHRExtractInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_Pointing_p_p");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_Pointing_p),
                           "NullSHRE_Pointing_p",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Target P-Level Variables for the pointers used in initialization",
                           "NullSHRExtractInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           1, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_InitialWT_p",
                           "NullSHRE_InitialWT_p_p");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_InitialWT),
                           "NullSHRE_InitialWT_p",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Extracted variables on the world tube for the p-Init level only up to rl",
                           "NullSHRExtractInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_Pointing_p");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_Pointing),
                           "NullSHRE_Pointing",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Gives the target Variables for the pointers used in initialization",
                           "NullSHRExtractInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           1, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_InitialWT",
                           "NullSHRE_InitialWT_p");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_ExtractWT),
                           "NullSHRE_ExtractWT",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Computes the extracted variables on the world tube for the Initial level",
                           "NullSHRExtractInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_Pointing");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("NullSHRExtract",
"NullSHRExtract",
                        "NullSHRExtract",
                        "NullSHRExtract",
                        "Group of the waveform extraction current level",
                        "NullEvol_Boundary",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        0, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "");
  }
   if (CCTK_EQUALS(WT_metric, "Full")) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("SphericalHarmonicReconRead",
"SphericalHarmonicReconRead",
                        "NullSHRExtract",
                        "NullSHRExtract",
                        "Schedule group for reconstructing current world-tube data",
                        "NullEvol_Boundary",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        1, /* Number of BEFORE   routines  */
                        0, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "NullSHRExtract");
  }
   }
   if (CCTK_EQUALS(WT_metric, "SchIEF")) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_SchReadClm),
                           "NullSHRE_SchReadClm",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Current Schwarzchild Spherical Harmonic Coefficients",
                           "NullSHRExtract",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           2, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_SchMetricRecon",
                           "NullSHRE_Pointing");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_SchMetricRecon),
                           "NullSHRE_SchMetricRecon",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Current Schwarzchild Metric and its Derivatives on the Sphere",
                           "NullSHRExtract",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           1, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_Pointing",
                           "NullSHRE_SchReadClm");
  }
     if (ana_metric) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_AnaSchMetricRecon),
                           "NullSHRE_AnaSchMetricRecon",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Current Analytic Schwarzchild Metric and its Derivatives on the Sphere",
                           "NullSHRExtract",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           1, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_Pointing",
                           "NullSHRE_SchMetricRecon");
  }
     }
   }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_Pointing),
                           "NullSHRE_Pointing",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Gives the target variables for the pointers used in extraction",
                           "NullSHRExtract",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           1, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_ExtractWT");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_ExtractWT),
                           "NullSHRE_ExtractWT",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "Computes the extracted variables on the world tube for the Current level",
                           "NullSHRExtract",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           1, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "",
                           "NullSHRE_Pointing");
  }
if (WT_spherical_harmonics)
{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(NullSHRE_WTSphHarm),
                           "NullSHRE_WTSphHarm",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "If requested, output spherical harmonics of the quantities computed on the Worldtube",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "");
  }
}
if (WT_spherical_harmonics_on_nullgrid)
{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(wt_WriteSphHarmWT),
                           "wt_WriteSphHarmWT",
                           "NullSHRExtract",
                           "NullSHRExtract",
                           "If requested, output spherical harmonics of the quantities computed on the nullgrid just off the Worldtube",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "");
  }
}
}
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_NullSHRExtract
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn NullSHRExtract
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_NullSHRExtract(void);
int CCTKi_BindingsParameterRecovery_NullSHRExtract(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

