/*@@
   @file       ScheduleCarpetTracker.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn CarpetTracker
   @enddesc
@@*/


#include "CarpetTracker/cctk.h"
#include "CarpetTracker/CParameters.h"
#include "cctki_ScheduleBindings.h"
#include "CarpetTracker/cctk_ScheduleFunctions.h"

/* Prototypes for Fortran schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */


void CCTKi_BindingsSchedule_CarpetTracker(void);
void CCTKi_BindingsSchedule_CarpetTracker(void)
{
  DECLARE_CCTK_PARAMETERS
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CarpetTracker_SetPositions,
                           "CarpetTracker_SetPositions",
                           "CarpetTracker",
                           "CarpetTracker",
                           "Set positions of refined regions",
                           "CCTK_PREREGRID",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "");
  }
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_CarpetTracker
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn CarpetTracker
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_CarpetTracker(void);
int CCTKi_BindingsParameterRecovery_CarpetTracker(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

