/*@@
   @file       ScheduleWeylScal4.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn WeylScal4
   @enddesc
@@*/


#include "WeylScal4/cctk.h"
#include "WeylScal4/CParameters.h"
#include "cctki_ScheduleBindings.h"
#include "WeylScal4/cctk_ScheduleFunctions.h"

/* Prototypes for Fortran schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */


void CCTKi_BindingsSchedule_WeylScal4(void);
void CCTKi_BindingsSchedule_WeylScal4(void)
{
  DECLARE_CCTK_PARAMETERS
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::Psi0r_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::Psi0r_group", CCTK_DeclaredTimeLevels("WeylScal4::Psi0r_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::Psi0r_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::Psi0i_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::Psi0i_group", CCTK_DeclaredTimeLevels("WeylScal4::Psi0i_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::Psi0i_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::Psi1r_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::Psi1r_group", CCTK_DeclaredTimeLevels("WeylScal4::Psi1r_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::Psi1r_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::Psi1i_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::Psi1i_group", CCTK_DeclaredTimeLevels("WeylScal4::Psi1i_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::Psi1i_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::Psi2r_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::Psi2r_group", CCTK_DeclaredTimeLevels("WeylScal4::Psi2r_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::Psi2r_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::Psi2i_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::Psi2i_group", CCTK_DeclaredTimeLevels("WeylScal4::Psi2i_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::Psi2i_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::Psi3r_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::Psi3r_group", CCTK_DeclaredTimeLevels("WeylScal4::Psi3r_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::Psi3r_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::Psi3i_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::Psi3i_group", CCTK_DeclaredTimeLevels("WeylScal4::Psi3i_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::Psi3i_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::Psi4r_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::Psi4r_group", CCTK_DeclaredTimeLevels("WeylScal4::Psi4r_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::Psi4r_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::Psi4i_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::Psi4i_group", CCTK_DeclaredTimeLevels("WeylScal4::Psi4i_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::Psi4i_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::curvIr_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::curvIr_group", CCTK_DeclaredTimeLevels("WeylScal4::curvIr_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::curvIr_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::curvIi_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::curvIi_group", CCTK_DeclaredTimeLevels("WeylScal4::curvIi_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::curvIi_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::curvJr_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::curvJr_group", CCTK_DeclaredTimeLevels("WeylScal4::curvJr_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::curvJr_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::curvJi_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::curvJi_group", CCTK_DeclaredTimeLevels("WeylScal4::curvJi_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::curvJi_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::curvJ1_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::curvJ1_group", CCTK_DeclaredTimeLevels("WeylScal4::curvJ1_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::curvJ1_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::curvJ2_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::curvJ2_group", CCTK_DeclaredTimeLevels("WeylScal4::curvJ2_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::curvJ2_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::curvJ3_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::curvJ3_group", CCTK_DeclaredTimeLevels("WeylScal4::curvJ3_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::curvJ3_group",timelevels);
  if(!(timelevels >= 0 && timelevels  <= CCTK_DeclaredTimeLevels("WeylScal4::curvJ4_group")))
      CCTK_VWarn(0, __LINE__, __FILE__, CCTK_THORNSTRING,
                 "Tried to schedule %ld timelevels for group '%s' in schedule.ccl.\n"
                 "Value must be between 0 and %d (inclusive)",
                 (long)timelevels, "WeylScal4::curvJ4_group", CCTK_DeclaredTimeLevels("WeylScal4::curvJ4_group"));
  CCTKi_ScheduleGroupStorage("WeylScal4::curvJ4_group",timelevels);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_Startup,
                           "WeylScal4_Startup",
                           "WeylScal4",
                           "WeylScal4",
                           "create banner",
                           "CCTK_STARTUP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "meta",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_RegisterSymmetries,
                           "WeylScal4_RegisterSymmetries",
                           "WeylScal4",
                           "WeylScal4",
                           "register symmetries",
                           "SymmetryRegister",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "meta",
                           "");
  }
if (CCTK_EQUALS(calc_scalars, "psi4"))
{
  if (CCTK_EQUALS(fd_order, "Nth"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psi4_calc_Nth_group",
"WeylScal4_psi4_calc_Nth_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psi4_calc_Nth",
                        "MoL_PseudoEvolution",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "ADMBase_SetADMVars");
  }
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psi4_calc_Nth,
                           "WeylScal4_psi4_calc_Nth",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psi4_calc_Nth",
                           "WeylScal4_psi4_calc_Nth_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           2, /* Number of WRITES clauses     */
                           15, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi4i(Interior)",
                           "WeylScal4::Psi4r(Interior)",
                           "admbase::kxx(Everywhere)",
                           "admbase::kxy(Everywhere)",
                           "admbase::kxz(Everywhere)",
                           "admbase::kyy(Everywhere)",
                           "admbase::kyz(Everywhere)",
                           "admbase::kzz(Everywhere)",
                           "admbase::gxx(Everywhere)",
                           "admbase::gxy(Everywhere)",
                           "admbase::gxz(Everywhere)",
                           "admbase::gyy(Everywhere)",
                           "admbase::gyz(Everywhere)",
                           "admbase::gzz(Everywhere)",
                           "grid::x(Everywhere)",
                           "grid::y(Everywhere)",
                           "grid::z(Everywhere)",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psi4_calc_Nth_SelectBCs,
                           "WeylScal4_psi4_calc_Nth_SelectBCs",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psi4_calc_Nth_SelectBCs",
                           "WeylScal4_psi4_calc_Nth_bc_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           2, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi4i_group",
                           "WeylScal4::Psi4r_group",
                           "level",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("ApplyBCs",
"WeylScal4_psi4_calc_Nth_ApplyBCs",
                        "WeylScal4",
                        "WeylScal4",
                        "Apply BCs for groups set in WeylScal4_psi4_calc_Nth",
                        "WeylScal4_psi4_calc_Nth_bc_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psi4_calc_Nth_SelectBCs");
  }
if (CCTK_EQUALS(calc_scalars, "psi4"))
{
  if (CCTK_EQUALS(fd_order, "Nth"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psi4_calc_Nth_bc_group",
"WeylScal4_psi4_calc_Nth_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psi4_calc_Nth",
                        "WeylScal4_psi4_calc_Nth_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psi4_calc_Nth");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psi4"))
{
  if (CCTK_EQUALS(fd_order, "Nth"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psi4_calc_Nth_bc_group",
"WeylScal4_psi4_calc_Nth_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psi4_calc_Nth",
                        "MoL_PseudoEvolutionBoundaries",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "MoL_PostStep");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psi4"))
{
  if (CCTK_EQUALS(fd_order, "2nd"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psi4_calc_2nd_group",
"WeylScal4_psi4_calc_2nd_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psi4_calc_2nd",
                        "MoL_PseudoEvolution",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "ADMBase_SetADMVars");
  }
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psi4_calc_2nd,
                           "WeylScal4_psi4_calc_2nd",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psi4_calc_2nd",
                           "WeylScal4_psi4_calc_2nd_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           2, /* Number of WRITES clauses     */
                           15, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi4i(Interior)",
                           "WeylScal4::Psi4r(Interior)",
                           "admbase::kxx(Everywhere)",
                           "admbase::kxy(Everywhere)",
                           "admbase::kxz(Everywhere)",
                           "admbase::kyy(Everywhere)",
                           "admbase::kyz(Everywhere)",
                           "admbase::kzz(Everywhere)",
                           "admbase::gxx(Everywhere)",
                           "admbase::gxy(Everywhere)",
                           "admbase::gxz(Everywhere)",
                           "admbase::gyy(Everywhere)",
                           "admbase::gyz(Everywhere)",
                           "admbase::gzz(Everywhere)",
                           "grid::x(Everywhere)",
                           "grid::y(Everywhere)",
                           "grid::z(Everywhere)",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psi4_calc_2nd_SelectBCs,
                           "WeylScal4_psi4_calc_2nd_SelectBCs",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psi4_calc_2nd_SelectBCs",
                           "WeylScal4_psi4_calc_2nd_bc_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           2, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi4i_group",
                           "WeylScal4::Psi4r_group",
                           "level",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("ApplyBCs",
"WeylScal4_psi4_calc_2nd_ApplyBCs",
                        "WeylScal4",
                        "WeylScal4",
                        "Apply BCs for groups set in WeylScal4_psi4_calc_2nd",
                        "WeylScal4_psi4_calc_2nd_bc_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psi4_calc_2nd_SelectBCs");
  }
if (CCTK_EQUALS(calc_scalars, "psi4"))
{
  if (CCTK_EQUALS(fd_order, "2nd"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psi4_calc_2nd_bc_group",
"WeylScal4_psi4_calc_2nd_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psi4_calc_2nd",
                        "WeylScal4_psi4_calc_2nd_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psi4_calc_2nd");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psi4"))
{
  if (CCTK_EQUALS(fd_order, "2nd"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psi4_calc_2nd_bc_group",
"WeylScal4_psi4_calc_2nd_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psi4_calc_2nd",
                        "MoL_PseudoEvolutionBoundaries",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "MoL_PostStep");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psi4"))
{
  if (CCTK_EQUALS(fd_order, "4th"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psi4_calc_4th_group",
"WeylScal4_psi4_calc_4th_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psi4_calc_4th",
                        "MoL_PseudoEvolution",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "ADMBase_SetADMVars");
  }
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psi4_calc_4th,
                           "WeylScal4_psi4_calc_4th",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psi4_calc_4th",
                           "WeylScal4_psi4_calc_4th_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           2, /* Number of WRITES clauses     */
                           15, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi4i(Interior)",
                           "WeylScal4::Psi4r(Interior)",
                           "admbase::kxx(Everywhere)",
                           "admbase::kxy(Everywhere)",
                           "admbase::kxz(Everywhere)",
                           "admbase::kyy(Everywhere)",
                           "admbase::kyz(Everywhere)",
                           "admbase::kzz(Everywhere)",
                           "admbase::gxx(Everywhere)",
                           "admbase::gxy(Everywhere)",
                           "admbase::gxz(Everywhere)",
                           "admbase::gyy(Everywhere)",
                           "admbase::gyz(Everywhere)",
                           "admbase::gzz(Everywhere)",
                           "grid::x(Everywhere)",
                           "grid::y(Everywhere)",
                           "grid::z(Everywhere)",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psi4_calc_4th_SelectBCs,
                           "WeylScal4_psi4_calc_4th_SelectBCs",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psi4_calc_4th_SelectBCs",
                           "WeylScal4_psi4_calc_4th_bc_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           2, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi4i_group",
                           "WeylScal4::Psi4r_group",
                           "level",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("ApplyBCs",
"WeylScal4_psi4_calc_4th_ApplyBCs",
                        "WeylScal4",
                        "WeylScal4",
                        "Apply BCs for groups set in WeylScal4_psi4_calc_4th",
                        "WeylScal4_psi4_calc_4th_bc_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psi4_calc_4th_SelectBCs");
  }
if (CCTK_EQUALS(calc_scalars, "psi4"))
{
  if (CCTK_EQUALS(fd_order, "4th"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psi4_calc_4th_bc_group",
"WeylScal4_psi4_calc_4th_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psi4_calc_4th",
                        "WeylScal4_psi4_calc_4th_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psi4_calc_4th");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psi4"))
{
  if (CCTK_EQUALS(fd_order, "4th"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psi4_calc_4th_bc_group",
"WeylScal4_psi4_calc_4th_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psi4_calc_4th",
                        "MoL_PseudoEvolutionBoundaries",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "MoL_PostStep");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psis"))
{
  if (CCTK_EQUALS(fd_order, "Nth"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psis_calc_Nth_group",
"WeylScal4_psis_calc_Nth_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psis_calc_Nth",
                        "MoL_PseudoEvolution",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "ADMBase_SetADMVars");
  }
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psis_calc_Nth,
                           "WeylScal4_psis_calc_Nth",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psis_calc_Nth",
                           "WeylScal4_psis_calc_Nth_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           10, /* Number of WRITES clauses     */
                           15, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi0i(Interior)",
                           "WeylScal4::Psi0r(Interior)",
                           "WeylScal4::Psi1i(Interior)",
                           "WeylScal4::Psi1r(Interior)",
                           "WeylScal4::Psi2i(Interior)",
                           "WeylScal4::Psi2r(Interior)",
                           "WeylScal4::Psi3i(Interior)",
                           "WeylScal4::Psi3r(Interior)",
                           "WeylScal4::Psi4i(Interior)",
                           "WeylScal4::Psi4r(Interior)",
                           "admbase::kxx(Everywhere)",
                           "admbase::kxy(Everywhere)",
                           "admbase::kxz(Everywhere)",
                           "admbase::kyy(Everywhere)",
                           "admbase::kyz(Everywhere)",
                           "admbase::kzz(Everywhere)",
                           "admbase::gxx(Everywhere)",
                           "admbase::gxy(Everywhere)",
                           "admbase::gxz(Everywhere)",
                           "admbase::gyy(Everywhere)",
                           "admbase::gyz(Everywhere)",
                           "admbase::gzz(Everywhere)",
                           "grid::x(Everywhere)",
                           "grid::y(Everywhere)",
                           "grid::z(Everywhere)",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psis_calc_Nth_SelectBCs,
                           "WeylScal4_psis_calc_Nth_SelectBCs",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psis_calc_Nth_SelectBCs",
                           "WeylScal4_psis_calc_Nth_bc_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           10, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi0i_group",
                           "WeylScal4::Psi0r_group",
                           "WeylScal4::Psi1i_group",
                           "WeylScal4::Psi1r_group",
                           "WeylScal4::Psi2i_group",
                           "WeylScal4::Psi2r_group",
                           "WeylScal4::Psi3i_group",
                           "WeylScal4::Psi3r_group",
                           "WeylScal4::Psi4i_group",
                           "WeylScal4::Psi4r_group",
                           "level",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("ApplyBCs",
"WeylScal4_psis_calc_Nth_ApplyBCs",
                        "WeylScal4",
                        "WeylScal4",
                        "Apply BCs for groups set in WeylScal4_psis_calc_Nth",
                        "WeylScal4_psis_calc_Nth_bc_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psis_calc_Nth_SelectBCs");
  }
if (CCTK_EQUALS(calc_scalars, "psis"))
{
  if (CCTK_EQUALS(fd_order, "Nth"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psis_calc_Nth_bc_group",
"WeylScal4_psis_calc_Nth_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psis_calc_Nth",
                        "WeylScal4_psis_calc_Nth_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psis_calc_Nth");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psis"))
{
  if (CCTK_EQUALS(fd_order, "Nth"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psis_calc_Nth_bc_group",
"WeylScal4_psis_calc_Nth_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psis_calc_Nth",
                        "MoL_PseudoEvolutionBoundaries",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "MoL_PostStep");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psis"))
{
  if (CCTK_EQUALS(fd_order, "2nd"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psis_calc_2nd_group",
"WeylScal4_psis_calc_2nd_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psis_calc_2nd",
                        "MoL_PseudoEvolution",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "ADMBase_SetADMVars");
  }
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psis_calc_2nd,
                           "WeylScal4_psis_calc_2nd",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psis_calc_2nd",
                           "WeylScal4_psis_calc_2nd_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           10, /* Number of WRITES clauses     */
                           15, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi0i(Interior)",
                           "WeylScal4::Psi0r(Interior)",
                           "WeylScal4::Psi1i(Interior)",
                           "WeylScal4::Psi1r(Interior)",
                           "WeylScal4::Psi2i(Interior)",
                           "WeylScal4::Psi2r(Interior)",
                           "WeylScal4::Psi3i(Interior)",
                           "WeylScal4::Psi3r(Interior)",
                           "WeylScal4::Psi4i(Interior)",
                           "WeylScal4::Psi4r(Interior)",
                           "admbase::kxx(Everywhere)",
                           "admbase::kxy(Everywhere)",
                           "admbase::kxz(Everywhere)",
                           "admbase::kyy(Everywhere)",
                           "admbase::kyz(Everywhere)",
                           "admbase::kzz(Everywhere)",
                           "admbase::gxx(Everywhere)",
                           "admbase::gxy(Everywhere)",
                           "admbase::gxz(Everywhere)",
                           "admbase::gyy(Everywhere)",
                           "admbase::gyz(Everywhere)",
                           "admbase::gzz(Everywhere)",
                           "grid::x(Everywhere)",
                           "grid::y(Everywhere)",
                           "grid::z(Everywhere)",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psis_calc_2nd_SelectBCs,
                           "WeylScal4_psis_calc_2nd_SelectBCs",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psis_calc_2nd_SelectBCs",
                           "WeylScal4_psis_calc_2nd_bc_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           10, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi0i_group",
                           "WeylScal4::Psi0r_group",
                           "WeylScal4::Psi1i_group",
                           "WeylScal4::Psi1r_group",
                           "WeylScal4::Psi2i_group",
                           "WeylScal4::Psi2r_group",
                           "WeylScal4::Psi3i_group",
                           "WeylScal4::Psi3r_group",
                           "WeylScal4::Psi4i_group",
                           "WeylScal4::Psi4r_group",
                           "level",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("ApplyBCs",
"WeylScal4_psis_calc_2nd_ApplyBCs",
                        "WeylScal4",
                        "WeylScal4",
                        "Apply BCs for groups set in WeylScal4_psis_calc_2nd",
                        "WeylScal4_psis_calc_2nd_bc_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psis_calc_2nd_SelectBCs");
  }
if (CCTK_EQUALS(calc_scalars, "psis"))
{
  if (CCTK_EQUALS(fd_order, "2nd"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psis_calc_2nd_bc_group",
"WeylScal4_psis_calc_2nd_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psis_calc_2nd",
                        "WeylScal4_psis_calc_2nd_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psis_calc_2nd");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psis"))
{
  if (CCTK_EQUALS(fd_order, "2nd"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psis_calc_2nd_bc_group",
"WeylScal4_psis_calc_2nd_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psis_calc_2nd",
                        "MoL_PseudoEvolutionBoundaries",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "MoL_PostStep");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psis"))
{
  if (CCTK_EQUALS(fd_order, "4th"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psis_calc_4th_group",
"WeylScal4_psis_calc_4th_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psis_calc_4th",
                        "MoL_PseudoEvolution",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "ADMBase_SetADMVars");
  }
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psis_calc_4th,
                           "WeylScal4_psis_calc_4th",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psis_calc_4th",
                           "WeylScal4_psis_calc_4th_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           10, /* Number of WRITES clauses     */
                           15, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi0i(Interior)",
                           "WeylScal4::Psi0r(Interior)",
                           "WeylScal4::Psi1i(Interior)",
                           "WeylScal4::Psi1r(Interior)",
                           "WeylScal4::Psi2i(Interior)",
                           "WeylScal4::Psi2r(Interior)",
                           "WeylScal4::Psi3i(Interior)",
                           "WeylScal4::Psi3r(Interior)",
                           "WeylScal4::Psi4i(Interior)",
                           "WeylScal4::Psi4r(Interior)",
                           "admbase::kxx(Everywhere)",
                           "admbase::kxy(Everywhere)",
                           "admbase::kxz(Everywhere)",
                           "admbase::kyy(Everywhere)",
                           "admbase::kyz(Everywhere)",
                           "admbase::kzz(Everywhere)",
                           "admbase::gxx(Everywhere)",
                           "admbase::gxy(Everywhere)",
                           "admbase::gxz(Everywhere)",
                           "admbase::gyy(Everywhere)",
                           "admbase::gyz(Everywhere)",
                           "admbase::gzz(Everywhere)",
                           "grid::x(Everywhere)",
                           "grid::y(Everywhere)",
                           "grid::z(Everywhere)",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_psis_calc_4th_SelectBCs,
                           "WeylScal4_psis_calc_4th_SelectBCs",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_psis_calc_4th_SelectBCs",
                           "WeylScal4_psis_calc_4th_bc_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           10, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::Psi0i_group",
                           "WeylScal4::Psi0r_group",
                           "WeylScal4::Psi1i_group",
                           "WeylScal4::Psi1r_group",
                           "WeylScal4::Psi2i_group",
                           "WeylScal4::Psi2r_group",
                           "WeylScal4::Psi3i_group",
                           "WeylScal4::Psi3r_group",
                           "WeylScal4::Psi4i_group",
                           "WeylScal4::Psi4r_group",
                           "level",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("ApplyBCs",
"WeylScal4_psis_calc_4th_ApplyBCs",
                        "WeylScal4",
                        "WeylScal4",
                        "Apply BCs for groups set in WeylScal4_psis_calc_4th",
                        "WeylScal4_psis_calc_4th_bc_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psis_calc_4th_SelectBCs");
  }
if (CCTK_EQUALS(calc_scalars, "psis"))
{
  if (CCTK_EQUALS(fd_order, "4th"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psis_calc_4th_bc_group",
"WeylScal4_psis_calc_4th_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psis_calc_4th",
                        "WeylScal4_psis_calc_4th_group",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psis_calc_4th");
  }
  }
}
if (CCTK_EQUALS(calc_scalars, "psis"))
{
  if (CCTK_EQUALS(fd_order, "4th"))
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_psis_calc_4th_bc_group",
"WeylScal4_psis_calc_4th_bc_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_psis_calc_4th",
                        "MoL_PseudoEvolutionBoundaries",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "MoL_PostStep");
  }
  }
}
if (CCTK_EQUALS(calc_invariants, "always"))
{
  if (CCTK_EQUALS(calc_scalars, "psis"))
  {
    if (CCTK_EQUALS(fd_order, "Nth"))
    {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_invars_calc_Nth_group",
"WeylScal4_invars_calc_Nth_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_invars_calc_Nth",
                        "MoL_PseudoEvolution",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psis_calc_Nth_group");
  }
    }
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_invars_calc_Nth,
                           "WeylScal4_invars_calc_Nth",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_invars_calc_Nth",
                           "WeylScal4_invars_calc_Nth_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           8, /* Number of WRITES clauses     */
                           10, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::curvIi(Interior)",
                           "WeylScal4::curvIr(Interior)",
                           "WeylScal4::curvJ1(Interior)",
                           "WeylScal4::curvJ2(Interior)",
                           "WeylScal4::curvJ3(Interior)",
                           "WeylScal4::curvJ4(Interior)",
                           "WeylScal4::curvJi(Interior)",
                           "WeylScal4::curvJr(Interior)",
                           "WeylScal4::Psi0i(Everywhere)",
                           "WeylScal4::Psi0r(Everywhere)",
                           "WeylScal4::Psi1i(Everywhere)",
                           "WeylScal4::Psi1r(Everywhere)",
                           "WeylScal4::Psi2i(Everywhere)",
                           "WeylScal4::Psi2r(Everywhere)",
                           "WeylScal4::Psi3i(Everywhere)",
                           "WeylScal4::Psi3r(Everywhere)",
                           "WeylScal4::Psi4i(Everywhere)",
                           "WeylScal4::Psi4r(Everywhere)",
                           "");
  }
if (CCTK_EQUALS(calc_invariants, "always"))
{
  if (CCTK_EQUALS(calc_scalars, "psis"))
  {
    if (CCTK_EQUALS(fd_order, "2nd"))
    {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_invars_calc_2nd_group",
"WeylScal4_invars_calc_2nd_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_invars_calc_2nd",
                        "MoL_PseudoEvolution",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psis_calc_2nd_group");
  }
    }
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_invars_calc_2nd,
                           "WeylScal4_invars_calc_2nd",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_invars_calc_2nd",
                           "WeylScal4_invars_calc_2nd_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           8, /* Number of WRITES clauses     */
                           10, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::curvIi(Interior)",
                           "WeylScal4::curvIr(Interior)",
                           "WeylScal4::curvJ1(Interior)",
                           "WeylScal4::curvJ2(Interior)",
                           "WeylScal4::curvJ3(Interior)",
                           "WeylScal4::curvJ4(Interior)",
                           "WeylScal4::curvJi(Interior)",
                           "WeylScal4::curvJr(Interior)",
                           "WeylScal4::Psi0i(Everywhere)",
                           "WeylScal4::Psi0r(Everywhere)",
                           "WeylScal4::Psi1i(Everywhere)",
                           "WeylScal4::Psi1r(Everywhere)",
                           "WeylScal4::Psi2i(Everywhere)",
                           "WeylScal4::Psi2r(Everywhere)",
                           "WeylScal4::Psi3i(Everywhere)",
                           "WeylScal4::Psi3r(Everywhere)",
                           "WeylScal4::Psi4i(Everywhere)",
                           "WeylScal4::Psi4r(Everywhere)",
                           "");
  }
if (CCTK_EQUALS(calc_invariants, "always"))
{
  if (CCTK_EQUALS(calc_scalars, "psis"))
  {
    if (CCTK_EQUALS(fd_order, "4th"))
    {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("WeylScal4_invars_calc_4th_group",
"WeylScal4_invars_calc_4th_group",
                        "WeylScal4",
                        "WeylScal4",
                        "WeylScal4_invars_calc_4th",
                        "MoL_PseudoEvolution",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_psis_calc_4th_group");
  }
    }
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_invars_calc_4th,
                           "WeylScal4_invars_calc_4th",
                           "WeylScal4",
                           "WeylScal4",
                           "WeylScal4_invars_calc_4th",
                           "WeylScal4_invars_calc_4th_group",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           8, /* Number of WRITES clauses     */
                           10, /* Number of READS clauses      */
                           0, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "WeylScal4::curvIi(Interior)",
                           "WeylScal4::curvIr(Interior)",
                           "WeylScal4::curvJ1(Interior)",
                           "WeylScal4::curvJ2(Interior)",
                           "WeylScal4::curvJ3(Interior)",
                           "WeylScal4::curvJ4(Interior)",
                           "WeylScal4::curvJi(Interior)",
                           "WeylScal4::curvJr(Interior)",
                           "WeylScal4::Psi0i(Everywhere)",
                           "WeylScal4::Psi0r(Everywhere)",
                           "WeylScal4::Psi1i(Everywhere)",
                           "WeylScal4::Psi1r(Everywhere)",
                           "WeylScal4::Psi2i(Everywhere)",
                           "WeylScal4::Psi2r(Everywhere)",
                           "WeylScal4::Psi3i(Everywhere)",
                           "WeylScal4::Psi3r(Everywhere)",
                           "WeylScal4::Psi4i(Everywhere)",
                           "WeylScal4::Psi4r(Everywhere)",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_SelectBoundConds,
                           "WeylScal4_SelectBoundConds",
                           "WeylScal4",
                           "WeylScal4",
                           "select boundary conditions",
                           "MoL_PostStep",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "level",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_CheckBoundaries,
                           "WeylScal4_CheckBoundaries",
                           "WeylScal4",
                           "WeylScal4",
                           "check boundaries treatment",
                           "CCTK_BASEGRID",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "meta",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)WeylScal4_RegisterVars,
                           "WeylScal4_RegisterVars",
                           "WeylScal4",
                           "WeylScal4",
                           "Register Variables for MoL",
                           "MoL_Register",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0, /* Number of SYNC     groups    */
                           0, /* Number of WRITES clauses     */
                           0, /* Number of READS clauses      */
                           1, /* Number of Options            */
                           0, /* Number of BEFORE   routines  */
                           0, /* Number of AFTER    routines  */
                           0, /* Number of WHILE    variables */
                           0, /* Number of IF       variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "meta",
                           "");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("ApplyBCs",
"WeylScal4_ApplyBCs",
                        "WeylScal4",
                        "WeylScal4",
                        "Apply boundary conditions controlled by thorn Boundary",
                        "MoL_PostStep",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0, /* Number of SYNC     groups    */
                        0, /* Number of WRITES clauses     */
                        0, /* Number of READS clauses      */
                        0, /* Number of Options            */
                        0, /* Number of BEFORE   routines  */
                        1, /* Number of AFTER    routines  */
                        0, /* Number of WHILE    variables */
                        0, /* Number of IF       variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "",
                        "WeylScal4_SelectBoundConds");
  }
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_WeylScal4
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn WeylScal4
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_WeylScal4(void);
int CCTKi_BindingsParameterRecovery_WeylScal4(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

