/*@@
   @header  RotatingDBHIVP/CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn RotatingDBHIVP
   @enddesc
 @@*/


#ifndef _ROTATINGDBHIVP_PARAMETERS_H_
#define _ROTATINGDBHIVP_PARAMETERS_H_ 1

#include "CParameterStructNames.h"
#include "ParameterCGlobal.h"
#include "ParameterCPrivateROTATINGDBHIVP.h"
#include "ParameterCRestrictedADMBASE.h"
#include "ParameterCRestrictedSTATICCONFORMAL.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_PRIVATE_ROTATINGDBHIVP_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (const char * const, metric_type, CCTK_PARAMETER__ADMBase__metric_type); \
  CCTK_DECLARE_INIT (const char * const, initial_lapse, CCTK_PARAMETER__ADMBase__initial_lapse); \
  CCTK_DECLARE_INIT (const char * const, initial_data, CCTK_PARAMETER__ADMBase__initial_data); \
  CCTK_DECLARE_INIT (const char * const, conformal_storage, CCTK_PARAMETER__StaticConformal__conformal_storage); \

#ifndef CCTK_PARAMETER__ADMBase__metric_type
#  define CCTK_PARAMETER__ADMBase__metric_type RESTRICTED_ADMBASE_STRUCT.metric_type
#endif
#ifndef CCTK_PARAMETER__ADMBase__initial_lapse
#  define CCTK_PARAMETER__ADMBase__initial_lapse RESTRICTED_ADMBASE_STRUCT.initial_lapse
#endif
#ifndef CCTK_PARAMETER__ADMBase__initial_data
#  define CCTK_PARAMETER__ADMBase__initial_data RESTRICTED_ADMBASE_STRUCT.initial_data
#endif
#ifndef CCTK_PARAMETER__StaticConformal__conformal_storage
#  define CCTK_PARAMETER__StaticConformal__conformal_storage RESTRICTED_STATICCONFORMAL_STRUCT.conformal_storage
#endif

#endif  /* _ROTATINGDBHIVP_PARAMETERS_H_ */

