#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_INT,Convert_to_HydroBase_every,)&&\
COMMON /Convert_to_HydroBasepriv/Convert_to_HydroBase_every&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH8,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH10,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH11,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH12,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH13,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH14,)&&\
CCTK_DECLARE(CCTK_INT,lapse_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,metric_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,shift_timelevels,)&&\
COMMON /ADMBASErest/CCTKH0, CCTKH1, CCTKH2, CCTKH3, CCTKH4, CCTKH5, CCTKH6, CCTKH7, CCTKH8, CCTKH9, CCTKH10, CCTKH11, CCTKH12, CCTKH13, CCTKH14, lapse_timelevels, metric_timelevels, shift_timelevels&&\
CCTK_DECLARE(CCTK_STRING,CCTKH15,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH16,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH17,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH18,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH19,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH21,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH22,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH23,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH24,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH25,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH26,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH27,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH28,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH29,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH30,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH20,)&&\
CCTK_DECLARE(CCTK_INT,timelevels,)&&\
COMMON /HYDROBASErest/CCTKH15, CCTKH16, CCTKH17, CCTKH18, CCTKH19, CCTKH21, CCTKH22, CCTKH23, CCTKH24, CCTKH25, CCTKH26, CCTKH27, CCTKH28, CCTKH29, CCTKH30, CCTKH20, timelevels&&\
CCTK_DECLARE(CCTK_REAL,CCTKH32,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH34,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH36,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH37,)&&\
CCTK_DECLARE(CCTK_REAL,gamma_th,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH41,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH42,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH43,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH31,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH35,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH38,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH33,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH39,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH40,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH44,)&&\
COMMON /ILLINOISGRMHDrest/CCTKH32, CCTKH34, CCTKH36, CCTKH37, gamma_th, CCTKH41, CCTKH42, CCTKH43, CCTKH31, CCTKH35, CCTKH38, CCTKH33, CCTKH39, CCTKH40, CCTKH44&&\

