#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_STRING,initial_data,)&&\
COMMON /idscalarwaverest/initial_data&&\
CCTK_DECLARE(CCTK_REAL,amplitude,)&&\
CCTK_DECLARE(CCTK_REAL,kx,)&&\
CCTK_DECLARE(CCTK_REAL,ky,)&&\
CCTK_DECLARE(CCTK_REAL,kz,)&&\
CCTK_DECLARE(CCTK_REAL,radius,)&&\
CCTK_DECLARE(CCTK_REAL,sigma,)&&\
COMMON /IDScalarWavepriv/amplitude, kx, ky, kz, radius, sigma&&\
CCTK_DECLARE(CCTK_REAL,CCTKH2,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH3,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH4,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH5,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH14,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH15,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH16,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH17,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH18,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH19,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH20,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH21,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,type,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH8,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH9,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH11,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH12,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH13,)&&\
COMMON /GRIDrest/CCTKH2, CCTKH3, CCTKH4, CCTKH5, CCTKH14, CCTKH15, CCTKH16, CCTKH17, CCTKH18, CCTKH19, CCTKH20, CCTKH21, CCTKH0, CCTKH1, CCTKH6, CCTKH7, type, CCTKH8, CCTKH9, CCTKH10, CCTKH11, CCTKH12, CCTKH13&&\

