/*@@
   @file    FleshInfo_Parameters.c
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Creates/extends parameters for this thorn
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "cctk_Config.h"
#include "cctk_Constants.h"
#include "ParameterBindings.h"
#include "CParameterStructNames.h"

/* structure containing all private parameters of thorn FleshInfo */
struct
{
  int dummy_parameter;
} PRIVATE_FLESHINFO_STRUCT;


/* structure containing all restricted parameters of thorn FleshInfo */
struct
{
  int dummy_parameter;
} RESTRICTED_FLESHINFO_STRUCT;


int CCTKi_BindingsCreateFleshInfoParameters(void);
int CCTKi_BindingsCreateFleshInfoParameters(void)
{
  return 0;
}

int CCTKi_BindingsFleshInfoParameterExtensions(void);
int CCTKi_BindingsFleshInfoParameterExtensions(void)
{
  return 0;
}

