/*@@
   @file    IDAnalyticBH_Parameters.c
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Creates/extends parameters for this thorn
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "cctk_Config.h"
#include "cctk_Constants.h"
#include "ParameterBindings.h"
#include "CParameterStructNames.h"
#include "ParameterCRestrictedADMBASE.h"
#include "ParameterCRestrictedSTATICCONFORMAL.h"

/* structure containing all private parameters of thorn IDAnalyticBH */
struct
{
  CCTK_REAL a_Kerr;
  CCTK_REAL bl_M_1;
  CCTK_REAL bl_M_2;
  CCTK_REAL bl_M_3;
  CCTK_REAL bl_M_4;
  CCTK_REAL bl_x0_1;
  CCTK_REAL bl_x0_2;
  CCTK_REAL bl_x0_3;
  CCTK_REAL bl_x0_4;
  CCTK_REAL bl_y0_1;
  CCTK_REAL bl_y0_2;
  CCTK_REAL bl_y0_3;
  CCTK_REAL bl_y0_4;
  CCTK_REAL bl_z0_1;
  CCTK_REAL bl_z0_2;
  CCTK_REAL bl_z0_3;
  CCTK_REAL bl_z0_4;
  CCTK_REAL epsilon;
  CCTK_REAL mass;
  CCTK_REAL mu;
  CCTK_INT bl_nbh;
  CCTK_INT misner_nbh;
  CCTK_INT nmax;
} PRIVATE_IDANALYTICBH_STRUCT;


/* structure containing all restricted parameters of thorn IDAnalyticBH */
struct
{
  int dummy_parameter;
} RESTRICTED_IDANALYTICBH_STRUCT;


int CCTKi_BindingsCreateIDAnalyticBHParameters(void);
int CCTKi_BindingsCreateIDAnalyticBHParameters(void)
{
  CCTKi_ParameterCreate("a_Kerr",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Angular momentum parameter of black hole",
                        "0.1",
                        &(PRIVATE_IDANALYTICBH_STRUCT.a_Kerr),
                        0,
                        NULL,
                        1,
                        "-1:1", "Between +1 and -1");

  CCTKi_ParameterCreate("bl_M_1",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Mass of 1st BL hole",
                        "1.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_M_1),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_M_2",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Mass of 2nd BL hole",
                        "1.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_M_2),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_M_3",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Mass of 3rd BL hole",
                        "1.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_M_3),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_M_4",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Mass of 4th BL hole",
                        "1.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_M_4),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_nbh",
                        "IDAnalyticBH",
                        "INT",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Number of Brill Lindquist black holes",
                        "1",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_nbh),
                        0,
                        NULL,
                        1,
                        "1:4", "Between one and four holes implemented");

  CCTKi_ParameterCreate("bl_x0_1",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "x-position of 1st BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_x0_1),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_x0_2",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "x-position of 2nd BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_x0_2),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_x0_3",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "x-position of 3nd BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_x0_3),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_x0_4",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "x-position of 4th BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_x0_4),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_y0_1",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "y-position of 1st BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_y0_1),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_y0_2",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "y-position of 2nd BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_y0_2),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_y0_3",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "y-position of 3nd BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_y0_3),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_y0_4",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "y-position of 4th BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_y0_4),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_z0_1",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "z-position of 1st BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_z0_1),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_z0_2",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "z-position of 2nd BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_z0_2),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_z0_3",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "z-position of 3nd BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_z0_3),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("bl_z0_4",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "z-position of 4th BL hole",
                        "0.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.bl_z0_4),
                        0,
                        NULL,
                        1,
                        ":", "Anything");

  CCTKi_ParameterCreate("epsilon",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Fudge factor",
                        "1.e-16",
                        &(PRIVATE_IDANALYTICBH_STRUCT.epsilon),
                        0,
                        NULL,
                        1,
                        "0.0:*", "");

  CCTKi_ParameterCreate("mass",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Mass of black hole",
                        "2.0",
                        &(PRIVATE_IDANALYTICBH_STRUCT.mass),
                        0,
                        NULL,
                        1,
                        ":", "Not sure if it can be negative or not");

  CCTKi_ParameterCreate("misner_nbh",
                        "IDAnalyticBH",
                        "INT",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Number of Misner black holes",
                        "1",
                        &(PRIVATE_IDANALYTICBH_STRUCT.misner_nbh),
                        0,
                        NULL,
                        1,
                        "1:10", "Not more than 10");

  CCTKi_ParameterCreate("mu",
                        "IDAnalyticBH",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Misner mu value",
                        "1.2",
                        &(PRIVATE_IDANALYTICBH_STRUCT.mu),
                        0,
                        NULL,
                        1,
                        "0:", "Non-negative");

  CCTKi_ParameterCreate("nmax",
                        "IDAnalyticBH",
                        "INT",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Number of terms to include for Misner series",
                        "30",
                        &(PRIVATE_IDANALYTICBH_STRUCT.nmax),
                        0,
                        NULL,
                        1,
                        "0:", "Non-negative");

  return 0;
}

int CCTKi_BindingsIDAnalyticBHParameterExtensions(void);
int CCTKi_BindingsIDAnalyticBHParameterExtensions(void)
{
  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_data",
                          "IDAnalyticBH",
                          "schwarzschild",
                          "One Schwarzschild black hole");

  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_data",
                          "IDAnalyticBH",
                          "bl_bh",
                          "Brill Lindquist black holes");

  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_data",
                          "IDAnalyticBH",
                          "misner_bh",
                          "Misner black holes");

  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_data",
                          "IDAnalyticBH",
                          "multiple_misner_bh",
                          "Multiple Misner black holes");

  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_data",
                          "IDAnalyticBH",
                          "kerr",
                          "One Kerr black hole"	);

  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_lapse",
                          "IDAnalyticBH",
                          "schwarzschild",
                          "Set lapse to Schwarzschild");

  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_lapse",
                          "IDAnalyticBH",
                          "schwarz",
                          "Set lapse to Schwarzschild");

  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_lapse",
                          "IDAnalyticBH",
                          "cadez",
                          "Set lapse to Misner");

  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_lapse",
                          "IDAnalyticBH",
                          "kerr",
                          "Set lapse to Kerr");

  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_shift",
                          "IDAnalyticBH",
                          "kerr",
                          "Set shift to Kerr");

  return 0;
}

