/*@@
   @file    IDConstraintViolate_Parameters.c
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Creates/extends parameters for this thorn
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "cctk_Config.h"
#include "cctk_Constants.h"
#include "ParameterBindings.h"
#include "CParameterStructNames.h"
#include "ParameterCRestrictedADMBASE.h"

/* structure containing all private parameters of thorn IDConstraintViolate */
struct
{
  CCTK_REAL amplitude;
  CCTK_REAL radius;
  CCTK_REAL sigma;
} PRIVATE_IDCONSTRAINTVIOLATE_STRUCT;


/* structure containing all restricted parameters of thorn IDConstraintViolate */
struct
{
  int dummy_parameter;
} RESTRICTED_IDCONSTRAINTVIOLATE_STRUCT;


int CCTKi_BindingsCreateIDConstraintViolateParameters(void);
int CCTKi_BindingsCreateIDConstraintViolateParameters(void)
{
  CCTKi_ParameterCreate("amplitude",
                        "IDConstraintViolate",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "The amplitude of the waves",
                        "0.001",
                        &(PRIVATE_IDCONSTRAINTVIOLATE_STRUCT.amplitude),
                        0,
                        NULL,
                        1,
                        "*:*", "No restriction");

  CCTKi_ParameterCreate("radius",
                        "IDConstraintViolate",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "The radial position of the Gaussian wave",
                        "0.0",
                        &(PRIVATE_IDCONSTRAINTVIOLATE_STRUCT.radius),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("sigma",
                        "IDConstraintViolate",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "The sigma for the Gaussian wave",
                        "0.1",
                        &(PRIVATE_IDCONSTRAINTVIOLATE_STRUCT.sigma),
                        0,
                        NULL,
                        1,
                        "(0:*", "Positive");

  return 0;
}

int CCTKi_BindingsIDConstraintViolateParameterExtensions(void);
int CCTKi_BindingsIDConstraintViolateParameterExtensions(void)
{
  CCTKi_ParameterAddRange("ADMBASE",
                          "initial_data",
                          "IDConstraintViolate",
                          "constraint violating gaussian",
                          "Constraint violating Gaussian");

  return 0;
}

