/*@@
   @file    ReductionTest3_Parameters.c
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Creates/extends parameters for this thorn
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "cctk_Config.h"
#include "cctk_Constants.h"
#include "ParameterBindings.h"
#include "CParameterStructNames.h"
#include "ParameterCRestrictedGRID.h"

/* structure containing all private parameters of thorn ReductionTest3 */
struct
{
  int dummy_parameter;
} PRIVATE_REDUCTIONTEST3_STRUCT;


/* structure containing all restricted parameters of thorn ReductionTest3 */
struct
{
  int dummy_parameter;
} RESTRICTED_REDUCTIONTEST3_STRUCT;


int CCTKi_BindingsCreateReductionTest3Parameters(void);
int CCTKi_BindingsCreateReductionTest3Parameters(void)
{
  return 0;
}

int CCTKi_BindingsReductionTest3ParameterExtensions(void);
int CCTKi_BindingsReductionTest3ParameterExtensions(void)
{
  return 0;
}

