/*@@
   @file    TestMath_Parameters.c
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Creates/extends parameters for this thorn
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "cctk_Config.h"
#include "cctk_Constants.h"
#include "ParameterBindings.h"
#include "CParameterStructNames.h"

/* structure containing all private parameters of thorn TestMath */
struct
{
  int dummy_parameter;
} PRIVATE_TESTMATH_STRUCT;


/* structure containing all restricted parameters of thorn TestMath */
struct
{
  int dummy_parameter;
} RESTRICTED_TESTMATH_STRUCT;


int CCTKi_BindingsCreateTestMathParameters(void);
int CCTKi_BindingsCreateTestMathParameters(void)
{
  return 0;
}

int CCTKi_BindingsTestMathParameterExtensions(void);
int CCTKi_BindingsTestMathParameterExtensions(void)
{
  return 0;
}

