/*@@
   @file    TestLoopControl_Parameters.c
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Creates/extends parameters for this thorn
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "cctk_Config.h"
#include "cctk_Constants.h"
#include "ParameterBindings.h"
#include "CParameterStructNames.h"

/* structure containing all private parameters of thorn TestLoopControl */
struct
{
  int dummy_parameter;
} PRIVATE_TESTLOOPCONTROL_STRUCT;


/* structure containing all restricted parameters of thorn TestLoopControl */
struct
{
  int dummy_parameter;
} RESTRICTED_TESTLOOPCONTROL_STRUCT;


int CCTKi_BindingsCreateTestLoopControlParameters(void);
int CCTKi_BindingsCreateTestLoopControlParameters(void)
{
  return 0;
}

int CCTKi_BindingsTestLoopControlParameterExtensions(void);
int CCTKi_BindingsTestLoopControlParameterExtensions(void)
{
  return 0;
}

