#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,Alvi__mass1,)&&\
CCTK_DECLARE(CCTK_REAL,Alvi__mass2,)&&\
CCTK_DECLARE(CCTK_REAL,Alvi__separation,)&&\
CCTK_DECLARE(CCTK_REAL,Bertotti__Lambda,)&&\
CCTK_DECLARE(CCTK_REAL,Bianchi_I__scale,)&&\
CCTK_DECLARE(CCTK_REAL,Goedel__scale,)&&\
CCTK_DECLARE(CCTK_REAL,Gowdy_wave__amplitude,)&&\
CCTK_DECLARE(CCTK_REAL,Kasner_generalized__p1,)&&\
CCTK_DECLARE(CCTK_REAL,Kasner_generalized__p2,)&&\
CCTK_DECLARE(CCTK_REAL,Kasner_like__q,)&&\
CCTK_DECLARE(CCTK_REAL,Kerr_BoyerLindquist__mass,)&&\
CCTK_DECLARE(CCTK_REAL,Kerr_BoyerLindquist__spin,)&&\
CCTK_DECLARE(CCTK_REAL,Kerr_KerrSchild__boost_v,)&&\
CCTK_DECLARE(CCTK_REAL,Kerr_KerrSchild__epsilon,)&&\
CCTK_DECLARE(CCTK_REAL,Kerr_KerrSchild__mass,)&&\
CCTK_DECLARE(CCTK_REAL,Kerr_KerrSchild__spin,)&&\
CCTK_DECLARE(CCTK_REAL,Kerr_KerrSchild__t,)&&\
CCTK_DECLARE(CCTK_REAL,Kerr_KerrSchild__x,)&&\
CCTK_DECLARE(CCTK_REAL,Kerr_KerrSchild__y,)&&\
CCTK_DECLARE(CCTK_REAL,Kerr_KerrSchild__z,)&&\
CCTK_DECLARE(CCTK_REAL,Lemaitre__Lambda,)&&\
CCTK_DECLARE(CCTK_REAL,Lemaitre__R0,)&&\
CCTK_DECLARE(CCTK_REAL,Lemaitre__epsilon0,)&&\
CCTK_DECLARE(CCTK_REAL,Lemaitre__kappa,)&&\
CCTK_DECLARE(CCTK_REAL,Minkowski_conf_wave__amplitude,)&&\
CCTK_DECLARE(CCTK_REAL,Minkowski_conf_wave__wavelength,)&&\
CCTK_DECLARE(CCTK_REAL,Minkowski_funny__amplitude,)&&\
CCTK_DECLARE(CCTK_REAL,Minkowski_funny__sigma,)&&\
CCTK_DECLARE(CCTK_REAL,Minkowski_gauge_wave__amplitude,)&&\
CCTK_DECLARE(CCTK_REAL,Minkowski_gauge_wave__lambda,)&&\
CCTK_DECLARE(CCTK_REAL,Minkowski_gauge_wave__omega,)&&\
CCTK_DECLARE(CCTK_REAL,Minkowski_gauge_wave__phase,)&&\
CCTK_DECLARE(CCTK_REAL,Minkowski_shift__amplitude,)&&\
CCTK_DECLARE(CCTK_REAL,Minkowski_shift__sigma,)&&\
CCTK_DECLARE(CCTK_REAL,Schwarzschild_BL__epsilon,)&&\
CCTK_DECLARE(CCTK_REAL,Schwarzschild_BL__mass,)&&\
CCTK_DECLARE(CCTK_REAL,Schwarzschild_EF__epsilon,)&&\
CCTK_DECLARE(CCTK_REAL,Schwarzschild_EF__mass,)&&\
CCTK_DECLARE(CCTK_REAL,Schwarzschild_Lemaitre__Lambda,)&&\
CCTK_DECLARE(CCTK_REAL,Schwarzschild_Lemaitre__mass,)&&\
CCTK_DECLARE(CCTK_REAL,Schwarzschild_Novikov__epsilon,)&&\
CCTK_DECLARE(CCTK_REAL,Schwarzschild_Novikov__mass,)&&\
CCTK_DECLARE(CCTK_REAL,Schwarzschild_PG__epsilon,)&&\
CCTK_DECLARE(CCTK_REAL,Schwarzschild_PG__mass,)&&\
CCTK_DECLARE(CCTK_REAL,Thorne_fakebinary__Omega0,)&&\
CCTK_DECLARE(CCTK_REAL,Thorne_fakebinary__epsilon,)&&\
CCTK_DECLARE(CCTK_REAL,Thorne_fakebinary__mass,)&&\
CCTK_DECLARE(CCTK_REAL,Thorne_fakebinary__separation,)&&\
CCTK_DECLARE(CCTK_REAL,Thorne_fakebinary__smoothing,)&&\
CCTK_DECLARE(CCTK_REAL,anti_de_Sitter_Lambda__scale,)&&\
CCTK_DECLARE(CCTK_REAL,boost_rotation_symmetric__amp,)&&\
CCTK_DECLARE(CCTK_REAL,boost_rotation_symmetric__min_d,)&&\
CCTK_DECLARE(CCTK_REAL,boost_rotation_symmetric__scale,)&&\
CCTK_DECLARE(CCTK_REAL,bowl__center,)&&\
CCTK_DECLARE(CCTK_REAL,bowl__sigma,)&&\
CCTK_DECLARE(CCTK_REAL,bowl__sigma_t,)&&\
CCTK_DECLARE(CCTK_REAL,bowl__strength,)&&\
CCTK_DECLARE(CCTK_REAL,bowl__t0,)&&\
CCTK_DECLARE(CCTK_REAL,bowl__x_scale,)&&\
CCTK_DECLARE(CCTK_REAL,bowl__y_scale,)&&\
CCTK_DECLARE(CCTK_REAL,bowl__z_scale,)&&\
CCTK_DECLARE(CCTK_REAL,constant_density_star__mass,)&&\
CCTK_DECLARE(CCTK_REAL,constant_density_star__radius,)&&\
CCTK_DECLARE(CCTK_REAL,de_Sitter_Lambda__scale,)&&\
CCTK_DECLARE(CCTK_REAL,de_Sitter__scale,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__Hubble,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__mass1,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__mass2,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__mass3,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__mass4,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__x1,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__x2,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__x3,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__x4,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__y1,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__y2,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__y3,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__y4,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__z1,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__z2,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__z3,)&&\
CCTK_DECLARE(CCTK_REAL,multi_BH__z4,)&&\
CCTK_DECLARE(CCTK_STRING,Minkowski_gauge_wave__what_fn,)&&\
CCTK_DECLARE(CCTK_STRING,Thorne_fakebinary__atype,)&&\
CCTK_DECLARE(CCTK_STRING,bowl__shape,)&&\
CCTK_DECLARE(CCTK_STRING,exact_model,)&&\
CCTK_DECLARE(CCTK_INT,Kerr_KerrSchild__parabolic,)&&\
CCTK_DECLARE(CCTK_INT,Kerr_KerrSchild__power,)&&\
CCTK_DECLARE(CCTK_INT,Minkowski_conf_wave__direction,)&&\
CCTK_DECLARE(CCTK_INT,Minkowski_gauge_wave__diagonal,)&&\
CCTK_DECLARE(CCTK_INT,Thorne_fakebinary__retarded,)&&\
CCTK_DECLARE(CCTK_INT,bowl__evolve,)&&\
CCTK_DECLARE(CCTK_INT,multi_BH__nBH,)&&\
COMMON /exactrest/Alvi__mass1, Alvi__mass2, Alvi__separation, Bertotti__Lambda, Bianchi_I__scale, Goedel__scale, Gowdy_wave__amplitude, Kasner_generalized__p1, Kasner_generalized__p2, Kasner_like__q, Kerr_BoyerLindquist__mass, Kerr_BoyerLindquist__spin, Kerr_KerrSchild__boost_v, Kerr_KerrSchild__epsilon, Kerr_KerrSchild__mass, Kerr_KerrSchild__spin, Kerr_KerrSchild__t, Kerr_KerrSchild__x, Kerr_KerrSchild__y, Kerr_KerrSchild__z, Lemaitre__Lambda, Lemaitre__R0, Lemaitre__epsilon0, Lemaitre__kappa, Minkowski_conf_wave__amplitude, Minkowski_conf_wave__wavelength, Minkowski_funny__amplitude, Minkowski_funny__sigma, Minkowski_gauge_wave__amplitude, Minkowski_gauge_wave__lambda, Minkowski_gauge_wave__omega, Minkowski_gauge_wave__phase, Minkowski_shift__amplitude, Minkowski_shift__sigma, Schwarzschild_BL__epsilon, Schwarzschild_BL__mass, Schwarzschild_EF__epsilon, Schwarzschild_EF__mass, Schwarzschild_Lemaitre__Lambda, Schwarzschild_Lemaitre__mass, Schwarzschild_Novikov__epsilon, Schwarzschild_Novikov__mass, Schwarzschild_PG__epsilon, Schwarzschild_PG__mass, Thorne_fakebinary__Omega0, Thorne_fakebinary__epsilon, Thorne_fakebinary__mass, Thorne_fakebinary__separation, Thorne_fakebinary__smoothing, anti_de_Sitter_Lambda__scale, boost_rotation_symmetric__amp, boost_rotation_symmetric__min_d, boost_rotation_symmetric__scale, bowl__center, bowl__sigma, bowl__sigma_t, bowl__strength, bowl__t0, bowl__x_scale, bowl__y_scale, bowl__z_scale, constant_density_star__mass, constant_density_star__radius, de_Sitter_Lambda__scale, de_Sitter__scale, multi_BH__Hubble, multi_BH__mass1, multi_BH__mass2, multi_BH__mass3, multi_BH__mass4, multi_BH__x1, multi_BH__x2, multi_BH__x3, multi_BH__x4, multi_BH__y1, multi_BH__y2, multi_BH__y3, multi_BH__y4, multi_BH__z1, multi_BH__z2, multi_BH__z3, multi_BH__z4, Minkowski_gauge_wave__what_fn, Thorne_fakebinary__atype, bowl__shape, exact_model, Kerr_KerrSchild__parabolic, Kerr_KerrSchild__power, Minkowski_conf_wave__direction, Minkowski_gauge_wave__diagonal, Thorne_fakebinary__retarded, bowl__evolve, multi_BH__nBH&&\
CCTK_DECLARE(CCTK_REAL,boost_vx,)&&\
CCTK_DECLARE(CCTK_REAL,boost_vy,)&&\
CCTK_DECLARE(CCTK_REAL,boost_vz,)&&\
CCTK_DECLARE(CCTK_REAL,exact_eps,)&&\
CCTK_DECLARE(CCTK_REAL,exblend_rout,)&&\
CCTK_DECLARE(CCTK_REAL,exblend_width,)&&\
CCTK_DECLARE(CCTK_REAL,rotation_euler_phi,)&&\
CCTK_DECLARE(CCTK_REAL,rotation_euler_psi,)&&\
CCTK_DECLARE(CCTK_REAL,rotation_euler_theta,)&&\
CCTK_DECLARE(CCTK_REAL,shift_add_x,)&&\
CCTK_DECLARE(CCTK_REAL,shift_add_y,)&&\
CCTK_DECLARE(CCTK_REAL,shift_add_z,)&&\
CCTK_DECLARE(CCTK_REAL,slice_Gauss_ampl,)&&\
CCTK_DECLARE(CCTK_REAL,slice_Gauss_width,)&&\
CCTK_DECLARE(CCTK_STRING,overwrite_boundary,)&&\
CCTK_DECLARE(CCTK_INT,exact_order,)&&\
CCTK_DECLARE(CCTK_INT,exblend_Ks,)&&\
CCTK_DECLARE(CCTK_INT,exblend_gauge,)&&\
CCTK_DECLARE(CCTK_INT,exblend_gs,)&&\
COMMON /Exactpriv/boost_vx, boost_vy, boost_vz, exact_eps, exblend_rout, exblend_width, rotation_euler_phi, rotation_euler_psi, rotation_euler_theta, shift_add_x, shift_add_y, shift_add_z, slice_Gauss_ampl, slice_Gauss_width, overwrite_boundary, exact_order, exblend_Ks, exblend_gauge, exblend_gs&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,dtlapse_evolution_method,)&&\
CCTK_DECLARE(CCTK_STRING,dtshift_evolution_method,)&&\
CCTK_DECLARE(CCTK_STRING,evolution_method,)&&\
CCTK_DECLARE(CCTK_STRING,initial_data,)&&\
CCTK_DECLARE(CCTK_STRING,initial_dtlapse,)&&\
CCTK_DECLARE(CCTK_STRING,initial_dtshift,)&&\
CCTK_DECLARE(CCTK_STRING,initial_lapse,)&&\
CCTK_DECLARE(CCTK_STRING,initial_shift,)&&\
CCTK_DECLARE(CCTK_STRING,lapse_evolution_method,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,metric_type,)&&\
CCTK_DECLARE(CCTK_STRING,shift_evolution_method,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH2,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH4,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH6,)&&\
COMMON /ADMBASErest/CCTKH0, dtlapse_evolution_method, dtshift_evolution_method, evolution_method, initial_data, initial_dtlapse, initial_dtshift, initial_lapse, initial_shift, lapse_evolution_method, CCTKH1, CCTKH3, metric_type, shift_evolution_method, CCTKH5, CCTKH2, CCTKH4, CCTKH6&&\
CCTK_DECLARE(CCTK_STRING,conformal_storage,)&&\
COMMON /STATICCONFORMALrest/conformal_storage&&\

