#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,array1d_dx_i,)&&\
CCTK_DECLARE(CCTK_REAL,array1d_dy_i,)&&\
CCTK_DECLARE(CCTK_REAL,array1d_dz_i,)&&\
CCTK_DECLARE(CCTK_REAL,array1d_x0,)&&\
CCTK_DECLARE(CCTK_REAL,array1d_y0,)&&\
CCTK_DECLARE(CCTK_REAL,array1d_z0,)&&\
CCTK_DECLARE(CCTK_REAL,array2d_dx_i,)&&\
CCTK_DECLARE(CCTK_REAL,array2d_dx_j,)&&\
CCTK_DECLARE(CCTK_REAL,array2d_dy_i,)&&\
CCTK_DECLARE(CCTK_REAL,array2d_dy_j,)&&\
CCTK_DECLARE(CCTK_REAL,array2d_dz_i,)&&\
CCTK_DECLARE(CCTK_REAL,array2d_dz_j,)&&\
CCTK_DECLARE(CCTK_REAL,array2d_x0,)&&\
CCTK_DECLARE(CCTK_REAL,array2d_y0,)&&\
CCTK_DECLARE(CCTK_REAL,array2d_z0,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_dx_i,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_dx_j,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_dx_k,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_dy_i,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_dy_j,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_dy_k,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_dz_i,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_dz_j,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_dz_k,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_x0,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_y0,)&&\
CCTK_DECLARE(CCTK_REAL,array3d_z0,)&&\
CCTK_DECLARE(CCTK_REAL,parray1d_dx_i,)&&\
CCTK_DECLARE(CCTK_REAL,parray1d_dy_i,)&&\
CCTK_DECLARE(CCTK_REAL,parray1d_dz_i,)&&\
CCTK_DECLARE(CCTK_REAL,parray1d_x0,)&&\
CCTK_DECLARE(CCTK_REAL,parray1d_y0,)&&\
CCTK_DECLARE(CCTK_REAL,parray1d_z0,)&&\
CCTK_DECLARE(CCTK_REAL,parray2d_dx_i,)&&\
CCTK_DECLARE(CCTK_REAL,parray2d_dx_j,)&&\
CCTK_DECLARE(CCTK_REAL,parray2d_dy_i,)&&\
CCTK_DECLARE(CCTK_REAL,parray2d_dy_j,)&&\
CCTK_DECLARE(CCTK_REAL,parray2d_dz_i,)&&\
CCTK_DECLARE(CCTK_REAL,parray2d_dz_j,)&&\
CCTK_DECLARE(CCTK_REAL,parray2d_x0,)&&\
CCTK_DECLARE(CCTK_REAL,parray2d_y0,)&&\
CCTK_DECLARE(CCTK_REAL,parray2d_z0,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_dx_i,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_dx_j,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_dx_k,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_dy_i,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_dy_j,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_dy_k,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_dz_i,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_dz_j,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_dz_k,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_x0,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_y0,)&&\
CCTK_DECLARE(CCTK_REAL,parray3d_z0,)&&\
CCTK_DECLARE(CCTK_REAL,scalar_x0,)&&\
CCTK_DECLARE(CCTK_REAL,scalar_y0,)&&\
CCTK_DECLARE(CCTK_REAL,scalar_z0,)&&\
CCTK_DECLARE(CCTK_STRING,array1d_vars,(100))&&\
CCTK_DECLARE(CCTK_STRING,array2d_vars,(100))&&\
CCTK_DECLARE(CCTK_STRING,array3d_vars,(100))&&\
CCTK_DECLARE(CCTK_STRING,interpolator_coordinates,)&&\
CCTK_DECLARE(CCTK_STRING,interpolator_name,)&&\
CCTK_DECLARE(CCTK_STRING,interpolator_options,)&&\
CCTK_DECLARE(CCTK_STRING,parray1d_vars,(100))&&\
CCTK_DECLARE(CCTK_STRING,parray2d_vars,(100))&&\
CCTK_DECLARE(CCTK_STRING,parray3d_vars,(100))&&\
CCTK_DECLARE(CCTK_STRING,scalar_vars,(100))&&\
CCTK_DECLARE(CCTK_INT,array1d_npoints_i,)&&\
CCTK_DECLARE(CCTK_INT,array1d_spacederivs,(100))&&\
CCTK_DECLARE(CCTK_INT,array1d_timederivs,(100))&&\
CCTK_DECLARE(CCTK_INT,array2d_npoints_i,)&&\
CCTK_DECLARE(CCTK_INT,array2d_npoints_j,)&&\
CCTK_DECLARE(CCTK_INT,array3d_npoints_i,)&&\
CCTK_DECLARE(CCTK_INT,array3d_npoints_j,)&&\
CCTK_DECLARE(CCTK_INT,array3d_npoints_k,)&&\
CCTK_DECLARE(CCTK_INT,carpetinterp2_interpolator_order,)&&\
CCTK_DECLARE(CCTK_INT,narrays1d,)&&\
CCTK_DECLARE(CCTK_INT,narrays2d,)&&\
CCTK_DECLARE(CCTK_INT,narrays3d,)&&\
CCTK_DECLARE(CCTK_INT,nghosts,)&&\
CCTK_DECLARE(CCTK_INT,nparrays1d,)&&\
CCTK_DECLARE(CCTK_INT,nparrays2d,)&&\
CCTK_DECLARE(CCTK_INT,nparrays3d,)&&\
CCTK_DECLARE(CCTK_INT,nscalars,)&&\
CCTK_DECLARE(CCTK_INT,parray1d_npoints_i,)&&\
CCTK_DECLARE(CCTK_INT,parray1d_spacederivs,(100))&&\
CCTK_DECLARE(CCTK_INT,parray1d_timederivs,(100))&&\
CCTK_DECLARE(CCTK_INT,parray2d_npoints_i,)&&\
CCTK_DECLARE(CCTK_INT,parray2d_npoints_j,)&&\
CCTK_DECLARE(CCTK_INT,parray3d_npoints_i,)&&\
CCTK_DECLARE(CCTK_INT,parray3d_npoints_j,)&&\
CCTK_DECLARE(CCTK_INT,parray3d_npoints_k,)&&\
CCTK_DECLARE(CCTK_INT,use_carpetinterp2,)&&\
COMMON /InterpToArrayrest/array1d_dx_i, array1d_dy_i, array1d_dz_i, array1d_x0, array1d_y0, array1d_z0, array2d_dx_i, array2d_dx_j, array2d_dy_i, array2d_dy_j, array2d_dz_i, array2d_dz_j, array2d_x0, array2d_y0, array2d_z0, array3d_dx_i, array3d_dx_j, array3d_dx_k, array3d_dy_i, array3d_dy_j, array3d_dy_k, array3d_dz_i, array3d_dz_j, array3d_dz_k, array3d_x0, array3d_y0, array3d_z0, parray1d_dx_i, parray1d_dy_i, parray1d_dz_i, parray1d_x0, parray1d_y0, parray1d_z0, parray2d_dx_i, parray2d_dx_j, parray2d_dy_i, parray2d_dy_j, parray2d_dz_i, parray2d_dz_j, parray2d_x0, parray2d_y0, parray2d_z0, parray3d_dx_i, parray3d_dx_j, parray3d_dx_k, parray3d_dy_i, parray3d_dy_j, parray3d_dy_k, parray3d_dz_i, parray3d_dz_j, parray3d_dz_k, parray3d_x0, parray3d_y0, parray3d_z0, scalar_x0, scalar_y0, scalar_z0, array1d_vars, array2d_vars, array3d_vars, interpolator_coordinates, interpolator_name, interpolator_options, parray1d_vars, parray2d_vars, parray3d_vars, scalar_vars, array1d_npoints_i, array1d_spacederivs, array1d_timederivs, array2d_npoints_i, array2d_npoints_j, array3d_npoints_i, array3d_npoints_j, array3d_npoints_k, carpetinterp2_interpolator_order, narrays1d, narrays2d, narrays3d, nghosts, nparrays1d, nparrays2d, nparrays3d, nscalars, parray1d_npoints_i, parray1d_spacederivs, parray1d_timederivs, parray2d_npoints_i, parray2d_npoints_j, parray3d_npoints_i, parray3d_npoints_j, parray3d_npoints_k, use_carpetinterp2&&\

