#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_STRING,extcurv_boundary,)&&\
CCTK_DECLARE(CCTK_STRING,extcurv_boundary_options,)&&\
CCTK_DECLARE(CCTK_INT,calc_extcurv,)&&\
CCTK_DECLARE(CCTK_INT,copy_to_next,)&&\
CCTK_DECLARE(CCTK_INT,copy_to_prev,)&&\
CCTK_DECLARE(CCTK_INT,copy_to_prev2,)&&\
COMMON /CalcKpriv/extcurv_boundary, extcurv_boundary_options, calc_extcurv, copy_to_next, copy_to_prev, copy_to_prev2&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH8,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH10,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH12,)&&\
CCTK_DECLARE(CCTK_STRING,metric_type,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH14,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH15,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH11,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH13,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH16,)&&\
COMMON /ADMBASErest/CCTKH0, CCTKH1, CCTKH2, CCTKH3, CCTKH4, CCTKH5, CCTKH6, CCTKH7, CCTKH8, CCTKH9, CCTKH10, CCTKH12, metric_type, CCTKH14, CCTKH15, CCTKH11, CCTKH13, CCTKH16&&\

