#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,GAMMA_SPEED_LIMIT,)&&\
CCTK_DECLARE(CCTK_REAL,K_poly,)&&\
CCTK_DECLARE(CCTK_REAL,Psi6threshold,)&&\
CCTK_DECLARE(CCTK_REAL,Sym_Bz,)&&\
CCTK_DECLARE(CCTK_REAL,gamma_th,)&&\
CCTK_DECLARE(CCTK_REAL,rho_b_atm,)&&\
CCTK_DECLARE(CCTK_REAL,rho_b_max,)&&\
CCTK_DECLARE(CCTK_REAL,tau_atm,)&&\
CCTK_DECLARE(CCTK_STRING,EM_BC,)&&\
CCTK_DECLARE(CCTK_STRING,Matter_BC,)&&\
CCTK_DECLARE(CCTK_STRING,Symmetry,)&&\
CCTK_DECLARE(CCTK_INT,IllinoisGRMHD_MaxNumEvolvedVars,)&&\
CCTK_DECLARE(CCTK_INT,conserv_to_prims_debug,)&&\
CCTK_DECLARE(CCTK_INT,neos,)&&\
CCTK_DECLARE(CCTK_INT,update_Tmunu,)&&\
COMMON /IllinoisGRMHDrest/GAMMA_SPEED_LIMIT, K_poly, Psi6threshold, Sym_Bz, gamma_th, rho_b_atm, rho_b_max, tau_atm, EM_BC, Matter_BC, Symmetry, IllinoisGRMHD_MaxNumEvolvedVars, conserv_to_prims_debug, neos, update_Tmunu&&\
CCTK_DECLARE(CCTK_REAL,damp_lorenz,)&&\
COMMON /IllinoisGRMHDpriv/damp_lorenz&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH8,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH10,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH11,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH12,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH13,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH14,)&&\
CCTK_DECLARE(CCTK_INT,lapse_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,metric_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,shift_timelevels,)&&\
COMMON /ADMBASErest/CCTKH0, CCTKH1, CCTKH2, CCTKH3, CCTKH4, CCTKH5, CCTKH6, CCTKH7, CCTKH8, CCTKH9, CCTKH10, CCTKH11, CCTKH12, CCTKH13, CCTKH14, lapse_timelevels, metric_timelevels, shift_timelevels&&\
CCTK_DECLARE(CCTK_INT,CCTKH15,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH16,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH17,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH18,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH19,)&&\
CCTK_DECLARE(CCTK_INT,MoL_Num_Evolved_Vars,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH20,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH21,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH22,)&&\
COMMON /METHODOFLINESrest/CCTKH15, CCTKH16, CCTKH17, CCTKH18, CCTKH19, MoL_Num_Evolved_Vars, CCTKH20, CCTKH21, CCTKH22&&\

