#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_STRING,surface_name,(10))&&\
CCTK_DECLARE(CCTK_INT,surface,(10))&&\
CCTK_DECLARE(CCTK_INT,verbose,)&&\
COMMON /CarpetTrackerpriv/surface_name, surface, verbose&&\
CCTK_DECLARE(CCTK_REAL,CCTKH2,(42))&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,(42))&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH0,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH3,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH4,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH6,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH7,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH8,(42))&&\
CCTK_DECLARE(CCTK_INT,nsurfaces,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH9,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH11,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH12,(42))&&\
CCTK_DECLARE(CCTK_INT,CCTKH13,)&&\
COMMON /SPHERICALSURFACErest/CCTKH2, CCTKH1, CCTKH5, CCTKH0, CCTKH3, CCTKH4, CCTKH6, CCTKH7, CCTKH8, nsurfaces, CCTKH9, CCTKH10, CCTKH11, CCTKH12, CCTKH13&&\

