/*@@
   @header  LoopControl/CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn LoopControl
   @enddesc
 @@*/


#ifndef _LOOPCONTROL_PARAMETERS_H_
#define _LOOPCONTROL_PARAMETERS_H_ 1

#include "CParameterStructNames.h"
#include "ParameterCGlobal.h"
#include "ParameterCPrivateLOOPCONTROL.h"
#include "ParameterCRestrictedIO.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_PRIVATE_LOOPCONTROL_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (const char * const, out_dir, CCTK_PARAMETER__IOUtil__out_dir); \

#ifndef CCTK_PARAMETER__IOUtil__out_dir
#  define CCTK_PARAMETER__IOUtil__out_dir RESTRICTED_IO_STRUCT.out_dir
#endif

#endif  /* _LOOPCONTROL_PARAMETERS_H_ */

