/*@@
   @header  TestInclude1/CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn TestInclude1
   @enddesc
 @@*/


#ifndef _TESTINCLUDE1_PARAMETERS_H_
#define _TESTINCLUDE1_PARAMETERS_H_ 1

#include "CParameterStructNames.h"
#include "ParameterCGlobal.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \


#endif  /* _TESTINCLUDE1_PARAMETERS_H_ */

