#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,CCTKH1,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH2,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH3,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH4,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH14,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH15,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH16,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH17,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH18,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH19,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH20,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH21,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,domain,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH13,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH7,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH8,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH9,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH11,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH12,)&&\
COMMON /GRIDrest/CCTKH1, CCTKH2, CCTKH3, CCTKH4, CCTKH14, CCTKH15, CCTKH16, CCTKH17, CCTKH18, CCTKH19, CCTKH20, CCTKH21, CCTKH0, domain, CCTKH5, CCTKH6, CCTKH13, CCTKH7, CCTKH8, CCTKH9, CCTKH10, CCTKH11, CCTKH12&&\

