#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_STRING,filename,)&&\
COMMON /Meudon_Mag_NSpriv/filename&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,initial_data,)&&\
CCTK_DECLARE(CCTK_STRING,initial_dtlapse,)&&\
CCTK_DECLARE(CCTK_STRING,initial_dtshift,)&&\
CCTK_DECLARE(CCTK_STRING,initial_lapse,)&&\
CCTK_DECLARE(CCTK_STRING,initial_shift,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH10,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH11,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH6,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH8,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH12,)&&\
COMMON /ADMBASErest/CCTKH0, CCTKH1, CCTKH2, CCTKH3, initial_data, initial_dtlapse, initial_dtshift, initial_lapse, initial_shift, CCTKH4, CCTKH5, CCTKH7, CCTKH9, CCTKH10, CCTKH11, CCTKH6, CCTKH8, CCTKH12&&\
CCTK_DECLARE(CCTK_STRING,CCTKH13,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH14,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH15,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH16,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH17,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH19,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH20,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH21,)&&\
CCTK_DECLARE(CCTK_STRING,initial_Bvec,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH22,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH23,)&&\
CCTK_DECLARE(CCTK_STRING,initial_hydro,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH24,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH25,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH26,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH18,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH27,)&&\
COMMON /HYDROBASErest/CCTKH13, CCTKH14, CCTKH15, CCTKH16, CCTKH17, CCTKH19, CCTKH20, CCTKH21, initial_Bvec, CCTKH22, CCTKH23, initial_hydro, CCTKH24, CCTKH25, CCTKH26, CCTKH18, CCTKH27&&\

