#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_INT,periodic,)&&\
CCTK_DECLARE(CCTK_INT,periodic_x,)&&\
CCTK_DECLARE(CCTK_INT,periodic_y,)&&\
CCTK_DECLARE(CCTK_INT,periodic_z,)&&\
COMMON /Driverrest/periodic, periodic_x, periodic_y, periodic_z&&\
CCTK_DECLARE(CCTK_REAL,aspect_ratio_x,)&&\
CCTK_DECLARE(CCTK_REAL,aspect_ratio_y,)&&\
CCTK_DECLARE(CCTK_REAL,aspect_ratio_z,)&&\
CCTK_DECLARE(CCTK_REAL,ghost_zone_cost,)&&\
CCTK_DECLARE(CCTK_REAL,maximum_imbalance,)&&\
CCTK_DECLARE(CCTK_REAL,timing_average_window_minutes,)&&\
CCTK_DECLARE(CCTK_STRING,base_extents,)&&\
CCTK_DECLARE(CCTK_STRING,base_outerbounds,)&&\
CCTK_DECLARE(CCTK_STRING,eno_interpolation_type,)&&\
CCTK_DECLARE(CCTK_STRING,ghost_sizes,)&&\
CCTK_DECLARE(CCTK_STRING,grid_coordinates_filename,)&&\
CCTK_DECLARE(CCTK_STRING,grid_structure_filename,)&&\
CCTK_DECLARE(CCTK_STRING,model,)&&\
CCTK_DECLARE(CCTK_STRING,processor_topology,)&&\
CCTK_DECLARE(CCTK_STRING,prolongation_orders_space,)&&\
CCTK_DECLARE(CCTK_STRING,refinement_centering,)&&\
CCTK_DECLARE(CCTK_STRING,space_refinement_factors,)&&\
CCTK_DECLARE(CCTK_STRING,time_refinement_factors,)&&\
CCTK_DECLARE(CCTK_STRING,timer_file,)&&\
CCTK_DECLARE(CCTK_INT,adaptive_stepsize,)&&\
CCTK_DECLARE(CCTK_INT,additional_buffer_zones,)&&\
CCTK_DECLARE(CCTK_INT,additional_overlap_zones,)&&\
CCTK_DECLARE(CCTK_INT,barriers,)&&\
CCTK_DECLARE(CCTK_INT,check_for_poison,)&&\
CCTK_DECLARE(CCTK_INT,checksum_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,constant_load_per_processor,)&&\
CCTK_DECLARE(CCTK_INT,convergence_factor,)&&\
CCTK_DECLARE(CCTK_INT,convergence_level,)&&\
CCTK_DECLARE(CCTK_INT,domain_from_coordbase,)&&\
CCTK_DECLARE(CCTK_INT,domain_from_multipatch,)&&\
CCTK_DECLARE(CCTK_INT,enable_all_storage,)&&\
CCTK_DECLARE(CCTK_INT,enable_no_storage,)&&\
CCTK_DECLARE(CCTK_INT,ghost_size,)&&\
CCTK_DECLARE(CCTK_INT,ghost_size_x,)&&\
CCTK_DECLARE(CCTK_INT,ghost_size_y,)&&\
CCTK_DECLARE(CCTK_INT,ghost_size_z,)&&\
CCTK_DECLARE(CCTK_INT,global_nsize,)&&\
CCTK_DECLARE(CCTK_INT,global_nx,)&&\
CCTK_DECLARE(CCTK_INT,global_ny,)&&\
CCTK_DECLARE(CCTK_INT,global_nz,)&&\
CCTK_DECLARE(CCTK_INT,granularity,)&&\
CCTK_DECLARE(CCTK_INT,granularity_boundary,)&&\
CCTK_DECLARE(CCTK_INT,include_local_mode_in_mode_timer_tree,)&&\
CCTK_DECLARE(CCTK_INT,include_maps_in_mode_timer_tree,)&&\
CCTK_DECLARE(CCTK_INT,init_3_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,init_each_timelevel,)&&\
CCTK_DECLARE(CCTK_INT,init_fill_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,max_poison_locations,)&&\
CCTK_DECLARE(CCTK_INT,max_refinement_levels,)&&\
CCTK_DECLARE(CCTK_INT,max_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,min_points_per_proc,)&&\
CCTK_DECLARE(CCTK_INT,no_split_direction,)&&\
CCTK_DECLARE(CCTK_INT,num_convergence_levels,)&&\
CCTK_DECLARE(CCTK_INT,num_integrator_substeps,)&&\
CCTK_DECLARE(CCTK_INT,num_maps,)&&\
CCTK_DECLARE(CCTK_INT,num_threads,)&&\
CCTK_DECLARE(CCTK_INT,output_after_regridding,)&&\
CCTK_DECLARE(CCTK_INT,output_initialise_timer_tree,)&&\
CCTK_DECLARE(CCTK_INT,output_internal_data,)&&\
CCTK_DECLARE(CCTK_INT,output_timer_tree_every,)&&\
CCTK_DECLARE(CCTK_INT,output_timers_every,)&&\
CCTK_DECLARE(CCTK_INT,output_xml_timer_tree,)&&\
CCTK_DECLARE(CCTK_INT,poison_new_timelevels,)&&\
CCTK_DECLARE(CCTK_INT,poison_value,)&&\
CCTK_DECLARE(CCTK_INT,print_grid_info,)&&\
CCTK_DECLARE(CCTK_INT,print_timestats_every,)&&\
CCTK_DECLARE(CCTK_INT,processor_topology_3d_x,)&&\
CCTK_DECLARE(CCTK_INT,processor_topology_3d_y,)&&\
CCTK_DECLARE(CCTK_INT,processor_topology_3d_z,)&&\
CCTK_DECLARE(CCTK_INT,prolongate_initial_data,)&&\
CCTK_DECLARE(CCTK_INT,prolongation_order_space,)&&\
CCTK_DECLARE(CCTK_INT,prolongation_order_time,)&&\
CCTK_DECLARE(CCTK_INT,recompose_verbose,)&&\
CCTK_DECLARE(CCTK_INT,refine_timestep,)&&\
CCTK_DECLARE(CCTK_INT,refinement_factor,)&&\
CCTK_DECLARE(CCTK_INT,regrid_during_initialisation,)&&\
CCTK_DECLARE(CCTK_INT,regrid_during_recovery,)&&\
CCTK_DECLARE(CCTK_INT,regrid_in_level_mode,)&&\
CCTK_DECLARE(CCTK_INT,same_number_of_components_on_each_process,)&&\
CCTK_DECLARE(CCTK_INT,schedule_barriers,)&&\
CCTK_DECLARE(CCTK_INT,set_cpu_affinity,)&&\
CCTK_DECLARE(CCTK_INT,split_components,)&&\
CCTK_DECLARE(CCTK_INT,split_direction,)&&\
CCTK_DECLARE(CCTK_INT,storage_verbose,)&&\
CCTK_DECLARE(CCTK_INT,suppress_restriction,)&&\
CCTK_DECLARE(CCTK_INT,sync_barriers,)&&\
CCTK_DECLARE(CCTK_INT,sync_during_time_integration,)&&\
CCTK_DECLARE(CCTK_INT,time_interpolation_during_regridding,)&&\
CCTK_DECLARE(CCTK_INT,use_buffer_zones,)&&\
CCTK_DECLARE(CCTK_INT,use_overlap_zones,)&&\
CCTK_DECLARE(CCTK_INT,use_tapered_grids,)&&\
CCTK_DECLARE(CCTK_INT,use_unusedpoints_mask,)&&\
CCTK_DECLARE(CCTK_INT,verbose,)&&\
CCTK_DECLARE(CCTK_INT,veryverbose,)&&\
COMMON /Carpetpriv/aspect_ratio_x, aspect_ratio_y, aspect_ratio_z, ghost_zone_cost, maximum_imbalance, timing_average_window_minutes, base_extents, base_outerbounds, eno_interpolation_type, ghost_sizes, grid_coordinates_filename, grid_structure_filename, model, processor_topology, prolongation_orders_space, refinement_centering, space_refinement_factors, time_refinement_factors, timer_file, adaptive_stepsize, additional_buffer_zones, additional_overlap_zones, barriers, check_for_poison, checksum_timelevels, constant_load_per_processor, convergence_factor, convergence_level, domain_from_coordbase, domain_from_multipatch, enable_all_storage, enable_no_storage, ghost_size, ghost_size_x, ghost_size_y, ghost_size_z, global_nsize, global_nx, global_ny, global_nz, granularity, granularity_boundary, include_local_mode_in_mode_timer_tree, include_maps_in_mode_timer_tree, init_3_timelevels, init_each_timelevel, init_fill_timelevels, max_poison_locations, max_refinement_levels, max_timelevels, min_points_per_proc, no_split_direction, num_convergence_levels, num_integrator_substeps, num_maps, num_threads, output_after_regridding, output_initialise_timer_tree, output_internal_data, output_timer_tree_every, output_timers_every, output_xml_timer_tree, poison_new_timelevels, poison_value, print_grid_info, print_timestats_every, processor_topology_3d_x, processor_topology_3d_y, processor_topology_3d_z, prolongate_initial_data, prolongation_order_space, prolongation_order_time, recompose_verbose, refine_timestep, refinement_factor, regrid_during_initialisation, regrid_during_recovery, regrid_in_level_mode, same_number_of_components_on_each_process, schedule_barriers, set_cpu_affinity, split_components, split_direction, storage_verbose, suppress_restriction, sync_barriers, sync_during_time_integration, time_interpolation_during_regridding, use_buffer_zones, use_overlap_zones, use_tapered_grids, use_unusedpoints_mask, verbose, veryverbose&&\
CCTK_DECLARE(CCTK_REAL,cctk_final_time,)&&\
CCTK_DECLARE(CCTK_REAL,cctk_initial_time,)&&\
CCTK_DECLARE(CCTK_REAL,max_runtime,)&&\
CCTK_DECLARE(CCTK_STRING,terminate,)&&\
CCTK_DECLARE(CCTK_INT,cctk_itlast,)&&\
CCTK_DECLARE(CCTK_INT,terminate_next,)&&\
COMMON /CACTUSrest/cctk_final_time, cctk_initial_time, max_runtime, terminate, cctk_itlast, terminate_next&&\
CCTK_DECLARE(CCTK_INT,CCTKH0,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH1,)&&\
CCTK_DECLARE(CCTK_INT,restriction_order_space,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH2,)&&\
CCTK_DECLARE(CCTK_INT,use_higher_order_restriction,)&&\
COMMON /CARPETLIBrest/CCTKH0, CCTKH1, restriction_order_space, CCTKH2, use_higher_order_restriction&&\
CCTK_DECLARE(CCTK_STRING,initial_data_setup_method,)&&\
COMMON /INITBASErest/initial_data_setup_method&&\
CCTK_DECLARE(CCTK_REAL,CCTKH8,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH21,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH31,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH33,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH35,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH37,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH39,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH41,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH43,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH45,)&&\
CCTK_DECLARE(CCTK_REAL,CCTKH47,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH12,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH13,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH14,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH17,)&&\
CCTK_DECLARE(CCTK_STRING,out_dir,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH23,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH24,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH25,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH27,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH49,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH51,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH53,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH55,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH56,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH59,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH3,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH4,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH7,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH11,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH15,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH16,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH18,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH19,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH20,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH22,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH26,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH28,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH29,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH30,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH32,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH34,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH36,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH38,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH40,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH42,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH44,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH46,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH48,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH50,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH52,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH54,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH57,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH58,)&&\
COMMON /IOrest/CCTKH8, CCTKH21, CCTKH31, CCTKH33, CCTKH35, CCTKH37, CCTKH39, CCTKH41, CCTKH43, CCTKH45, CCTKH47, CCTKH5, CCTKH6, CCTKH9, CCTKH12, CCTKH13, CCTKH14, CCTKH17, out_dir, CCTKH23, CCTKH24, CCTKH25, CCTKH27, CCTKH49, CCTKH51, CCTKH53, CCTKH55, CCTKH56, CCTKH59, CCTKH3, CCTKH4, CCTKH7, CCTKH10, CCTKH11, CCTKH15, CCTKH16, CCTKH18, CCTKH19, CCTKH20, CCTKH22, CCTKH26, CCTKH28, CCTKH29, CCTKH30, CCTKH32, CCTKH34, CCTKH36, CCTKH38, CCTKH40, CCTKH42, CCTKH44, CCTKH46, CCTKH48, CCTKH50, CCTKH52, CCTKH54, CCTKH57, CCTKH58&&\

