/*@@
   @file    RotatingSymmetry180_Functions.c
   @author  Automatically generated by CreateFunctionBindings.pl
   @desc
            The wrappers for functions provided by thorn RotatingSymmetry180.
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cctk_Flesh.h"
#include "cctk_WarnLevel.h"


CCTK_INT Register_RotatingSymmetry180(void);
CCTK_INT Register_RotatingSymmetry180(void)
{
  CCTK_INT ierr;

  ierr = 0;

  return ierr;
}
