/*@@
   @header  Hydro_Analysis/CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn Hydro_Analysis
   @enddesc
 @@*/


#ifndef _HYDRO_ANALYSIS_PARAMETERS_H_
#define _HYDRO_ANALYSIS_PARAMETERS_H_ 1

#include "CParameterStructNames.h"
#include "ParameterCGlobal.h"
#include "ParameterCPrivateHYDRO_ANALYSIS.h"
#include "ParameterCRestrictedHYDROBASE.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_PRIVATE_HYDRO_ANALYSIS_STRUCT_PARAMS \
  CCTK_DECLARE_INIT (CCTK_INT const, timelevels, CCTK_PARAMETER__HydroBase__timelevels); \

#ifndef CCTK_PARAMETER__HydroBase__timelevels
#  define CCTK_PARAMETER__HydroBase__timelevels RESTRICTED_HYDROBASE_STRUCT.timelevels
#endif

#endif  /* _HYDRO_ANALYSIS_PARAMETERS_H_ */

