#define DECLARE_CCTK_PARAMETERS \
CCTK_DECLARE(CCTK_REAL,amplitude,)&&\
CCTK_DECLARE(CCTK_REAL,wavecenter,)&&\
CCTK_DECLARE(CCTK_REAL,wavelength,)&&\
CCTK_DECLARE(CCTK_REAL,wavephi,)&&\
CCTK_DECLARE(CCTK_REAL,wavepulse,)&&\
CCTK_DECLARE(CCTK_REAL,wavetheta,)&&\
CCTK_DECLARE(CCTK_STRING,packet,)&&\
CCTK_DECLARE(CCTK_STRING,parity,)&&\
CCTK_DECLARE(CCTK_STRING,teuk_no_vee,)&&\
CCTK_DECLARE(CCTK_STRING,wavesgoing,)&&\
CCTK_DECLARE(CCTK_INT,mvalue,)&&\
COMMON /IDLinearWavespriv/amplitude, wavecenter, wavelength, wavephi, wavepulse, wavetheta, packet, parity, teuk_no_vee, wavesgoing, mvalue&&\
CCTK_DECLARE(CCTK_STRING,CCTKH0,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH1,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH2,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH3,)&&\
CCTK_DECLARE(CCTK_STRING,initial_data,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH4,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH5,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH6,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH7,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH8,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH9,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH11,)&&\
CCTK_DECLARE(CCTK_STRING,metric_type,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH13,)&&\
CCTK_DECLARE(CCTK_STRING,CCTKH14,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH10,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH12,)&&\
CCTK_DECLARE(CCTK_INT,CCTKH15,)&&\
COMMON /ADMBASErest/CCTKH0, CCTKH1, CCTKH2, CCTKH3, initial_data, CCTKH4, CCTKH5, CCTKH6, CCTKH7, CCTKH8, CCTKH9, CCTKH11, metric_type, CCTKH13, CCTKH14, CCTKH10, CCTKH12, CCTKH15&&\
CCTK_DECLARE(CCTK_STRING,conformal_storage,)&&\
COMMON /STATICCONFORMALrest/conformal_storage&&\

